/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.dictionary.datatype.__impl;

public class AMssqlPropertyDbTableWrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationWrapperImpl<com.sap.ide.metamodel.dictionary.datatype.AMssqlPropertyDbTable> implements com.sap.ide.metamodel.dictionary.datatype.AMssqlPropertyDbTable,com.sap.tc.moin.repository.Partitionable
{

    /**
     * The AMssqlPropertyDbTable wrapper
     */
    public AMssqlPropertyDbTableWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, com.sap.ide.metamodel.dictionary.datatype.__impl.AMssqlPropertyDbTableImpl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }
    
    private com.sap.ide.metamodel.dictionary.datatype.__impl.AMssqlPropertyDbTableImpl getCastWrappedObject() {
        return (com.sap.ide.metamodel.dictionary.datatype.__impl.AMssqlPropertyDbTableImpl) getWrappedObject();
    }

    public com.sap.ide.metamodel.dictionary.datatype.AMssqlPropertyDbTable unwrap() {
        return (com.sap.ide.metamodel.dictionary.datatype.AMssqlPropertyDbTable) getWrappedObject();
    }
    
    public boolean exists(com.sap.ide.metamodel.dictionary.datatype.DtMssqlTableProperty _MssqlProperty, com.sap.ide.metamodel.dictionary.datatype.DtDbTable _DbTable) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _MssqlProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _DbTable));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _MssqlProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _DbTable)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public com.sap.ide.metamodel.dictionary.datatype.DtMssqlTableProperty getMssqlProperty(com.sap.ide.metamodel.dictionary.datatype.DtDbTable _DbTable) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (com.sap.ide.metamodel.dictionary.datatype.DtMssqlTableProperty) wrapResult(getCastWrappedObject().getMssqlProperty(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _DbTable)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (com.sap.ide.metamodel.dictionary.datatype.DtMssqlTableProperty) wrapResult(getCastWrappedObject().getMssqlProperty(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _DbTable))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public com.sap.ide.metamodel.dictionary.datatype.DtDbTable getDbTable(com.sap.ide.metamodel.dictionary.datatype.DtMssqlTableProperty _MssqlProperty) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (com.sap.ide.metamodel.dictionary.datatype.DtDbTable) wrapResult(getCastWrappedObject().getDbTable(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _MssqlProperty)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (com.sap.ide.metamodel.dictionary.datatype.DtDbTable) wrapResult(getCastWrappedObject().getDbTable(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _MssqlProperty))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean add(com.sap.ide.metamodel.dictionary.datatype.DtMssqlTableProperty _MssqlProperty, com.sap.ide.metamodel.dictionary.datatype.DtDbTable _DbTable) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _MssqlProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _DbTable));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _MssqlProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _DbTable)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean remove(com.sap.ide.metamodel.dictionary.datatype.DtMssqlTableProperty _MssqlProperty, com.sap.ide.metamodel.dictionary.datatype.DtDbTable _DbTable) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _MssqlProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _DbTable));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _MssqlProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _DbTable)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }   

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.dictionary.datatype.AMssqlPropertyDbTable> get___JmiInterface() {
        return com.sap.ide.metamodel.dictionary.datatype.AMssqlPropertyDbTable.class;
    }

    protected String metaObjectToString() {
        return "com.sap.ide.metamodel.dictionary.datatype.AMssqlPropertyDbTable (Java Type)\nDictionary.datatype.A_MssqlProperty_DbTable (MOF Type)"; //$NON-NLS-1$
    }    
}