/**
* <copyright>
*
* Copyright (c) 2005, 2009 IBM Corporation and others.
* All rights reserved.   This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
*   IBM - Initial API and implementation
*   E.D.Willink - Elimination of some shift-reduce conflicts
*   E.D.Willink - Remove unnecessary warning suppression
*   E.D.Willink - Bugs 184048, 225493, 243976, 259818, 282882, 287993, 288040
*   Borland - Bug 242880
*
* </copyright>
*
* $Id: OCLParsersym.java,v 1.13 2009/10/10 11:47:30 ewillink Exp $
*/

package org.eclipse.ocl.parser;

/**
 * @noimplement This interface is not intended to be implemented by clients.
 * @noextend This interface is not intended to be extended by clients.
 */
@SuppressWarnings("nls")
public interface OCLParsersym {
	/**
	 * Token kind codes.
	 * 
	 * @noreference These constants are not intended to be referenced by clients.
	 */
    public final static int
      TK_STRING_LITERAL = 64,
      TK_INTEGER_LITERAL = 65,
      TK_REAL_LITERAL = 66,
      TK_PLUS = 44,
      TK_MINUS = 4,
      TK_MULTIPLY = 39,
      TK_DIVIDE = 59,
      TK_GREATER = 60,
      TK_LESS = 61,
      TK_EQUAL = 41,
      TK_GREATER_EQUAL = 62,
      TK_LESS_EQUAL = 63,
      TK_NOT_EQUAL = 67,
      TK_LPAREN = 1,
      TK_RPAREN = 3,
      TK_LBRACE = 86,
      TK_RBRACE = 72,
      TK_LBRACKET = 42,
      TK_RBRACKET = 73,
      TK_ARROW = 74,
      TK_BAR = 43,
      TK_COMMA = 5,
      TK_COLON = 2,
      TK_COLONCOLON = 6,
      TK_SEMICOLON = 79,
      TK_DOT = 75,
      TK_DOTDOT = 80,
      TK_ATPRE = 40,
      TK_CARET = 76,
      TK_CARETCARET = 77,
      TK_QUESTIONMARK = 87,
      TK_self = 7,
      TK_inv = 48,
      TK_pre = 49,
      TK_post = 50,
      TK_context = 45,
      TK_package = 70,
      TK_endpackage = 68,
      TK_def = 46,
      TK_if = 69,
      TK_then = 81,
      TK_else = 82,
      TK_endif = 83,
      TK_and = 51,
      TK_or = 52,
      TK_xor = 53,
      TK_not = 47,
      TK_implies = 78,
      TK_let = 71,
      TK_in = 84,
      TK_true = 8,
      TK_false = 9,
      TK_body = 54,
      TK_derive = 55,
      TK_init = 56,
      TK_null = 10,
      TK_invalid = 11,
      TK_static = 57,
      TK_Set = 12,
      TK_Bag = 13,
      TK_Sequence = 14,
      TK_Collection = 15,
      TK_OrderedSet = 16,
      TK_iterate = 17,
      TK_forAll = 18,
      TK_exists = 19,
      TK_isUnique = 20,
      TK_any = 21,
      TK_one = 22,
      TK_collect = 23,
      TK_select = 24,
      TK_reject = 25,
      TK_collectNested = 26,
      TK_sortedBy = 27,
      TK_closure = 28,
      TK_String = 29,
      TK_Integer = 30,
      TK_UnlimitedNatural = 31,
      TK_Real = 32,
      TK_Boolean = 33,
      TK_Tuple = 58,
      TK_OclAny = 34,
      TK_OclVoid = 35,
      TK_OclInvalid = 36,
      TK_OclMessage = 37,
      TK_EOF_TOKEN = 85,
      TK_IDENTIFIER = 38,
      TK_SINGLE_LINE_COMMENT = 88,
      TK_MULTI_LINE_COMMENT = 89,
      TK_ERROR_TOKEN = 90;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "LPAREN",
                 "COLON",
                 "RPAREN",
                 "MINUS",
                 "COMMA",
                 "COLONCOLON",
                 "self",
                 "true",
                 "false",
                 "null",
                 "invalid",
                 "Set",
                 "Bag",
                 "Sequence",
                 "Collection",
                 "OrderedSet",
                 "iterate",
                 "forAll",
                 "exists",
                 "isUnique",
                 "any",
                 "one",
                 "collect",
                 "select",
                 "reject",
                 "collectNested",
                 "sortedBy",
                 "closure",
                 "String",
                 "Integer",
                 "UnlimitedNatural",
                 "Real",
                 "Boolean",
                 "OclAny",
                 "OclVoid",
                 "OclInvalid",
                 "OclMessage",
                 "IDENTIFIER",
                 "MULTIPLY",
                 "ATPRE",
                 "EQUAL",
                 "LBRACKET",
                 "BAR",
                 "PLUS",
                 "context",
                 "def",
                 "not",
                 "inv",
                 "pre",
                 "post",
                 "and",
                 "or",
                 "xor",
                 "body",
                 "derive",
                 "init",
                 "static",
                 "Tuple",
                 "DIVIDE",
                 "GREATER",
                 "LESS",
                 "GREATER_EQUAL",
                 "LESS_EQUAL",
                 "STRING_LITERAL",
                 "INTEGER_LITERAL",
                 "REAL_LITERAL",
                 "NOT_EQUAL",
                 "endpackage",
                 "if",
                 "package",
                 "let",
                 "RBRACE",
                 "RBRACKET",
                 "ARROW",
                 "DOT",
                 "CARET",
                 "CARETCARET",
                 "implies",
                 "SEMICOLON",
                 "DOTDOT",
                 "then",
                 "else",
                 "endif",
                 "in",
                 "EOF_TOKEN",
                 "LBRACE",
                 "QUESTIONMARK",
                 "SINGLE_LINE_COMMENT",
                 "MULTI_LINE_COMMENT",
                 "ERROR_TOKEN"
             };

    public final static boolean isValidForParser = true;
}
