/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.application.__impl;

public final class ApplicationPackageImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefPackageImpl
{
        
    public static final java.util.Map<java.lang.String, java.lang.Integer> FEATURE_IDS;

    static {
        
        FEATURE_IDS = new java.util.HashMap<java.lang.String, java.lang.Integer>(10);
        FEATURE_IDS.put("Application", Integer.valueOf(0)); //$NON-NLS-1$
        FEATURE_IDS.put("ApplicationProperty", Integer.valueOf(1)); //$NON-NLS-1$
        FEATURE_IDS.put("A_ApplicationProperties_Application", Integer.valueOf(2)); //$NON-NLS-1$
        FEATURE_IDS.put("A_StartupPlug_application", Integer.valueOf(3)); //$NON-NLS-1$
        FEATURE_IDS.put("A_PropertyDefinitionSets_application", Integer.valueOf(4)); //$NON-NLS-1$
        FEATURE_IDS.put("A_PropertyDefinition_applicationProperty", Integer.valueOf(5)); //$NON-NLS-1$
        FEATURE_IDS.put("A_RootComponentConfiguration_application", Integer.valueOf(6)); //$NON-NLS-1$
    }

    // constructors    
    public ApplicationPackageImpl()
    {
        super();
    }
    public ApplicationPackageImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject)
    {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    // internal enumeration creators
    // internal structure type creators
    // nested packages
    // classes
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getApplication(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "Application"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getApplicationProperty(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "ApplicationProperty"); //$NON-NLS-1$
    }
    // associations
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAApplicationPropertiesApplication(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_ApplicationProperties_Application"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAStartupPlugApplication(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_StartupPlug_application"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAPropertyDefinitionSetsApplication(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_PropertyDefinitionSets_application"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAPropertyDefinitionApplicationProperty(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_PropertyDefinition_applicationProperty"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getARootComponentConfigurationApplication(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_RootComponentConfiguration_application"); //$NON-NLS-1$
    }
    // structure type creators

    protected java.lang.Object create___Extent(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        java.lang.String name = ((com.sap.tc.moin.repository.mmi.model.ModelElement) metaObject).getName();
        com.sap.tc.moin.repository.mmi.reflect.RefBaseObject result = null;
        try {
            switch (FEATURE_IDS.get(name)) {
                case 0:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.ide.metamodel.webdynpro.application.__impl.ApplicationImpl")); //$NON-NLS-1$
                case 1:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.ide.metamodel.webdynpro.application.__impl.ApplicationPropertyImpl")); //$NON-NLS-1$
                case 2:
                    return new com.sap.ide.metamodel.webdynpro.application.__impl.AApplicationPropertiesApplicationImpl(workspace, mofId, immediatePackage, metaObject);
                case 3:
                    return new com.sap.ide.metamodel.webdynpro.application.__impl.AStartupPlugApplicationImpl(workspace, mofId, immediatePackage, metaObject);
                case 4:
                    return new com.sap.ide.metamodel.webdynpro.application.__impl.APropertyDefinitionSetsApplicationImpl(workspace, mofId, immediatePackage, metaObject);
                case 5:
                    return new com.sap.ide.metamodel.webdynpro.application.__impl.APropertyDefinitionApplicationPropertyImpl(workspace, mofId, immediatePackage, metaObject);
                case 6:
                    return new com.sap.ide.metamodel.webdynpro.application.__impl.ARootComponentConfigurationApplicationImpl(workspace, mofId, immediatePackage, metaObject);
                default:
                    throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(name, null, "create___Extent()"); //$NON-NLS-1$
        }
        }
        catch(com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            throw ex;
        }
        catch(java.lang.Exception ex) {
            throw new com.sap.tc.moin.repository.mmi.reflect.JmiException(ex);
        }        
    }

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.webdynpro.application.ApplicationPackage> get___JmiInterface() {
        return com.sap.ide.metamodel.webdynpro.application.ApplicationPackage.class;
    }
    
    protected void initialize() {
        if (___refPackages == null) {
            ___refPackages = new java.util.ArrayList<RefPackageAndName>(0);
            ___refPackagesByName = new java.util.HashMap<String, RefPackageAndName>();
            @SuppressWarnings("unused")
            java.lang.String name = ""; //$NON-NLS-1$
            @SuppressWarnings("unused")
            RefPackageAndName rpan = null;
        }
  
        if (___refClasses == null) {
            ___refClasses = new java.util.ArrayList<RefClassAndName>(2);
            ___refClassesByName = new java.util.HashMap<String, RefClassAndName>();
            java.lang.String name = ""; //$NON-NLS-1$
            RefClassAndName rcan = null;
            name = "Application"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.application.Application"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
            name = "ApplicationProperty"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.application.ApplicationProperty"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
        }
  
        if (___refAssociations == null) {
            ___refAssociations = new java.util.ArrayList<RefAssociationAndName>(5);
            ___refAssociationsByName = new java.util.HashMap<String, RefAssociationAndName>();
            @SuppressWarnings("unused")
            java.lang.String name = ""; //$NON-NLS-1$
            @SuppressWarnings("unused")
            RefAssociationAndName raan = null;
            name = "A_ApplicationProperties_Application"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.application.AApplicationPropertiesApplication"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_StartupPlug_application"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.application.AStartupPlugApplication"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_PropertyDefinitionSets_application"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.application.APropertyDefinitionSetsApplication"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_PropertyDefinition_applicationProperty"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.application.APropertyDefinitionApplicationProperty"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_RootComponentConfiguration_application"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.application.ARootComponentConfigurationApplication"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
        }
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<com.sap.ide.metamodel.webdynpro.application.__impl.ApplicationPackageImpl> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new com.sap.ide.metamodel.webdynpro.application.__impl.ApplicationPackageWrapper(conn, this, synchronize);
    }

}