<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ocl"
    nsURI="http://www.eclipse.org/ocl/1.1.0/OCLUML" nsPrefix="ocl">
  <eSubpackages name="uml" nsURI="http://www.eclipse.org/ocl/1.1.0/UML" nsPrefix="ocl.uml">
    <eClassifiers xsi:type="ecore:EClass" name="AnyType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperations" upperBound="-1"
          eType="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"
          containment="true"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/AnyType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VoidType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperations" upperBound="-1"
          eType="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"
          containment="true"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/VoidType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperations" upperBound="-1"
          eType="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"
          containment="true"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/InvalidType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ElementType" eSuperTypes="../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier ../../org.eclipse.ocl/model/OCL.ecore#//types/ElementType"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperations" upperBound="-1"
          eType="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"
          containment="true"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/TypeType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessageType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperations" upperBound="-1"
          eType="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAttributes" upperBound="-1"
          eType="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"
          containment="true"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/MessageType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//PrimitiveType"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/PrimitiveType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionType">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/CollectionType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TupleType">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/TupleType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BagType">
      <eGenericSuperTypes eClassifier="#//uml/CollectionType"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/BagType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetType">
      <eGenericSuperTypes eClassifier="#//uml/CollectionType"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/SetType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedSetType">
      <eGenericSuperTypes eClassifier="#//uml/CollectionType"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/OrderedSetType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceType">
      <eGenericSuperTypes eClassifier="#//uml/CollectionType"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//types/SequenceType">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionInOCL">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//OpaqueExpression"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.ocl/model/OCL.ecore#//utilities/ExpressionInOCL">
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        <eTypeArguments eClassifier="ecore:EClass ../../../plugin/org.eclipse.uml2.uml/model/UML.ecore#//Parameter"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
