<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modifiedImpactAnalyzer"
    nsURI="http://de.hpi.sam.bp2009.benchframework.modifiedImpactAnalyzer" nsPrefix="benchframework.modifiedImpactAnalyzer">
  <eClassifiers xsi:type="ecore:EClass" name="ModifiedImpactAnalyzer" eSuperTypes="../../de.hpi.sam.bp2009.solution.impactAnalyzer/model/impactAnalyzer.ecore#//ImpactAnalyzer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Modified version of the Impact Analyzer to make it &quot;benchmarker enabled&quot;.&#xD;&#xA;It provides an extension point for Adapters to register for getting a notification once it communicates with another component of the system.&#xD;&#xA;To do so, it overrides methods of the Impact Analyzer and includes a call to sendBenchmarNotification()."/>
    </eAnnotations>
    <eOperations name="sendBenchmarkNotification">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Build and send a notification to all registered benchmarkers."/>
      </eAnnotations>
      <eParameters name="communicationPartner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="incoming" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncomingEventNotification" eSuperTypes="../../de.hpi.sam.bp2009.solution.eventManager/model/eventManager.ecore#//EventNotification">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutgoingResultNotification" eSuperTypes="../../de.hpi.sam.bp2009.solution.eventManager/model/eventManager.ecore#//EventNotification">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmbedModifiedIAOperator" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//Operator"/>
</ecore:EPackage>
