<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MiniJava"
    nsURI="http://www.furcas.org/example/minijava" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedClass" lowerBound="1"
        eType="#//ClassDeclaration" containment="true" eOpposite="#//ClassDeclaration/compilationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//ClassImport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package_" eType="#//Package"
        eOpposite="#//Package/compilationUnits"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassImport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedClass" lowerBound="1"
        eType="#//ClassDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//MemberDeclaration" containment="true" eOpposite="#//MemberDeclaration/owningClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compilationUnit" eType="#//CompilationUnit"
        eOpposite="#//CompilationUnit/containedClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compilationUnits" upperBound="-1"
        eType="#//CompilationUnit" containment="true" eOpposite="#//CompilationUnit/package_"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldDeclaration" eSuperTypes="#//MemberDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="MemberDeclaration" abstract="true" eSuperTypes="#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningClass" eType="#//ClassDeclaration"
        eOpposite="#//ClassDeclaration/members"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true" eOpposite="#//Parameter/owningDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodDeclaration" eSuperTypes="#//MemberDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eLiterals name="private"/>
    <eLiterals name="public"/>
    <eLiterals name="protected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningDeclaration" eType="#//MemberDeclaration"
        eOpposite="#//MemberDeclaration/parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ClassDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
</ecore:EPackage>
