<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oclToMqlOperator"
    nsURI="http://de.hpi.sam.bp2009.benchframework.oclToMqlOperator" nsPrefix="benchframework.oclToMqlOperator">
  <eClassifiers xsi:type="ecore:EClass" name="OclToMqlOperator" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//Operator">
    <eOperations name="executeQueries">
      <eParameters name="resourceSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclToMqlUtil">
    <eOperations name="evaluateMQL">
      <eParameters name="completeConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="resourceSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"/>
      <eParameters name="evaluator" eType="ecore:EClass ../../de.hpi.sam.bp2009.benchframework.queryEvaluator/model/queryEvaluator.ecore#//QueryEvaluator"/>
    </eOperations>
    <eOperations name="evaluateOCL">
      <eParameters name="completeConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="resourceSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"/>
      <eParameters name="evaluator" eType="ecore:EClass ../../de.hpi.sam.bp2009.benchframework.queryEvaluator/model/queryEvaluator.ecore#//QueryEvaluator"/>
    </eOperations>
    <eOperations name="getOCLExpressionForOCL">
      <eGenericType eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//expressions/OCLExpression">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="completeConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="resourceSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"/>
    </eOperations>
    <eOperations name="getOCLExpressionForMQL">
      <eGenericType eClassifier="ecore:EClass platform:/plugin/org.eclipse.ocl/model/OCL.ecore#//expressions/OCLExpression">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="completeConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="resourceSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclToMqlResult" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//ResultObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queriesToResults" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclToMqlOptionObject" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//OptionObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
