<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="interfaceconfiguration"
    nsURI="http://interfaceconfiguration/1.0" nsPrefix="interfaceconfiguration">
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" lowerBound="1"
        upperBound="-1" eType="#//Binding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requireingSyntax" lowerBound="1"
        eType="ecore:EClass TCS.ecore#//ConcreteSyntax"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providingSyntax" lowerBound="1"
        eType="ecore:EClass TCS.ecore#//ConcreteSyntax"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredTemplate" lowerBound="1"
        eType="ecore:EClass TCS.ecore#//Template"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedTemplate" lowerBound="1"
        eType="ecore:EClass TCS.ecore#//Template"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
