<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="textblockdefinition"
    nsURI="http://www.furcas.org/textblockdefinition" nsPrefix="com.sap.furcas.textblockdefinition">
  <eClassifiers xsi:type="ecore:EClass" name="TextBlockDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatPolicy" eType="#//FormatPolicy"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultTemplate" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parseRule" eType="ecore:EClass TCS.ecore#//Template">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="textBlockDefinition"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//TextBlockDefinition"
        eOpposite="#//TextBlockDefinition/subDefinitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subDefinitions" upperBound="-1"
        eType="#//TextBlockDefinition" containment="true" eOpposite="#//TextBlockDefinition/context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalisation" eType="#//TextBlockDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FormatPolicy">
    <eLiterals name="KEEP_ALWAYS"/>
    <eLiterals name="KEEP_NEVER"/>
    <eLiterals name="KEEP_BEFORE"/>
    <eLiterals name="KEEP_AFTER"/>
  </eClassifiers>
</ecore:EPackage>
