<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="textblocks"
    nsURI="http://www.furcas.org/textblocks" nsPrefix="com.sap.furcas.textblocks">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://de.hpi.sam.bp2009.OCL"/>
    <details key="validationDelegates" value="http://de.hpi.sam.bp2009.OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TextBlock" eSuperTypes="#//DocumentNode">
    <eOperations name="getSubBlocks" upperBound="-1" eType="#//TextBlock">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="body"/>
      </eAnnotations>
      <eAnnotations source="http://de.hpi.sam.bp2009.OCL">
        <details key="body" value="self.subNodes->select(n | n.oclIsKindOf(TextBlock)).oclAsType(TextBlock)"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getTokens" upperBound="-1" eType="#//AbstractToken">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="body"/>
      </eAnnotations>
      <eAnnotations source="http://de.hpi.sam.bp2009.OCL">
        <details key="body" value="self.subNodes->select(n | n.oclIsKindOf(AbstractToken)).oclAsType(AbstractToken)"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAdditionalTemplates" upperBound="-1" eType="ecore:EClass TCS.ecore#//Template"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass textblockdefinition.ecore#//TextblockDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subNodes" upperBound="-1"
        eType="#//DocumentNode" containment="true" eOpposite="#//DocumentNode/parent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentAltChoices" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementsInContext" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forEachContext" upperBound="-1"
        eType="#//ForEachContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cachedString" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractToken" eSuperTypes="#//DocumentNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lookahead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lookback" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OmittedToken" eSuperTypes="#//AbstractToken"/>
  <eClassifiers xsi:type="ecore:EClass" name="LexedToken" eSuperTypes="#//AbstractToken">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnlexedToken" eSuperTypes="#//AbstractToken"/>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="childrenChanged" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relexingNeeded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//TextBlock"
        eOpposite="#//TextBlock/subNodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingModelElements"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedElements" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceElement" eType="ecore:EClass TCS.ecore#//SequenceElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherVersions" upperBound="2"
        eType="#//DocumentNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offsetRelative" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startRow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endRow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absoluteOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Version">
    <eLiterals name="REFERENCE"/>
    <eLiterals name="PREVIOUS" value="1"/>
    <eLiterals name="CURRENT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForEachContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreachPedicatePropertyInit"
        eType="ecore:EClass TCS.ecore#//ForeachPredicatePropertyInit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextElement" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultModelElement" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceModelElement" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eostoken" eSuperTypes="#//AbstractToken"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bostoken" eSuperTypes="#//AbstractToken"/>
</ecore:EPackage>
