<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oclEvaluator"
    nsURI="http://de.hpi.sam.bp2009.solution.oclEvaluator" nsPrefix="solution.oclEvaluator">
  <eClassifiers xsi:type="ecore:EClass" name="OCLEvaluator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
    <eOperations name="evaluate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="queryobject" eType="#//OclQuery"/>
    </eOperations>
    <eOperations name="evaluate">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
      <eParameters name="queries">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//OclQuery"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="passToInterpreter" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject">
      <eParameters name="interpreter" eType="#//Interpreter"/>
      <eParameters name="queryobject" eType="#//OclQuery"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclQuery">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extentMap" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
        <eTypeArguments eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
          <eTypeArguments>
            <eUpperBound eClassifier="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
          </eTypeArguments>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="#//expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Interpreter">
    <eLiterals name="Ocl"/>
    <eLiterals name="Mql" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="expression" instanceClassName="org.eclipse.ocl.expressions.OCLExpression"/>
</ecore:EPackage>
