/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.tc.moin.testcases.case002;

/**
 * This interface is not intended to be implemented by clients.
 */
public interface E2 extends com.sap.tc.moin.testcases.case002.A2 {

    /**
     * Descriptors for all features of this MofClass and its supertypes.
     */
    public static final Descriptors DESCRIPTORS = new Descriptors( );

    // class extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, com.sap.tc.moin.testcases.case002.E2> CLASS_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, com.sap.tc.moin.testcases.case002.E2>("45F120A55067F11A44D046600BD0B767D823BE62", "test.sap.com/tc/moin/metamodel/testcases", "testcases", "case002", "E2"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 

    
    // references
    public com.sap.tc.moin.testcases.case002.B2 getB() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setB(com.sap.tc.moin.testcases.case002.B2 newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;


    public static final class Descriptors {
        Descriptors( ) { 
        }
        private com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case002.E2,com.sap.tc.moin.testcases.case002.B2> __b;
        /**
         * Returns the descriptor for the <code>b</code> reference.
         * @return  the descriptor for the <code>b</code> reference
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case002.E2,com.sap.tc.moin.testcases.case002.B2> B( ) {
            if ( __b == null ) {
                __b = new com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case002.E2,com.sap.tc.moin.testcases.case002.B2>( "45F120A51DFB40EAA0514E7F0E47CC74465760B1", "test.sap.com/tc/moin/metamodel/testcases", new java.lang.String[] { "testcases", "case002", "E2", "b" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ 
            }
            return __b;
        }
    }
}    