/**
 * Generated by the MOIN Generator Version 3.0
 **/

package euml.generic.relationships.__impl;

public final class UmldirectedRelationShipUmlelementImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public UmldirectedRelationShipUmlelementImpl() {
        super();
    }

    // specific constructor
    public UmldirectedRelationShipUmlelementImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheRelationshipOfTarget, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheTargetElement) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _TheRelationshipOfTarget, _TheTargetElement);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheRelationshipOfTarget, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheTargetElement) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMultN( connection, _TheRelationshipOfTarget, _TheTargetElement, "4986469C71059E02F0C511DD9562000E35A783E4"); //$NON-NLS-1$
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getTheRelationshipOfTarget(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheTargetElement) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getTheRelationshipOfTarget(get___CurrentConnection(), _TheTargetElement);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getTheRelationshipOfTarget(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheTargetElement) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___queryElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _TheTargetElement, get___EndAndMetaObject( 1 ) );
    }
    public java.util.List<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getTheTargetElement(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheRelationshipOfTarget) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getTheTargetElement(get___CurrentConnection(), _TheRelationshipOfTarget);
    }
    public java.util.List<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getTheTargetElement(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheRelationshipOfTarget) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.List<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___getElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _TheRelationshipOfTarget, get___EndAndMetaObject( 0 ) );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheRelationshipOfTarget, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheTargetElement) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheRelationshipOfTarget, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheTargetElement);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheRelationshipOfTarget, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheTargetElement) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheRelationshipOfTarget, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheTargetElement);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheRelationshipOfTarget, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheTargetElement) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheRelationshipOfTarget, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheTargetElement);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheRelationshipOfTarget, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheTargetElement) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheRelationshipOfTarget, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheTargetElement);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    @SuppressWarnings("unchecked")
    public java.lang.Class<euml.generic.relationships.UmldirectedRelationShipUmlelement> get___JmiInterface() {
        return euml.generic.relationships.UmldirectedRelationShipUmlelement.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<euml.generic.relationships.UmldirectedRelationShipUmlelement> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new euml.generic.relationships.__impl.UmldirectedRelationShipUmlelementWrapper(conn, this, synchronize);
    }
}