/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.model.__impl;

public class ASettingDefinitionModelRelationRoleSettingWrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationWrapperImpl<com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationRoleSetting> implements com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationRoleSetting,com.sap.tc.moin.repository.Partitionable
{

    /**
     * The ASettingDefinitionModelRelationRoleSetting wrapper
     */
    public ASettingDefinitionModelRelationRoleSettingWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, com.sap.ide.metamodel.webdynpro.model.__impl.ASettingDefinitionModelRelationRoleSettingImpl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }
    
    private com.sap.ide.metamodel.webdynpro.model.__impl.ASettingDefinitionModelRelationRoleSettingImpl getCastWrappedObject() {
        return (com.sap.ide.metamodel.webdynpro.model.__impl.ASettingDefinitionModelRelationRoleSettingImpl) getWrappedObject();
    }

    public com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationRoleSetting unwrap() {
        return (com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationRoleSetting) getWrappedObject();
    }
    
    public boolean exists(com.sap.ide.metamodel.webdynpro.framework.ModelRelationRoleSettingDefinition _SettingDefinition, com.sap.ide.metamodel.webdynpro.model.ModelRelationRoleSetting _ModelRelationRoleSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SettingDefinition), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _ModelRelationRoleSetting));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SettingDefinition), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _ModelRelationRoleSetting)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public com.sap.ide.metamodel.webdynpro.framework.ModelRelationRoleSettingDefinition getSettingDefinition(com.sap.ide.metamodel.webdynpro.model.ModelRelationRoleSetting _ModelRelationRoleSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (com.sap.ide.metamodel.webdynpro.framework.ModelRelationRoleSettingDefinition) wrapResult(getCastWrappedObject().getSettingDefinition(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _ModelRelationRoleSetting)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (com.sap.ide.metamodel.webdynpro.framework.ModelRelationRoleSettingDefinition) wrapResult(getCastWrappedObject().getSettingDefinition(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _ModelRelationRoleSetting))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public java.util.Collection getModelRelationRoleSetting(com.sap.ide.metamodel.webdynpro.framework.ModelRelationRoleSettingDefinition _SettingDefinition) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (java.util.Collection) wrapResult(getCastWrappedObject().getModelRelationRoleSetting(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SettingDefinition)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (java.util.Collection) wrapResult(getCastWrappedObject().getModelRelationRoleSetting(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SettingDefinition))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean add(com.sap.ide.metamodel.webdynpro.framework.ModelRelationRoleSettingDefinition _SettingDefinition, com.sap.ide.metamodel.webdynpro.model.ModelRelationRoleSetting _ModelRelationRoleSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SettingDefinition), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _ModelRelationRoleSetting));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SettingDefinition), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _ModelRelationRoleSetting)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean remove(com.sap.ide.metamodel.webdynpro.framework.ModelRelationRoleSettingDefinition _SettingDefinition, com.sap.ide.metamodel.webdynpro.model.ModelRelationRoleSetting _ModelRelationRoleSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SettingDefinition), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _ModelRelationRoleSetting));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SettingDefinition), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _ModelRelationRoleSetting)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }   

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationRoleSetting> get___JmiInterface() {
        return com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationRoleSetting.class;
    }

    protected String metaObjectToString() {
        return "com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationRoleSetting (Java Type)\nWebDynpro.model.A_SettingDefinition_modelRelationRoleSetting (MOF Type)"; //$NON-NLS-1$
    }    
}