/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.model.__impl;

public final class ASettingDefinitionModelRelationSettingImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public ASettingDefinitionModelRelationSettingImpl() {
        super();
    }

    // specific constructor
    public ASettingDefinitionModelRelationSettingImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SettingDefinition, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ModelRelationSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _SettingDefinition, _ModelRelationSetting);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SettingDefinition, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ModelRelationSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMult1( connection, _ModelRelationSetting, _SettingDefinition, "45DDACEF86573E41B2BA42A41AE380BBE504A433"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getSettingDefinition(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ModelRelationSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getSettingDefinition(get___CurrentConnection(), _ModelRelationSetting);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getSettingDefinition(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ModelRelationSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _ModelRelationSetting, "45DDACEF86573E41B2BA42A41AE380BBE504A433"); //$NON-NLS-1$
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getModelRelationSetting(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SettingDefinition) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getModelRelationSetting(get___CurrentConnection(), _SettingDefinition);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getModelRelationSetting(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SettingDefinition) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___queryElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _SettingDefinition, get___EndAndMetaObject( 0 ) );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SettingDefinition, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ModelRelationSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_SettingDefinition, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ModelRelationSetting);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SettingDefinition, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ModelRelationSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_SettingDefinition, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ModelRelationSetting);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SettingDefinition, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ModelRelationSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_SettingDefinition, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ModelRelationSetting);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SettingDefinition, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ModelRelationSetting) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_SettingDefinition, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ModelRelationSetting);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationSetting> get___JmiInterface() {
        return com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationSetting.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<com.sap.ide.metamodel.webdynpro.model.ASettingDefinitionModelRelationSetting> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new com.sap.ide.metamodel.webdynpro.model.__impl.ASettingDefinitionModelRelationSettingWrapper(conn, this, synchronize);
    }
}