/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.tc.moin.testcases.case007.top.nestedoftop.__impl;

public final class NestedOfTopPackageImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefPackageImpl
{
        
    public static final java.util.Map<java.lang.String, java.lang.Integer> FEATURE_IDS;
    
    static {
        
        FEATURE_IDS = new java.util.HashMap<java.lang.String, java.lang.Integer>(4);
        FEATURE_IDS.put("NestedOfTopA", Integer.valueOf(0)); //$NON-NLS-1$
        FEATURE_IDS.put("NestedOfTopB", Integer.valueOf(1)); //$NON-NLS-1$
        FEATURE_IDS.put("NestedOfTopAReferencesNestedOfTopB", Integer.valueOf(2)); //$NON-NLS-1$
    }

    // constructors    
    public NestedOfTopPackageImpl()
    {
        super();
    }
    public NestedOfTopPackageImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject)
    {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    // internal enumeration creators
    // internal structure type creators
    // nested packages
    // classes
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getNestedOfTopA(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "NestedOfTopA"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getNestedOfTopB(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "NestedOfTopB"); //$NON-NLS-1$
    }
    // associations
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getNestedOfTopAreferencesNestedOfTopB(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "NestedOfTopAReferencesNestedOfTopB"); //$NON-NLS-1$
    }
    // structure type creators

    protected java.lang.Object create___Extent(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        java.lang.String name = ((com.sap.tc.moin.repository.mmi.model.ModelElement) metaObject).getName();
        com.sap.tc.moin.repository.mmi.reflect.RefBaseObject result = null;
        try {
            switch (FEATURE_IDS.get(name)) {
                case 0:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.tc.moin.testcases.case007.top.nestedoftop.__impl.NestedOfTopAImpl")); //$NON-NLS-1$
                case 1:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.tc.moin.testcases.case007.top.nestedoftop.__impl.NestedOfTopBImpl")); //$NON-NLS-1$
                case 2:
                    return new com.sap.tc.moin.testcases.case007.top.nestedoftop.__impl.NestedOfTopAreferencesNestedOfTopBImpl(workspace, mofId, immediatePackage, metaObject);
                default:
                    throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(name, null, "create___Extent()"); //$NON-NLS-1$
        }
        }
        catch(com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            throw ex;
        }
        catch(java.lang.Exception ex) {
            throw new com.sap.tc.moin.repository.mmi.reflect.JmiException(ex);
        }        
    }

    public java.lang.Class<com.sap.tc.moin.testcases.case007.top.nestedoftop.NestedOfTopPackage> get___JmiInterface() {
        return com.sap.tc.moin.testcases.case007.top.nestedoftop.NestedOfTopPackage.class;
    }
    
    protected void initialize() {
        if (___refPackages == null) {
            ___refPackages = new java.util.ArrayList<RefPackageAndName>(0);
            ___refPackagesByName = new java.util.HashMap<String, RefPackageAndName>();
            java.lang.String name = ""; //$NON-NLS-1$
            RefPackageAndName rpan = null;
        }
  
        if (___refClasses == null) {
            ___refClasses = new java.util.ArrayList<RefClassAndName>(2);
            ___refClassesByName = new java.util.HashMap<String, RefClassAndName>();
            java.lang.String name = ""; //$NON-NLS-1$
            RefClassAndName rcan = null;
            name = "NestedOfTopA"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.tc.moin.testcases.case007.top.nestedoftop.NestedOfTopA"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
            name = "NestedOfTopB"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.tc.moin.testcases.case007.top.nestedoftop.NestedOfTopB"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
        }
  
        if (___refAssociations == null) {
            ___refAssociations = new java.util.ArrayList<RefAssociationAndName>(1);
            ___refAssociationsByName = new java.util.HashMap<String, RefAssociationAndName>();
            java.lang.String name = ""; //$NON-NLS-1$
            RefAssociationAndName raan = null;
            name = "NestedOfTopAReferencesNestedOfTopB"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.tc.moin.testcases.case007.top.nestedoftop.NestedOfTopAreferencesNestedOfTopB"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
        }
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<com.sap.tc.moin.testcases.case007.top.nestedoftop.__impl.NestedOfTopPackageImpl> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new com.sap.tc.moin.testcases.case007.top.nestedoftop.__impl.NestedOfTopPackageWrapper(conn, this, synchronize);
    }

}