<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eventManager"
    nsURI="http://de.hpi.sam.bp2009.solution.eventManager" nsPrefix="solution.eventManager">
  <eClassifiers xsi:type="ecore:EClass" name="EventManager">
    <eOperations name="subscribe">
      <eParameters name="root" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="filter" eType="#//EventFilter"/>
      <eParameters name="caller" eType="#//Adapter"/>
    </eOperations>
    <eOperations name="subscribe">
      <eParameters name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
      <eParameters name="filter" eType="#//EventFilter"/>
      <eParameters name="caller" eType="#//Adapter"/>
    </eOperations>
    <eOperations name="subscribe">
      <eParameters name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"/>
      <eParameters name="filter" eType="#//EventFilter"/>
      <eParameters name="caller" eType="#//Adapter"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Adapter" instanceClassName="org.eclipse.emf.common.notify.Adapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelChangeEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the EObject that cause the event."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementChangeEvent" eSuperTypes="#//ModelChangeEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeValueChangeEvent" eSuperTypes="#//ElementChangeEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementLifeCycleEvent" eSuperTypes="#//ElementChangeEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkLifeCycleEvent" eSuperTypes="#//ModelChangeEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementCreateEvent" eSuperTypes="#//ElementLifeCycleEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementDeleteEvent" eSuperTypes="#//ElementLifeCycleEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkCreateEvent" eSuperTypes="#//LinkLifeCycleEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkDeleteEvent" eSuperTypes="#//LinkLifeCycleEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventFilter" abstract="true" interface="true">
    <eOperations name="matchesFor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="event" eType="#//ModelChangeEvent"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTypeFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" eType="#//EventFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" eType="#//EventFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" eType="#//EventFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" eType="#//EventFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wantedClass" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositionHierarchyFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" eType="#//EventFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wantedPackage" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationFilter" eSuperTypes="#//EventFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventNotification"/>
</ecore:EPackage>
