<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="benchframework"
    nsURI="http://de.hpi.sam.bp2009.benchframework" nsPrefix="benchframework">
  <eClassifiers xsi:type="ecore:EClass" name="Engine">
    <eOperations name="benchmark"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testRuns" upperBound="-1"
        eType="#//TestRun"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true">
    <eOperations name="execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" eType="#//OptionObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//ResultObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testRun" eType="#//TestRun"
        eOpposite="#//TestRun/operators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultProcessor" abstract="true">
    <eOperations name="showResults" eType="#//WizardPage">
      <eParameters name="resultObjects">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="#//ResultObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultPage" eType="#//WizardPage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionObject">
    <eOperations name="getOptionMap">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wizardPage" eType="#//WizardPage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultObject">
    <eOperations name="getPropertyMap">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultDisplay" eType="#//UIComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserInterface" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="engine" eType="#//Engine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableOperators" eType="#//Operator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultProcessor" eType="#//ResultProcessor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestRun">
    <eOperations name="getInstanceForClass">
      <eGenericType eTypeParameter="#//TestRun/getInstanceForClass/returnType"/>
      <eTypeParameters name="returnType"/>
      <eParameters name="aClass">
        <eAnnotations>
          <details key="documentation" value="This is a test"/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//TestRun/getInstanceForClass/returnType"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="setInstanceForClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="aClass">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="anObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operators" upperBound="-1"
        eType="#//Operator" eOpposite="#//Operator/testRun"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OutputStream" instanceClassName="java.io.OutputStream"/>
  <eClassifiers xsi:type="ecore:EDataType" name="WizardPage" instanceClassName="org.eclipse.jface.wizard.WizardPage"/>
  <eClassifiers xsi:type="ecore:EDataType" name="UIComponent" instanceClassName="org.eclipse.swt.widgets.Composite"/>
</ecore:EPackage>
