<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modifiedEventManager"
    nsURI="http://de.hpi.sam.bp2009.benchframework.modifiedEventManager" nsPrefix="benchframework.modifiedEventManager">
  <eClassifiers xsi:type="ecore:EClass" name="ModifiedEventManager" eSuperTypes="../../de.hpi.sam.bp2009.solution.eventManager/model/eventManager.ecore#//EventManager">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
    <eOperations name="sendBenchmarkNotification">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation"/>
      </eAnnotations>
      <eParameters name="communicationPartner" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
      <eParameters name="incoming" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmbedModifiedEMOperator" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//Operator"/>
</ecore:EPackage>
