<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modifiedEventManager"
    nsURI="http://de.hpi.sam.bp2009.benchframework.modifiedEventManager" nsPrefix="benchframework.modifiedEventManager">
  <eClassifiers xsi:type="ecore:EClass" name="ModifiedEventManager" eSuperTypes="../../de.hpi.sam.bp2009.solution.eventManager/model/eventManager.ecore#//EventManager">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmbedModifiedEMOperator" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//Operator"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ModifiedEventManagerNotifyLiterals">
    <eLiterals name="START_SUBSCRIPTION" literal="START_SUBSCRIPTION"/>
    <eLiterals name="END_SUBSCRIPTION" value="1"/>
    <eLiterals name="START_EMF_EVENT_HANDLING" value="2"/>
    <eLiterals name="END_EMF_EVENT_HANDLING" value="3"/>
    <eLiterals name="START_APPLICATION_NOTIFICATION" value="4"/>
    <eLiterals name="END_APPLICATION_NOTIFICATION" value="5"/>
  </eClassifiers>
</ecore:EPackage>
