/**
 * Generated by the MOIN Generator Version 3.0
 **/

package behavioral.statusandaction.design;
/**
 * This interface is not intended to be implemented by clients.
 */
public interface BusinessObjectHasNodes extends com.sap.tc.moin.repository.mmi.reflect.RefAssociation
{
    // association extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<behavioral.statusandaction.design.BusinessObjectHasNodes> ASSOCIATION_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<behavioral.statusandaction.design.BusinessObjectHasNodes>("E0BC871351DF94E63E4B11DECD010018DE1146FF", "sap.com/moin/mm/ap/core", "behavioral", "status_and_action", "design", "BusinessObjectHasNodes"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ 


    // association interface
    public boolean exists(behavioral.statusandaction.design.BusinessObjectNode _Nodes, behavioral.statusandaction.design.BusinessObject _BusinessObject) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.Collection<behavioral.statusandaction.design.BusinessObjectNode> getNodes(behavioral.statusandaction.design.BusinessObject _BusinessObject) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public behavioral.statusandaction.design.BusinessObject getBusinessObject(behavioral.statusandaction.design.BusinessObjectNode _Nodes) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean add(behavioral.statusandaction.design.BusinessObjectNode _Nodes, behavioral.statusandaction.design.BusinessObject _BusinessObject) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean remove(behavioral.statusandaction.design.BusinessObjectNode _Nodes, behavioral.statusandaction.design.BusinessObject _BusinessObject) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
}