<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ast"
    nsURI="urn:ast.ecore" nsPrefix="ast">
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.lang.Boolean"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="java.lang.Double"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.lang.Double"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.lang.Integer"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.util.List"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="Visitable">
    <eOperations name="accept" eType="#//Object">
      <eAnnotations source="body">
        <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
      </eAnnotations>
      <eParameters name="visitor" eType="#//Visitor"/>
      <eParameters name="data" eType="#//Object"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visitor">
    <eOperations name="visit" eType="#//Object">
      <eParameters name="visitable" eType="#//Visitable"/>
      <eParameters name="data" eType="#//Object"/>
    </eOperations>
  </eClassifiers>
  <eSubpackages name="contexts" nsURI="urn:ast.contexts.ecore" nsPrefix="ast.contexts">
    <eClassifiers xsi:type="ecore:EClass" name="ClassifierContextDeclAS" eSuperTypes="#//contexts/ContextDeclarationAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathName" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstraintAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1"
          eType="#//contexts/ConstraintKindAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defOperation" eType="#//contexts/OperationAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bodyExpression" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defVariable" eType="#//contexts/VariableDeclarationAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ConstraintKindAS">
      <eLiterals name="INIT"/>
      <eLiterals name="DERIVE" value="1"/>
      <eLiterals name="INV" value="2"/>
      <eLiterals name="DEF" value="3"/>
      <eLiterals name="PRE" value="4"/>
      <eLiterals name="POST" value="5"/>
      <eLiterals name="BODY" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContextDeclarationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//contexts/ConstraintAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathName" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//contexts/VariableDeclarationAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationContextDeclAS" eSuperTypes="#//contexts/ContextDeclarationAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
          eType="#//contexts/OperationAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PackageDeclarationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathName" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contextDecls" upperBound="-1"
          eType="#//contexts/ContextDeclarationAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyContextDeclAS" eSuperTypes="#//contexts/ContextDeclarationAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathName" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initExp" eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="urn:ast.expressions.ecore" nsPrefix="ast.expressions">
    <eClassifiers xsi:type="ecore:EClass" name="AndExpAS" eSuperTypes="#//expressions/LogicalExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrowSelectionExpAS" eSuperTypes="#//expressions/SelectionExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssociationCallExpAS" eSuperTypes="#//expressions/CallExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteralExpAS" eSuperTypes="#//expressions/PrimitiveLiteralExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="#//Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CallExpAS" abstract="true" eSuperTypes="#//expressions/OclExpressionAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionItemAS" eSuperTypes="#//expressions/CollectionLiteralPartAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CollectionKindAS">
      <eLiterals name="SET"/>
      <eLiterals name="BAG" value="1"/>
      <eLiterals name="SEQUENCE" value="2"/>
      <eLiterals name="COLLECTION" value="3"/>
      <eLiterals name="ORDERED_SET" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteralExpAS" eSuperTypes="#//expressions/LiteralExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1"
          eType="#//expressions/CollectionKindAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionParts" upperBound="-1"
          eType="#//expressions/CollectionLiteralPartAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteralPartAS" abstract="true"
        eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionRangeAS" eSuperTypes="#//expressions/CollectionLiteralPartAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="last" eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DotSelectionExpAS" eSuperTypes="#//expressions/SelectionExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumLiteralExpAS" eSuperTypes="#//expressions/LiteralExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathName" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfExpAS" eSuperTypes="#//expressions/OclExpressionAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" lowerBound="1"
          eType="#//expressions/OclExpressionAS" eOpposite="#//expressions/OclExpressionAS/ifExpAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImpliesExpAS" eSuperTypes="#//expressions/LogicalExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteralExpAS" eSuperTypes="#//expressions/PrimitiveLiteralExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IterateExpAS" eSuperTypes="#//expressions/LoopExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IteratorExpAS" eSuperTypes="#//expressions/LoopExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LetExpAS" eSuperTypes="#//expressions/OclExpressionAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
          upperBound="-1" eType="#//contexts/VariableDeclarationAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralExpAS" abstract="true" eSuperTypes="#//expressions/PrimaryExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogicalExpAS" abstract="true" eSuperTypes="#//expressions/OclExpressionAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoopExpAS" abstract="true" eSuperTypes="#//expressions/OclExpressionAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" upperBound="-1"
          eType="#//contexts/VariableDeclarationAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1"
          eType="#//contexts/VariableDeclarationAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NotExpAS" eSuperTypes="#//expressions/LogicalExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclExpressionAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMarkedPre" lowerBound="1"
          eType="#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifExpAS" lowerBound="1"
          eType="#//expressions/IfExpAS" eOpposite="#//expressions/IfExpAS/elseExpression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclMessageArgAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//types/TypeAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclMessageExpAS" eSuperTypes="#//expressions/OclExpressionAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1"
          eType="#//expressions/OclMessageKindAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//expressions/OclMessageArgAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OclMessageKindAS">
      <eLiterals name="UP"/>
      <eLiterals name="UP_UP" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationCallExpAS" eSuperTypes="#//expressions/CallExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrExpAS" eSuperTypes="#//expressions/LogicalExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PathNameExpAS" eSuperTypes="#//expressions/PrimaryExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathName" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpAS" abstract="true" eSuperTypes="#//expressions/OclExpressionAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveLiteralExpAS" abstract="true"
        eSuperTypes="#//expressions/LiteralExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RealLiteralExpAS" eSuperTypes="#//expressions/PrimitiveLiteralExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="#//Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectionExpAS" abstract="true" eSuperTypes="#//expressions/OclExpressionAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringLiteralExpAS" eSuperTypes="#//expressions/PrimitiveLiteralExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TupleLiteralExpAS" eSuperTypes="#//expressions/LiteralExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tupleParts" upperBound="-1"
          eType="#//contexts/VariableDeclarationAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XorExpAS" eSuperTypes="#//expressions/LogicalExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="qvt" nsURI="urn:ast.qvt.ecore" nsPrefix="ast.qvt">
    <eClassifiers xsi:type="ecore:EClass" name="CollectionTemplateAS" eSuperTypes="#//qvt/TemplateAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionKind" lowerBound="1"
          eType="#//expressions/CollectionKindAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memberSelectionExpressions"
          lowerBound="1" eType="#//qvt/MemberSelectionExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="oclExpressions" upperBound="-1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="setComprehensionExpression"
          lowerBound="1" eType="#//qvt/SetComprehensionExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainAS" eSuperTypes="#//qvt/GeneralDomainAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionKind" lowerBound="1"
          eType="#//qvt/ExecutionKindAS"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementedBy" lowerBound="1"
          eType="#//expressions/DotSelectionExpAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyTemplates" upperBound="-1"
          eType="#//qvt/PropertyTemplateAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ExecutionKindAS">
      <eLiterals name="CHECK_ONLY"/>
      <eLiterals name="ENFORCE" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GeneralDomainAS" abstract="true" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KeyDeclarationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classId" lowerBound="1"
          eType="#//List"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyIds" lowerBound="1"
          eType="#//List"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MemberSelectionExpressionAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectTemplate" lowerBound="1"
          eType="#//qvt/ObjectTemplateAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelDeclarationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaModelIds" lowerBound="1"
          eType="#//List"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectTemplateAS" eSuperTypes="#//qvt/TemplateAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyTemplates" upperBound="-1"
          eType="#//qvt/PropertyTemplateAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterDeclarationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveDomainAS" eSuperTypes="#//qvt/GeneralDomainAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyTemplateAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QueryAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathName" lowerBound="1"
          eType="#//List"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//qvt/ParameterDeclarationAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTopLevel" lowerBound="1"
          eType="#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="overrides" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="where" upperBound="-1"
          eType="#//expressions/OclExpressionAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarations"
          upperBound="-1" eType="#//qvt/VariableDeclarationAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
          eType="#//qvt/GeneralDomainAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="when" upperBound="-1"
          eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetComprehensionExpressionAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectTemplate" lowerBound="1"
          eType="#//qvt/ObjectTemplateAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="oclExpression" lowerBound="1"
          eType="#//expressions/OclExpressionAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateAS" eSuperTypes="#//expressions/OclExpressionAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TopLevelAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imports" lowerBound="1"
          eType="#//List"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
          eType="#//qvt/TransformationAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransformationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extends" lowerBound="1"
          eType="#//List"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="keyDeclarations" upperBound="-1"
          eType="#//qvt/KeyDeclarationAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
          eType="#//qvt/RelationAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelDeclarations" upperBound="-1"
          eType="#//qvt/ModelDeclarationAS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="query" upperBound="-1"
          eType="#//qvt/QueryAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationAS" eSuperTypes="#//Visitable">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="names" lowerBound="1"
          eType="#//List"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeAS"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="types" nsURI="urn:ast.types.ecore" nsPrefix="ast.types">
    <eClassifiers xsi:type="ecore:EClass" name="BagTypeAS" eSuperTypes="#//types/CollectionTypeAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassifierAS" eSuperTypes="#//types/TypeAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathName" lowerBound="1"
          eType="#//List"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionTypeAS" eSuperTypes="#//types/TypeAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1"
          eType="#//types/TypeAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedSetTypeAS" eSuperTypes="#//types/CollectionTypeAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceTypeAS" eSuperTypes="#//types/CollectionTypeAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetTypeAS" eSuperTypes="#//types/CollectionTypeAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TupleTypeAS" eSuperTypes="#//types/TypeAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarationList"
          upperBound="-1" eType="#//contexts/VariableDeclarationAS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeAS" abstract="true" eSuperTypes="#//expressions/LiteralExpAS">
      <eOperations name="accept" eType="#//Object">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return ((org.oslo.ocl20.semantics.analyser.OclSemanticAnalyserVisitorImpl)visitor).visit(this,data);"/>
        </eAnnotations>
        <eParameters name="visitor" eType="#//Visitor"/>
        <eParameters name="data" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
