<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datatypes"
    nsURI="http://sap.com/moin/datatypes" nsPrefix="datatypes">
  <eAnnotations source="http://sap.com/MOIN">
    <details key="datatypes.Point" value="//Point"/>
    <details key="datatypes.ViewPort" value="//ViewPort"/>
    <details key="datatypes.Color" value="//Color"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="datatypes.Point"/>
      <details key="metaObjectMofId" value="473ABD0053BA21A2929211DCC37B8000600FE800"/>
      <details key="isStructureType" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="before" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="after" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewPort">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="datatypes.ViewPort"/>
      <details key="metaObjectMofId" value="45E806E310B0E51AC44B4194019BE01307D16147"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="datatypes.Color"/>
      <details key="metaObjectMofId" value="45E806E31BEE0BFC06414C9B3C40BD0ABFB5FC54"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="red" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="green" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
