<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Imports"
    nsURI="http://imports" nsPrefix="im">
  <eClassifiers xsi:type="ecore:EClass" name="Referer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="self" eType="#//Referer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="minute" eType="ecore:EClass LittleModel.ecore#//Minute"/>
  </eClassifiers>
</ecore:EPackage>
