<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test"
    nsURI="http://test" nsPrefix="tst">
  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Test"
        eOpposite="#//Test/child"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Test"
        eOpposite="#//Test/parent"/>
  </eClassifiers>
</ecore:EPackage>
