/**
 * Generated by the MOIN Generator Version 3.0
 **/

package configuration.contextdrivers.__impl;

public class IncludedContextValuesWrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationWrapperImpl<configuration.contextdrivers.IncludedContextValues> implements configuration.contextdrivers.IncludedContextValues,com.sap.tc.moin.repository.Partitionable
{

    /**
     * The IncludedContextValues wrapper
     */
    public IncludedContextValuesWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, configuration.contextdrivers.__impl.IncludedContextValuesImpl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }
    
    private configuration.contextdrivers.__impl.IncludedContextValuesImpl getCastWrappedObject() {
        return (configuration.contextdrivers.__impl.IncludedContextValuesImpl) getWrappedObject();
    }

    public configuration.contextdrivers.IncludedContextValues unwrap() {
        return (configuration.contextdrivers.IncludedContextValues) getWrappedObject();
    }
    
    public boolean exists(configuration.contextdrivers.ContexConfiguration _IncludedValuesConfiguration, configuration.contextdrivers.ContextCategoryValue _IncludedValues) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValuesConfiguration), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValues));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValuesConfiguration), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValues)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public java.util.Collection getIncludedValuesConfiguration(configuration.contextdrivers.ContextCategoryValue _IncludedValues) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (java.util.Collection) wrapResult(getCastWrappedObject().getIncludedValuesConfiguration(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValues)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (java.util.Collection) wrapResult(getCastWrappedObject().getIncludedValuesConfiguration(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValues))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public java.util.Collection getIncludedValues(configuration.contextdrivers.ContexConfiguration _IncludedValuesConfiguration) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (java.util.Collection) wrapResult(getCastWrappedObject().getIncludedValues(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValuesConfiguration)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (java.util.Collection) wrapResult(getCastWrappedObject().getIncludedValues(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValuesConfiguration))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean add(configuration.contextdrivers.ContexConfiguration _IncludedValuesConfiguration, configuration.contextdrivers.ContextCategoryValue _IncludedValues) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValuesConfiguration), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValues));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValuesConfiguration), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValues)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean remove(configuration.contextdrivers.ContexConfiguration _IncludedValuesConfiguration, configuration.contextdrivers.ContextCategoryValue _IncludedValues) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValuesConfiguration), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValues));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValuesConfiguration), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _IncludedValues)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }   

    public java.lang.Class<configuration.contextdrivers.IncludedContextValues> get___JmiInterface() {
        return configuration.contextdrivers.IncludedContextValues.class;
    }

    protected String metaObjectToString() {
        return "configuration.contextdrivers.IncludedContextValues (Java Type)\nconfiguration.context_drivers.IncludedContextValues (MOF Type)"; //$NON-NLS-1$
    }    
}