<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="textverticalization"
    nsURI="http://sap.com/moin/textverticalization" nsPrefix="tv">
  <eAnnotations source="http://sap.com/MOIN">
    <details key="textverticalization.TranslatableTextFragment" value="//TranslatableTextFragment"/>
    <details key="textverticalization.TranslatableText" value="//TranslatableText"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TranslatableText">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/textverticalization[2.0.0]"/>
      <details key="metaObject" value="textverticalization.TranslatableTextFragment"/>
      <details key="metaObjectMofId" value="48D4188D58380873869111DD8E220019993BAD15"/>
      <details key="isStructureType" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxWidth" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="255"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalText" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="translate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transUnitId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
