<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="baseCST"
    nsURI="http://www.eclipse.org/ocl/3.0.0/BaseCST" nsPrefix="baseCST">
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationElementCS" abstract="true"
      eSuperTypes="#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//DetailCS" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeCS" abstract="true" interface="true"
      eSuperTypes="#//StructuralFeatureCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeCSRef" eSuperTypes="#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//AttributeCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundClassCS" eSuperTypes="#//ClassCS #//BoundClassifierCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="BoundClassifierCS">
    <eGenericSuperTypes eClassifier="#//ClassifierCS"/>
    <eGenericSuperTypes eClassifier="#//BoundElementCS">
      <eTypeArguments eClassifier="#//ClassifierCS"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundDocumentCS" eSuperTypes="#//PackageCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="BoundElementCS" abstract="true" interface="true"
      eSuperTypes="#//NamedElementCS">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//NamedElementCS"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" eType="#//TypeBindingsCS"
        transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binds" derived="true">
      <eGenericType eTypeParameter="#//BoundElementCS/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundOperationCS">
    <eGenericSuperTypes eClassifier="#//OperationCS"/>
    <eGenericSuperTypes eClassifier="#//BoundElementCS">
      <eTypeArguments eClassifier="#//OperationCS"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassCS" abstract="true" interface="true"
      eSuperTypes="#//ClassifierCS #//NamespaceCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
        eType="#//TypedRefCS" unsettable="true" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
        <details key="suppressedUnsetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//OperationCS" containment="true" resolveProxies="false" eOpposite="#//OperationCS/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralFeatures" upperBound="-1"
        eType="#//StructuralFeatureCS" containment="true" resolveProxies="false" eOpposite="#//StructuralFeatureCS/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassCSRef" eSuperTypes="#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//ClassCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierCS" abstract="true" eSuperTypes="#//NamedElementCS #//TypeCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
        eType="#//TypeParameterCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//PackageCS"
        eOpposite="#//PackageCS/classifiers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierRefCS" abstract="true" eSuperTypes="#//ModelElementCS">
    <eOperations name="getClassifier" eType="#//ClassifierCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionTypeRefCS" eSuperTypes="#//TypedRefCS #//NamedElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" eType="#//TypeRefCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DetailCS" eSuperTypes="#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentCS" abstract="true" eSuperTypes="#//NamespaceCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//ImportCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
        eType="#//LibraryCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementCS" abstract="true">
    <eOperations name="getSignature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getSignature">
      <eParameters name="s" eType="#//Signature"/>
      <eParameters name="bindings" eType="#//TypeBindingsCS"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteralCS" eSuperTypes="#//NamedElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureCS" abstract="true" interface="true"
      eSuperTypes="#//TypedElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefinition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportCS" eSuperTypes="#//NamespaceCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//NamespaceCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LibraryCS" eSuperTypes="#//NamespaceCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//PackageCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementCS" abstract="true" eSuperTypes="#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//AnnotationElementCS" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalXmiId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementCSRef" eSuperTypes="#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//ModelElementCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElementCS" abstract="true" eSuperTypes="#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceCS" abstract="true" interface="true"
      eSuperTypes="#//NamedElementCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationCS" abstract="true" eSuperTypes="#//FeatureCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ParameterCS" containment="true" resolveProxies="false" eOpposite="#//ParameterCS/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
        eType="#//TypeParameterCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//ClassCS"
        eOpposite="#//ClassCS/operations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationRefCS" abstract="true" eSuperTypes="#//ModelElementCS">
    <eOperations name="getOperation" eType="#//OperationCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageCS" eSuperTypes="#//NamespaceCS">
    <eOperations name="getClassifier" eType="#//ClassifierCS">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1"
        eType="#//ClassifierCS" containment="true" eOpposite="#//ClassifierCS/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subpackages" upperBound="-1"
        eType="#//PackageCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageRefCS" abstract="true" eSuperTypes="#//ModelElementCS">
    <eOperations name="getPackage" eType="#//PackageCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterCS" eSuperTypes="#//TypedElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//OperationCS"
        eOpposite="#//OperationCS/parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterizedTypeRefCS" abstract="true"
      eSuperTypes="#//TypedRefCS">
    <eOperations name="getType" eType="#//TypeCS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
        eType="#//TypeRefCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeRefCS" eSuperTypes="#//TypedRefCS #//NamedElementCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedClassifierRefCS">
    <eGenericSuperTypes eClassifier="#//ClassifierRefCS"/>
    <eGenericSuperTypes eClassifier="#//QualifiedRefCS">
      <eTypeArguments eClassifier="#//ClassifierRefCS"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedOperationRefCS">
    <eGenericSuperTypes eClassifier="#//OperationRefCS"/>
    <eGenericSuperTypes eClassifier="#//QualifiedRefCS">
      <eTypeArguments eClassifier="#//OperationRefCS"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedPackageRefCS">
    <eGenericSuperTypes eClassifier="#//PackageRefCS"/>
    <eGenericSuperTypes eClassifier="#//QualifiedRefCS">
      <eTypeArguments eClassifier="#//PackageRefCS"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedRefCS" abstract="true" interface="true"
      eSuperTypes="#//ModelElementCS">
    <eTypeParameters name="E">
      <eBounds eClassifier="#//ElementCS"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//NamespaceCS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" containment="true">
      <eGenericType eTypeParameter="#//QualifiedRefCS/E"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedStructuralFeatureRefCS">
    <eGenericSuperTypes eClassifier="#//StructuralFeatureRefCS"/>
    <eGenericSuperTypes eClassifier="#//QualifiedRefCS">
      <eTypeArguments eClassifier="#//StructuralFeatureRefCS"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedTypeRefCS">
    <eGenericSuperTypes eClassifier="#//ParameterizedTypeRefCS"/>
    <eGenericSuperTypes eClassifier="#//QualifiedRefCS">
      <eTypeArguments eClassifier="#//ParameterizedTypeRefCS"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceCS" abstract="true" interface="true"
      eSuperTypes="#//StructuralFeatureCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//ReferenceCSRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceCSRef" eSuperTypes="#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//ReferenceCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleClassifierRefCS" eSuperTypes="#//ClassifierRefCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" eType="#//ClassifierCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleOperationRefCS" eSuperTypes="#//OperationRefCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//OperationCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimplePackageRefCS" eSuperTypes="#//PackageRefCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//PackageCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleStructuralFeatureRefCS" eSuperTypes="#//StructuralFeatureRefCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//StructuralFeatureCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeatureCS" abstract="true"
      eSuperTypes="#//FeatureCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//ClassCS"
        eOpposite="#//ClassCS/structuralFeatures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeatureRefCS" abstract="true"
      eSuperTypes="#//ModelElementCS">
    <eOperations name="getFeature" eType="#//StructuralFeatureCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeBindingCS" eSuperTypes="#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameter" eType="#//TypeParameterCS"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgument" eType="#//ClassifierCS"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeBindingsCS" eSuperTypes="#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundDocument" eType="#//BoundDocumentCS"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//TypeBindingCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nested" upperBound="-1"
        eType="#//TypeBindingsCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeCS" abstract="true" interface="true"
      eSuperTypes="#//ElementCS">
    <eOperations name="getSignature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeParameterCS" eSuperTypes="#//NamedElementCS #//TypeCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//TypedRefCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" eType="#//TypedRefCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRefCS" abstract="true" eSuperTypes="#//ModelElementCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElementCS" abstract="true" interface="true"
      eSuperTypes="#//NamedElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiers" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypedRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedRefCS" abstract="true" eSuperTypes="#//TypeRefCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedTypeRefCS" eSuperTypes="#//ParameterizedTypeRefCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WildcardTypeRefCS" eSuperTypes="#//TypeRefCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//TypedRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" eType="#//TypedRefCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Signature" instanceClassName="org.eclipse.ocl.examples.xtext.base.util.Signature"/>
</ecore:EPackage>
