/**
 * Generated by the MOIN Generator Version 3.0
 **/

package behavioral.statusandaction.assembly.__impl;

public final class ConnectorHasTargetImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public ConnectorHasTargetImpl() {
        super();
    }

    // specific constructor
    public ConnectorHasTargetImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Target, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Incoming) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _Target, _Incoming);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Target, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Incoming) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMult1( connection, _Incoming, _Target, "E0BC871351E205EE3E4B11DEC4060018DE1146FF"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getTarget(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Incoming) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getTarget(get___CurrentConnection(), _Incoming);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getTarget(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Incoming) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _Incoming, "E0BC871351E205EE3E4B11DEC4060018DE1146FF"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getIncoming(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Target) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getIncoming(get___CurrentConnection(), _Target);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getIncoming(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Target) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        com.sap.tc.moin.repository.core.EndAndMetaObject endAndMetaObject = get___EndAndMetaObject( 0 );
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___queryElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _Target, endAndMetaObject );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Target, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Incoming) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Target, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Incoming);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Target, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Incoming) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Target, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Incoming);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Target, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Incoming) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Target, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Incoming);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Target, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Incoming) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Target, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Incoming);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    public java.lang.Class<behavioral.statusandaction.assembly.ConnectorHasTarget> get___JmiInterface() {
        return behavioral.statusandaction.assembly.ConnectorHasTarget.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<behavioral.statusandaction.assembly.ConnectorHasTarget> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new behavioral.statusandaction.assembly.__impl.ConnectorHasTargetWrapper(conn, this, synchronize);
    }
}