/**
 * Generated by the MOIN Generator Version 3.0
 **/

package behavioral.statusandaction.assembly.__impl;

public final class ProxyRepresentsActionImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public ProxyRepresentsActionImpl() {
        super();
    }

    // specific constructor
    public ProxyRepresentsActionImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Action, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Proxy) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _Action, _Proxy);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Action, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Proxy) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMult1( connection, _Proxy, _Action, "E0BC871351E205DE3E4B11DEB64D0018DE1146FF"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getAction(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Proxy) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getAction(get___CurrentConnection(), _Proxy);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getAction(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Proxy) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _Proxy, "E0BC871351E205DE3E4B11DEB64D0018DE1146FF"); //$NON-NLS-1$
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getProxy(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Action) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getProxy(get___CurrentConnection(), _Action);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getProxy(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Action) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___queryElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _Action, get___EndAndMetaObject( 0 ) );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Action, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Proxy) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Action, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Proxy);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Action, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Proxy) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Action, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Proxy);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Action, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Proxy) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Action, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Proxy);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Action, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Proxy) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Action, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Proxy);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    public java.lang.Class<behavioral.statusandaction.assembly.ProxyRepresentsAction> get___JmiInterface() {
        return behavioral.statusandaction.assembly.ProxyRepresentsAction.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<behavioral.statusandaction.assembly.ProxyRepresentsAction> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new behavioral.statusandaction.assembly.__impl.ProxyRepresentsActionWrapper(conn, this, synchronize);
    }
}