/**
 * Generated by the MOIN Generator Version 3.0
 **/

package behavioral.statusandaction.assembly.__impl;

public final class RequiredStrategyImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefObjectImpl {

    
    static {
    }
    
    // default constructor
    public RequiredStrategyImpl() {
        super();
    }
    
    // specific constructor
    public RequiredStrategyImpl(java.lang.Object workspace, String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject, com.sap.tc.moin.repository.mmi.reflect.RefClass refClass) {
        super(workspace, mofId, immediatePackage, metaObject, refClass);
    }
    
    // methods for internal attribute setter

    // reflective methods
        
    


    // get the JMI interface
    public java.lang.Class<behavioral.statusandaction.assembly.RequiredStrategy> get___JmiInterface() {
        return behavioral.statusandaction.assembly.RequiredStrategy.class;
    }

    // create the wrapper
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<behavioral.statusandaction.assembly.__impl.RequiredStrategyImpl> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new behavioral.statusandaction.assembly.__impl.RequiredStrategyWrapper(conn, this, synchronize);
    }
    
}