/**
 * Generated by the MOIN Generator Version 3.0
 **/

package data.classes.__impl;

public final class AImplementationFunctionSignatureImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public AImplementationFunctionSignatureImpl() {
        super();
    }

    // specific constructor
    public AImplementationFunctionSignatureImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Implementation, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _FunctionSignature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _Implementation, _FunctionSignature);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Implementation, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _FunctionSignature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMult1( connection, _FunctionSignature, _Implementation, "E0234C8C51EB7BF53E4B11DEAB4E0018DE1146FF"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getImplementation(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _FunctionSignature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getImplementation(get___CurrentConnection(), _FunctionSignature);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getImplementation(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _FunctionSignature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _FunctionSignature, "E0234C8C51EB7BF53E4B11DEAB4E0018DE1146FF"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getFunctionSignature(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Implementation) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getFunctionSignature(get___CurrentConnection(), _Implementation);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getFunctionSignature(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Implementation) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        com.sap.tc.moin.repository.core.EndAndMetaObject endAndMetaObject = get___EndAndMetaObject( 0 );
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) get___CompositeParentForEndAndMetaObject( connection, _Implementation, endAndMetaObject );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Implementation, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _FunctionSignature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Implementation, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_FunctionSignature);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Implementation, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _FunctionSignature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Implementation, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_FunctionSignature);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Implementation, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _FunctionSignature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Implementation, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_FunctionSignature);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Implementation, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _FunctionSignature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Implementation, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_FunctionSignature);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    public java.lang.Class<data.classes.AImplementationFunctionSignature> get___JmiInterface() {
        return data.classes.AImplementationFunctionSignature.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<data.classes.AImplementationFunctionSignature> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new data.classes.__impl.AImplementationFunctionSignatureWrapper(conn, this, synchronize);
    }
}