/**
 * Generated by the MOIN Generator Version 3.0
 **/

package behavioral.statusandactionold.__impl;

public final class SamneutralPreconditionFromOperatorToOperatorImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public SamneutralPreconditionFromOperatorToOperatorImpl() {
        super();
    }

    // specific constructor
    public SamneutralPreconditionFromOperatorToOperatorImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamSourceOperators, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamTargetOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _SamSourceOperators, _SamTargetOperators);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamSourceOperators, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamTargetOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMultN( connection, _SamTargetOperators, _SamSourceOperators, "E0BC871351DD4B053E4B11DE96AC0018DE1146FF"); //$NON-NLS-1$
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getSamSourceOperators(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamTargetOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getSamSourceOperators(get___CurrentConnection(), _SamTargetOperators);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getSamSourceOperators(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamTargetOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___getElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _SamTargetOperators, get___EndAndMetaObject( 1 ) );
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getSamTargetOperators(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamSourceOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getSamTargetOperators(get___CurrentConnection(), _SamSourceOperators);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getSamTargetOperators(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamSourceOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___queryElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _SamSourceOperators, get___EndAndMetaObject( 0 ) );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamSourceOperators, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamTargetOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_SamSourceOperators, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_SamTargetOperators);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamSourceOperators, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamTargetOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_SamSourceOperators, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_SamTargetOperators);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamSourceOperators, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamTargetOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_SamSourceOperators, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_SamTargetOperators);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamSourceOperators, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _SamTargetOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_SamSourceOperators, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_SamTargetOperators);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    @SuppressWarnings("unchecked")
    public java.lang.Class<behavioral.statusandactionold.SamneutralPreconditionFromOperatorToOperator> get___JmiInterface() {
        return behavioral.statusandactionold.SamneutralPreconditionFromOperatorToOperator.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<behavioral.statusandactionold.SamneutralPreconditionFromOperatorToOperator> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new behavioral.statusandactionold.__impl.SamneutralPreconditionFromOperatorToOperatorWrapper(conn, this, synchronize);
    }
}