/**
 * Generated by the MOIN Generator Version 3.0
 **/

package behavioral.statusandactionold.__impl;

public class SampreconditionFromOperatorToActionWrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationWrapperImpl<behavioral.statusandactionold.SampreconditionFromOperatorToAction> implements behavioral.statusandactionold.SampreconditionFromOperatorToAction,com.sap.tc.moin.repository.Partitionable
{

    /**
     * The SampreconditionFromOperatorToAction wrapper
     */
    public SampreconditionFromOperatorToActionWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, behavioral.statusandactionold.__impl.SampreconditionFromOperatorToActionImpl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }
    
    private behavioral.statusandactionold.__impl.SampreconditionFromOperatorToActionImpl getCastWrappedObject() {
        return (behavioral.statusandactionold.__impl.SampreconditionFromOperatorToActionImpl) getWrappedObject();
    }

    public behavioral.statusandactionold.SampreconditionFromOperatorToAction unwrap() {
        return (behavioral.statusandactionold.SampreconditionFromOperatorToAction) getWrappedObject();
    }
    
    public boolean exists(behavioral.statusandactionold.SamschemaAction _SamSchemaActions, behavioral.statusandactionold.Samoperator _SamSchemaOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaActions), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaOperators));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaActions), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaOperators)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public java.util.Collection getSamSchemaActions(behavioral.statusandactionold.Samoperator _SamSchemaOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (java.util.Collection) wrapResult(getCastWrappedObject().getSamSchemaActions(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaOperators)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (java.util.Collection) wrapResult(getCastWrappedObject().getSamSchemaActions(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaOperators))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public java.util.Collection getSamSchemaOperators(behavioral.statusandactionold.SamschemaAction _SamSchemaActions) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (java.util.Collection) wrapResult(getCastWrappedObject().getSamSchemaOperators(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaActions)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (java.util.Collection) wrapResult(getCastWrappedObject().getSamSchemaOperators(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaActions))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean add(behavioral.statusandactionold.SamschemaAction _SamSchemaActions, behavioral.statusandactionold.Samoperator _SamSchemaOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaActions), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaOperators));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaActions), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaOperators)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean remove(behavioral.statusandactionold.SamschemaAction _SamSchemaActions, behavioral.statusandactionold.Samoperator _SamSchemaOperators) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaActions), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaOperators));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaActions), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _SamSchemaOperators)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }   

    public java.lang.Class<behavioral.statusandactionold.SampreconditionFromOperatorToAction> get___JmiInterface() {
        return behavioral.statusandactionold.SampreconditionFromOperatorToAction.class;
    }

    protected String metaObjectToString() {
        return "behavioral.statusandactionold.SampreconditionFromOperatorToAction (Java Type)\nbehavioral.status_and_action_old.SAMPreconditionFromOperatorToAction (MOF Type)"; //$NON-NLS-1$
    }    
}