<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="semantics"
    nsURI="urn:semanticsQvt.ecore" nsPrefix="semanticsQvt">
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.lang.Boolean"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BridgeFactory" instanceClassName="org.oslo.ocl20.semantics.factories.BridgeFactory"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="org.oslo.ocl20.semantics.factories.BridgeFactory"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Class" instanceClassName="java.lang.Class"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.lang.Class"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.lang.Integer"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.util.List"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Map" instanceClassName="java.util.Map"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.util.Map"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="OclProcessor" instanceClassName="org.oslo.ocl20.OclProcessor"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="org.oslo.ocl20.OclProcessor"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Real" instanceClassName="java.lang.Double"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.lang.Double"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Set" instanceClassName="java.util.Set"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="java.util.Set"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TypeFactory" instanceClassName="org.oslo.ocl20.semantics.factories.TypeFactory"
      serializable="false">
    <eAnnotations source="instance">
      <details key="instance" value="org.oslo.ocl20.semantics.factories.TypeFactory"/>
    </eAnnotations>
  </eClassifiers>
  <eSubpackages name="model" nsURI="urn:semanticsQvt.model.ecore" nsPrefix="semanticsQvt.model">
    <eSubpackages name="qvtbase" nsURI="urn:semanticsQvt.model.qvtbase.ecore" nsPrefix="semanticsQvt.model.qvtbase">
      <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="SemanticsOcl.ecore#//bridge/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCheckable" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnforcable" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="typedModel" eType="#//model/qvtbase/TypedModel"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="SemanticsOcl.ecore#//bridge/DefinedOperation">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="queryExpression" eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/OclExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionParameter" eSuperTypes="SemanticsOcl.ecore#//bridge/Parameter SemanticsOcl.ecore#//model/expressions/VariableDeclaration">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((OclVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Pattern" eSuperTypes="SemanticsOcl.ecore#//bridge/Element">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="whereOwner" lowerBound="1"
            eType="#//model/qvtrelation/Relation" eOpposite="#//model/qvtrelation/Relation/where"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="whenOwner" eType="#//model/qvtrelation/Relation"
            eOpposite="#//model/qvtrelation/Relation/when"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" upperBound="-1"
            eType="#//model/qvtbase/Predicate" containment="true" eOpposite="#//model/qvtbase/Predicate/pattern"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="bindsTo" upperBound="-1"
            eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/VariableDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Predicate" eSuperTypes="SemanticsOcl.ecore#//bridge/Element">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="contitionExpression"
            lowerBound="1" eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/OclExpression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
            eType="#//model/qvtbase/Pattern" eOpposite="#//model/qvtbase/Pattern/predicate"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="SemanticsOcl.ecore#//bridge/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="domain" upperBound="-1"
            eType="#//model/qvtbase/Domain" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="overrides" eType="#//model/qvtbase/Rule"
            eOpposite="#//model/qvtbase/Rule/overriden"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="overriden" upperBound="-1"
            eType="#//model/qvtbase/Rule" eOpposite="#//model/qvtbase/Rule/overrides"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" lowerBound="1"
            eType="#//model/qvtbase/Transformation" eOpposite="#//model/qvtbase/Transformation/rule"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Transformation" eSuperTypes="SemanticsOcl.ecore#//bridge/DefinedClass SemanticsOcl.ecore#//bridge/DefinedPackage">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTag" upperBound="-1"
            eType="ecore:EClass SemanticsOcl.ecore#//bridge/Tag" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="modelParameter" upperBound="-1"
            eType="#//model/qvtbase/TypedModel" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//model/qvtbase/Transformation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1"
            eType="#//model/qvtbase/Rule" containment="true" eOpposite="#//model/qvtbase/Rule/transformation"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TypedModel" eSuperTypes="SemanticsOcl.ecore#//bridge/NamedElement SemanticsOcl.ecore#//SemanticsVisitable">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOn" upperBound="-1"
            eType="#//model/qvtbase/TypedModel"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="usedPackage" lowerBound="1"
            upperBound="-1" eType="ecore:EClass SemanticsOcl.ecore#//bridge/Namespace"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="qvtrelation" nsURI="urn:semanticsQvt.model.qvtrelation.ecore"
        nsPrefix="semanticsQvt.model.qvtrelation">
      <eClassifiers xsi:type="ecore:EClass" name="DomainPattern" eSuperTypes="#//model/qvtbase/Pattern">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="templateExpression"
            eType="#//model/qvttemplate/TemplateExp" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Key" eSuperTypes="SemanticsOcl.ecore#//bridge/Element">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="identifies" lowerBound="1"
            eType="ecore:EClass SemanticsOcl.ecore#//bridge/Classifier"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" eType="#//model/qvtrelation/RelationalTransformation"
            eOpposite="#//model/qvtrelation/RelationalTransformation/ownedKey"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="part" lowerBound="1"
            upperBound="-1" eType="ecore:EClass SemanticsOcl.ecore#//bridge/Property"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//model/qvtbase/Rule">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTopLevel" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//model/qvtbase/Pattern"
            containment="true" eOpposite="#//model/qvtbase/Pattern/whereOwner"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
            eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/VariableDeclaration"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="operationalImpl" upperBound="-1"
            eType="#//model/qvtrelation/RelationImplementation" eOpposite="#//model/qvtrelation/RelationImplementation/relation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//model/qvtbase/Pattern"
            containment="true" eOpposite="#//model/qvtbase/Pattern/whenOwner"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RelationCallExp" eSuperTypes="SemanticsOcl.ecore#//model/expressions/OclExpression">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="referredRelation" eType="#//model/qvtrelation/Relation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
            eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/OclExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RelationDomain" eSuperTypes="#//model/qvtbase/Domain">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rootVariable" lowerBound="1"
            eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/VariableDeclaration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//model/qvtrelation/DomainPattern"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RelationImplementation" eSuperTypes="SemanticsOcl.ecore#//bridge/Element">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="relation" eType="#//model/qvtrelation/Relation"
            eOpposite="#//model/qvtrelation/Relation/operationalImpl"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="impl" lowerBound="1"
            eType="ecore:EClass SemanticsOcl.ecore#//bridge/Operation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="inDirectionOf" lowerBound="1"
            eType="#//model/qvtbase/TypedModel"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RelationalTransformation" eSuperTypes="#//model/qvtbase/Transformation">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="ownedKey" upperBound="-1"
            eType="#//model/qvtrelation/Key" containment="true" eOpposite="#//model/qvtrelation/Key/transformation"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="qvttemplate" nsURI="urn:semanticsQvt.model.qvttemplate.ecore"
        nsPrefix="semanticsQvt.model.qvttemplate">
      <eClassifiers xsi:type="ecore:EClass" name="ColletionTemplateExp" eSuperTypes="#//model/qvttemplate/TemplateExp">
        <eStructuralFeatures xsi:type="ecore:EReference" name="match" eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/OclExpression"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1"
            eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/OclExpression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="refferedCollectionType"
            eType="ecore:EClass SemanticsOcl.ecore#//model/types/CollectionType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ObjectTemplateExp" eSuperTypes="#//model/qvttemplate/TemplateExp">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="refferedClass" lowerBound="1"
            eType="ecore:EClass SemanticsOcl.ecore#//bridge/Classifier"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1"
            eType="#//model/qvttemplate/PropertyTemplateItem" containment="true" eOpposite="#//model/qvttemplate/PropertyTemplateItem/objContainer"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PropertyTemplateItem" eSuperTypes="SemanticsOcl.ecore#//bridge/Element">
        <eOperations name="accept" eType="#//Object">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return ((QvtVisitor)visitor).visit(this,data);"/>
          </eAnnotations>
          <eParameters name="visitor" eType="ecore:EClass SemanticsOcl.ecore#//OclVisitor"/>
          <eParameters name="data" eType="#//Object"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
            eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/OclExpression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="referredProperty" lowerBound="1"
            eType="ecore:EClass SemanticsOcl.ecore#//bridge/Property"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="objContainer" lowerBound="1"
            eType="#//model/qvttemplate/ObjectTemplateExp" eOpposite="#//model/qvttemplate/ObjectTemplateExp/part"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TemplateExp" abstract="true" eSuperTypes="SemanticsOcl.ecore#//model/expressions/LiteralExp">
        <eStructuralFeatures xsi:type="ecore:EReference" name="bindsTo" eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/VariableDeclaration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/OclExpression"
            containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="qvt" nsURI="urn:semanticsQvt.qvt.ecore" nsPrefix="semanticsQvt.qvt">
    <eClassifiers xsi:type="ecore:EClass" name="QvtVisitor" abstract="true" eSuperTypes="SemanticsOcl.ecore#//OclVisitor">
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtrelation/RelationDomain"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtrelation/RelationalTransformation"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtrelation/Relation"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtrelation/RelationCallExp"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvttemplate/ObjectTemplateExp"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvttemplate/PropertyTemplateItem"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="ecore:EClass SemanticsOcl.ecore#//model/expressions/OperationCallExp"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtrelation/DomainPattern"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtrelation/Key"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtbase/Predicate"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtbase/Pattern"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtrelation/RelationImplementation"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="ecore:EClass SemanticsOcl.ecore#//bridge/Tag"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtbase/TypedModel"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
      <eOperations name="visit" eType="#//Object">
        <eParameters name="host" eType="#//model/qvtbase/Function"/>
        <eParameters name="data" ordered="false" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
