/**
 * Generated by the MOIN Generator Version 3.0
 **/

package tcs.__impl;

public class EnumerationTemplateEnumLiteralMappingWrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationWrapperImpl<tcs.EnumerationTemplateEnumLiteralMapping> implements tcs.EnumerationTemplateEnumLiteralMapping,com.sap.tc.moin.repository.Partitionable
{

    /**
     * The EnumerationTemplateEnumLiteralMapping wrapper
     */
    public EnumerationTemplateEnumLiteralMappingWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, tcs.__impl.EnumerationTemplateEnumLiteralMappingImpl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }
    
    private tcs.__impl.EnumerationTemplateEnumLiteralMappingImpl getCastWrappedObject() {
        return (tcs.__impl.EnumerationTemplateEnumLiteralMappingImpl) getWrappedObject();
    }

    public tcs.EnumerationTemplateEnumLiteralMapping unwrap() {
        return (tcs.EnumerationTemplateEnumLiteralMapping) getWrappedObject();
    }
    
    public boolean exists(tcs.EnumerationTemplate _Enumerationtemplate, tcs.EnumLiteralMapping _Enumliteralmapping) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumerationtemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumliteralmapping));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumerationtemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumliteralmapping)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public tcs.EnumerationTemplate getEnumerationtemplate(tcs.EnumLiteralMapping _Enumliteralmapping) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (tcs.EnumerationTemplate) wrapResult(getCastWrappedObject().getEnumerationtemplate(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumliteralmapping)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (tcs.EnumerationTemplate) wrapResult(getCastWrappedObject().getEnumerationtemplate(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumliteralmapping))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public java.util.List getEnumliteralmapping(tcs.EnumerationTemplate _Enumerationtemplate) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (java.util.List) wrapResult(getCastWrappedObject().getEnumliteralmapping(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumerationtemplate)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (java.util.List) wrapResult(getCastWrappedObject().getEnumliteralmapping(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumerationtemplate))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean add(tcs.EnumerationTemplate _Enumerationtemplate, tcs.EnumLiteralMapping _Enumliteralmapping) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumerationtemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumliteralmapping));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumerationtemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumliteralmapping)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean remove(tcs.EnumerationTemplate _Enumerationtemplate, tcs.EnumLiteralMapping _Enumliteralmapping) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumerationtemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumliteralmapping));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumerationtemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Enumliteralmapping)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }   

    @SuppressWarnings("unchecked")
    public java.lang.Class<tcs.EnumerationTemplateEnumLiteralMapping> get___JmiInterface() {
        return tcs.EnumerationTemplateEnumLiteralMapping.class;
    }

    protected String metaObjectToString() {
        return "tcs.EnumerationTemplateEnumLiteralMapping (Java Type)\nTCS.EnumerationTemplate_EnumLiteralMapping (MOF Type)"; //$NON-NLS-1$
    }    
}