/**
 * Generated by the MOIN Generator Version 3.0
 **/

package tcs.__impl;

public class OperatorTemplatePropertyReference1Wrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationWrapperImpl<tcs.OperatorTemplatePropertyReference1> implements tcs.OperatorTemplatePropertyReference1,com.sap.tc.moin.repository.Partitionable
{

    /**
     * The OperatorTemplatePropertyReference1 wrapper
     */
    public OperatorTemplatePropertyReference1Wrapper(com.sap.tc.moin.repository.core.CoreConnection conn, tcs.__impl.OperatorTemplatePropertyReference1Impl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }
    
    private tcs.__impl.OperatorTemplatePropertyReference1Impl getCastWrappedObject() {
        return (tcs.__impl.OperatorTemplatePropertyReference1Impl) getWrappedObject();
    }

    public tcs.OperatorTemplatePropertyReference1 unwrap() {
        return (tcs.OperatorTemplatePropertyReference1) getWrappedObject();
    }
    
    public boolean exists(tcs.OperatorTemplate _Operatortemplate, tcs.PropertyReference _StoreRightSideTo) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Operatortemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _StoreRightSideTo));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Operatortemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _StoreRightSideTo)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public tcs.OperatorTemplate getOperatortemplate(tcs.PropertyReference _StoreRightSideTo) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (tcs.OperatorTemplate) wrapResult(getCastWrappedObject().getOperatortemplate(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _StoreRightSideTo)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (tcs.OperatorTemplate) wrapResult(getCastWrappedObject().getOperatortemplate(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _StoreRightSideTo))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public tcs.PropertyReference getStoreRightSideTo(tcs.OperatorTemplate _Operatortemplate) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (tcs.PropertyReference) wrapResult(getCastWrappedObject().getStoreRightSideTo(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Operatortemplate)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (tcs.PropertyReference) wrapResult(getCastWrappedObject().getStoreRightSideTo(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Operatortemplate))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean add(tcs.OperatorTemplate _Operatortemplate, tcs.PropertyReference _StoreRightSideTo) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Operatortemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _StoreRightSideTo));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Operatortemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _StoreRightSideTo)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean remove(tcs.OperatorTemplate _Operatortemplate, tcs.PropertyReference _StoreRightSideTo) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Operatortemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _StoreRightSideTo));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Operatortemplate), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _StoreRightSideTo)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }   

    @SuppressWarnings("unchecked")
    public java.lang.Class<tcs.OperatorTemplatePropertyReference1> get___JmiInterface() {
        return tcs.OperatorTemplatePropertyReference1.class;
    }

    protected String metaObjectToString() {
        return "tcs.OperatorTemplatePropertyReference1 (Java Type)\nTCS.OperatorTemplate_PropertyReference1 (MOF Type)"; //$NON-NLS-1$
    }    
}