/**
 * Generated by the MOIN JMI Generator Version 3.0
 **/

package org.omg.ocl.stdlibrary.__impl;

public final class OrderedSetTypeStdLibClassImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl implements org.omg.ocl.stdlibrary.OrderedSetTypeStdLibClass,org.omg.ocl.stdlibrary.__impl.OrderedSetTypeStdLibClassInternal {

    
    static {
    }

    // static variable declarations
    
    // default constructor
    public OrderedSetTypeStdLibClassImpl() {
        super();
    }

    // specific constructor
    public OrderedSetTypeStdLibClassImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }

    // object creators
    public org.omg.ocl.stdlibrary.OrderedSetTypeStdLib createOrderedSetTypeStdLib() throws com.sap.tc.moin.repository.mmi.reflect.JmiException {
    
        org.omg.ocl.stdlibrary.OrderedSetTypeStdLib result = (org.omg.ocl.stdlibrary.OrderedSetTypeStdLib) refCreateInstance(get___CurrentConnection(), (java.util.List<? extends Object>)null);
        ((org.omg.ocl.stdlibrary.__impl.OrderedSetTypeStdLibImpl) result).initialize___Values(get___CurrentConnection());
        return result;
    }
    public org.omg.ocl.stdlibrary.OrderedSetTypeStdLib createOrderedSetTypeStdLib(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException {
    
        org.omg.ocl.stdlibrary.OrderedSetTypeStdLib result = (org.omg.ocl.stdlibrary.OrderedSetTypeStdLib) refCreateInstance(connection, (java.util.List<? extends Object>)null);
        ((org.omg.ocl.stdlibrary.__impl.OrderedSetTypeStdLibImpl) result).initialize___Values(connection);
        return result;
    }
    public org.omg.ocl.stdlibrary.OrderedSetTypeStdLib createOrderedSetTypeStdLibInPartition(com.sap.tc.moin.repository.ModelPartition partition) throws com.sap.tc.moin.repository.mmi.reflect.JmiException {
    
        org.omg.ocl.stdlibrary.OrderedSetTypeStdLib result = (org.omg.ocl.stdlibrary.OrderedSetTypeStdLib) refCreateInstanceInPartition(get___CurrentConnection(), (java.util.List<? extends Object>)null, partition);
        ((org.omg.ocl.stdlibrary.__impl.OrderedSetTypeStdLibImpl) result).initialize___Values(get___CurrentConnection());
        return result;
    }
    public org.omg.ocl.stdlibrary.OrderedSetTypeStdLib createOrderedSetTypeStdLibInPartition(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.ModelPartition partition) throws com.sap.tc.moin.repository.mmi.reflect.JmiException {
    
        org.omg.ocl.stdlibrary.OrderedSetTypeStdLib result = (org.omg.ocl.stdlibrary.OrderedSetTypeStdLib) refCreateInstanceInPartition(connection, (java.util.List<? extends Object>)null, partition);
        ((org.omg.ocl.stdlibrary.__impl.OrderedSetTypeStdLibImpl) result).initialize___Values(connection);
        return result;
    }
    public org.omg.ocl.stdlibrary.OrderedSetTypeStdLib createOrderedSetTypeStdLib(java.lang.String name, java.lang.String annotation, boolean isRoot, boolean isLeaf, boolean isAbstract, com.sap.tc.moin.repository.mmi.model.VisibilityKind visibility) throws com.sap.tc.moin.repository.mmi.reflect.JmiException {
        java.util.List<java.lang.Object> parameterList = new java.util.ArrayList<java.lang.Object>(6);
        parameterList.add(name);
        parameterList.add(annotation);
        parameterList.add(isRoot);
        parameterList.add(isLeaf);
        parameterList.add(isAbstract);
        parameterList.add(visibility);
        return (org.omg.ocl.stdlibrary.OrderedSetTypeStdLib) refCreateInstance(get___CurrentConnection(), parameterList);
    }
    public org.omg.ocl.stdlibrary.OrderedSetTypeStdLib createOrderedSetTypeStdLib(com.sap.tc.moin.repository.core.CoreConnection connection, java.lang.String name, java.lang.String annotation, boolean isRoot, boolean isLeaf, boolean isAbstract, com.sap.tc.moin.repository.mmi.model.VisibilityKind visibility) throws com.sap.tc.moin.repository.mmi.reflect.JmiException {
        java.util.List<java.lang.Object> parameterList = new java.util.ArrayList<java.lang.Object>(6);
        parameterList.add(name);
        parameterList.add(annotation);
        parameterList.add(isRoot);
        parameterList.add(isLeaf);
        parameterList.add(isAbstract);
        parameterList.add(visibility);
        return (org.omg.ocl.stdlibrary.OrderedSetTypeStdLib) refCreateInstance(connection, parameterList);
    }
    public org.omg.ocl.stdlibrary.OrderedSetTypeStdLib createOrderedSetTypeStdLibInPartition(java.lang.String name, java.lang.String annotation, boolean isRoot, boolean isLeaf, boolean isAbstract, com.sap.tc.moin.repository.mmi.model.VisibilityKind visibility, com.sap.tc.moin.repository.ModelPartition partition) throws com.sap.tc.moin.repository.mmi.reflect.JmiException {
        java.util.List<java.lang.Object> parameterList = new java.util.ArrayList<java.lang.Object>(6);
        parameterList.add(name);
        parameterList.add(annotation);
        parameterList.add(isRoot);
        parameterList.add(isLeaf);
        parameterList.add(isAbstract);
        parameterList.add(visibility);
        return (org.omg.ocl.stdlibrary.OrderedSetTypeStdLib) refCreateInstanceInPartition(get___CurrentConnection(), parameterList, partition);
    }
    public org.omg.ocl.stdlibrary.OrderedSetTypeStdLib createOrderedSetTypeStdLibInPartition(com.sap.tc.moin.repository.core.CoreConnection connection, java.lang.String name, java.lang.String annotation, boolean isRoot, boolean isLeaf, boolean isAbstract, com.sap.tc.moin.repository.mmi.model.VisibilityKind visibility, com.sap.tc.moin.repository.ModelPartition partition) throws com.sap.tc.moin.repository.mmi.reflect.JmiException {
        java.util.List<java.lang.Object> parameterList = new java.util.ArrayList<java.lang.Object>(6);
        parameterList.add(name);
        parameterList.add(annotation);
        parameterList.add(isRoot);
        parameterList.add(isLeaf);
        parameterList.add(isAbstract);
        parameterList.add(visibility);
        return (org.omg.ocl.stdlibrary.OrderedSetTypeStdLib) refCreateInstanceInPartition(connection, parameterList, partition);
    }

    // methods for static attributes
    
    
    // methods for modeled static operations
    
    // methods for structure type creators


    // methods for internal modeled operations

    // internal enumeration creators

    // internal structure type creators

    // reflective methods
        
    


    // for performance reasons overwrite method
    public boolean is___Singleton() {
        return false;
    }
    // for performance reasons overwrite method
    public boolean is___Abstract() {
        return false;
    }

    public com.sap.tc.moin.repository.mmi.reflect.RefObject get___Instance() throws com.sap.tc.moin.repository.mmi.reflect.JmiException {
        return new org.omg.ocl.stdlibrary.__impl.OrderedSetTypeStdLibImpl();    
    }

    // get the JMI interface
    public java.lang.Class<org.omg.ocl.stdlibrary.OrderedSetTypeStdLibClass> get___JmiInterface() {
        return org.omg.ocl.stdlibrary.OrderedSetTypeStdLibClass.class;
    }
        
    
    // reflective methods
    

    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<org.omg.ocl.stdlibrary.__impl.OrderedSetTypeStdLibClassImpl> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new org.omg.ocl.stdlibrary.__impl.OrderedSetTypeStdLibClassWrapper(conn, this, synchronize);
    }   

}