/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.__impl;

public final class NestedOfClusteredAreferencesNestedOfClusteredBImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public NestedOfClusteredAreferencesNestedOfClusteredBImpl() {
        super();
    }

    // specific constructor
    public NestedOfClusteredAreferencesNestedOfClusteredBImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredB, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredA) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _NestedOfClusteredB, _NestedOfClusteredA);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredB, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredA) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMultN( connection, _NestedOfClusteredB, _NestedOfClusteredA, "476118E36F8F0463A96F11DCCFF9001558C93B47"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getNestedOfClusteredB(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredA) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getNestedOfClusteredB(get___CurrentConnection(), _NestedOfClusteredA);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getNestedOfClusteredB(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredA) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        com.sap.tc.moin.repository.core.EndAndMetaObject endAndMetaObject = get___EndAndMetaObject( 1 );
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___queryElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _NestedOfClusteredA, endAndMetaObject );
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getNestedOfClusteredA(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredB) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getNestedOfClusteredA(get___CurrentConnection(), _NestedOfClusteredB);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getNestedOfClusteredA(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredB) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___getElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _NestedOfClusteredB, get___EndAndMetaObject( 0 ) );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredB, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredA) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_NestedOfClusteredB, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_NestedOfClusteredA);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredB, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredA) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_NestedOfClusteredB, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_NestedOfClusteredA);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredB, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredA) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_NestedOfClusteredB, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_NestedOfClusteredA);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredB, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _NestedOfClusteredA) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_NestedOfClusteredB, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_NestedOfClusteredA);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    public java.lang.Class<com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.NestedOfClusteredAreferencesNestedOfClusteredB> get___JmiInterface() {
        return com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.NestedOfClusteredAreferencesNestedOfClusteredB.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.NestedOfClusteredAreferencesNestedOfClusteredB> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.__impl.NestedOfClusteredAreferencesNestedOfClusteredBWrapper(conn, this, synchronize);
    }
}