/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.__impl;

public class NestedOfClusteredAWrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefObjectWrapperImpl<com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.__impl.NestedOfClusteredAImpl> implements com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.NestedOfClusteredA,com.sap.tc.moin.repository.Partitionable {

    
    static {
    }

    public NestedOfClusteredAWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.__impl.NestedOfClusteredAImpl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }

    private com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.__impl.NestedOfClusteredAImpl getCastWrappedObject() {
        return (com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.__impl.NestedOfClusteredAImpl) getWrappedObject();
    }
    
    public com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.__impl.NestedOfClusteredAImpl unwrap() {
        return (com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.__impl.NestedOfClusteredAImpl) getWrappedObject();
    }
        
    // methods for attributes
     
    // methods for references
   
    // methods for modeled operations
    
    // methods for internal modeled operations

    // reflective methods
    

    // get the JMI interface
    public java.lang.Class<com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.NestedOfClusteredA> get___JmiInterface() {
        return com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.NestedOfClusteredA.class;
    }

    // to String
    protected String metaObjectToString() {
        return "com.sap.tc.moin.testcases.case007.clustered.nestedofclustered.NestedOfClusteredA (Java Type)\ntestcases.case007.clustered.nestedOfClustered.nestedOfClusteredA (MOF Type)"; //$NON-NLS-1$
    }    
}