/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.event;
/**
 * This interface is not intended to be implemented by clients.
 */
public interface AEventBindingParameterMappings extends com.sap.tc.moin.repository.mmi.reflect.RefAssociation
{
    // association extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<com.sap.ide.metamodel.webdynpro.event.AEventBindingParameterMappings> ASSOCIATION_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<com.sap.ide.metamodel.webdynpro.event.AEventBindingParameterMappings>("45DDACEE8ED7F84DC1B140612FE2A8E4FF3A0B1A", "sap.com/tc/moin/webdynpro", "WebDynpro", "event", "A_EventBinding_ParameterMappings"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 


    // association interface
    public boolean exists(com.sap.ide.metamodel.webdynpro.event.EventBinding _EventBinding, com.sap.ide.metamodel.webdynpro.event.ParameterMapping _ParameterMappings) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public com.sap.ide.metamodel.webdynpro.event.EventBinding getEventBinding(com.sap.ide.metamodel.webdynpro.event.ParameterMapping _ParameterMappings) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.Collection<com.sap.ide.metamodel.webdynpro.event.ParameterMapping> getParameterMappings(com.sap.ide.metamodel.webdynpro.event.EventBinding _EventBinding) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean add(com.sap.ide.metamodel.webdynpro.event.EventBinding _EventBinding, com.sap.ide.metamodel.webdynpro.event.ParameterMapping _ParameterMappings) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean remove(com.sap.ide.metamodel.webdynpro.event.EventBinding _EventBinding, com.sap.ide.metamodel.webdynpro.event.ParameterMapping _ParameterMappings) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
}