/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.mi.gfw.mm.pictograms;

/**
 * This interface is not intended to be implemented by clients.
 */
public interface Style extends com.sap.mi.gfw.mm.pictograms.StyleContainer,com.sap.mi.gfw.mm.pictograms.AbstractStyle {

    /**
     * Descriptors for all features of this MofClass and its supertypes.
     */
    public static final Descriptors DESCRIPTORS = new Descriptors( );

    // class extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, com.sap.mi.gfw.mm.pictograms.Style> CLASS_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, com.sap.mi.gfw.mm.pictograms.Style>("46973F2C80BDECBB311F11DCC8D8001125D59A18", "sap.com/com/sap/mi/gfw/mm", "pictograms", "Style"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ 

    
    // attributes
    public java.lang.String getId() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setId(java.lang.String newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.lang.String getDescription() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setDescription(java.lang.String newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public com.sap.mi.gfw.mm.pictograms.Font getFont() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setFont(com.sap.mi.gfw.mm.pictograms.Font newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public com.sap.mi.gfw.mm.pictograms.Orientation getHorizontalAlignment() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setHorizontalAlignment(com.sap.mi.gfw.mm.pictograms.Orientation newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public com.sap.mi.gfw.mm.pictograms.Orientation getVerticalAlignment() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setVerticalAlignment(com.sap.mi.gfw.mm.pictograms.Orientation newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.lang.Integer getAngle() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setAngle(java.lang.Integer newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.lang.Boolean isStretchH() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setStretchH(java.lang.Boolean newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.lang.Boolean isStretchV() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setStretchV(java.lang.Boolean newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.lang.Boolean isProportional() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setProportional(java.lang.Boolean newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;

    // references
    public com.sap.mi.gfw.mm.pictograms.StyleContainer getStyleContainer() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setStyleContainer(com.sap.mi.gfw.mm.pictograms.StyleContainer newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;


    public static final class Descriptors {
        Descriptors( ) { 
        }
        /**
         * Returns the descriptor for the <code>lineWidth</code> attribute.
         * @return  the descriptor for the <code>lineWidth</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.AbstractStyle,java.lang.Integer> LINE_WIDTH( ) {
            return com.sap.mi.gfw.mm.pictograms.AbstractStyle.DESCRIPTORS.LINE_WIDTH( );
        }
        /**
         * Returns the descriptor for the <code>lineStyle</code> attribute.
         * @return  the descriptor for the <code>lineStyle</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.AbstractStyle,com.sap.mi.gfw.mm.pictograms.LineStyle> LINE_STYLE( ) {
            return com.sap.mi.gfw.mm.pictograms.AbstractStyle.DESCRIPTORS.LINE_STYLE( );
        }
        /**
         * Returns the descriptor for the <code>filled</code> attribute.
         * @return  the descriptor for the <code>filled</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.AbstractStyle,java.lang.Boolean> FILLED( ) {
            return com.sap.mi.gfw.mm.pictograms.AbstractStyle.DESCRIPTORS.FILLED( );
        }
        /**
         * Returns the descriptor for the <code>lineVisible</code> attribute.
         * @return  the descriptor for the <code>lineVisible</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.AbstractStyle,java.lang.Boolean> LINE_VISIBLE( ) {
            return com.sap.mi.gfw.mm.pictograms.AbstractStyle.DESCRIPTORS.LINE_VISIBLE( );
        }
        /**
         * Returns the descriptor for the <code>renderingStyle</code> attribute.
         * @return  the descriptor for the <code>renderingStyle</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.AbstractStyle,com.sap.mi.gfw.mm.pictograms.RenderingStyle> RENDERING_STYLE( ) {
            return com.sap.mi.gfw.mm.pictograms.AbstractStyle.DESCRIPTORS.RENDERING_STYLE( );
        }
        /**
         * Returns the descriptor for the <code>transparency</code> attribute.
         * @return  the descriptor for the <code>transparency</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.AbstractStyle,java.lang.Double> TRANSPARENCY( ) {
            return com.sap.mi.gfw.mm.pictograms.AbstractStyle.DESCRIPTORS.TRANSPARENCY( );
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.String> __id;
        /**
         * Returns the descriptor for the <code>id</code> attribute.
         * @return  the descriptor for the <code>id</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.String> ID( ) {
            if ( __id == null ) {
                __id = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.String>( "4697441C723DBCD0312211DC8980001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "id" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __id;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.String> __description;
        /**
         * Returns the descriptor for the <code>description</code> attribute.
         * @return  the descriptor for the <code>description</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.String> DESCRIPTION( ) {
            if ( __description == null ) {
                __description = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.String>( "4697441C723DBCD1312211DCB478001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "description" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __description;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.Font> __font;
        /**
         * Returns the descriptor for the <code>font</code> attribute.
         * @return  the descriptor for the <code>font</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.Font> FONT( ) {
            if ( __font == null ) {
                __font = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.Font>( "46973F2C80BDECB2311F11DC9519001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "font" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __font;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.Orientation> __horizontalAlignment;
        /**
         * Returns the descriptor for the <code>horizontalAlignment</code> attribute.
         * @return  the descriptor for the <code>horizontalAlignment</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.Orientation> HORIZONTAL_ALIGNMENT( ) {
            if ( __horizontalAlignment == null ) {
                __horizontalAlignment = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.Orientation>( "46973F2C80BDECB3311F11DCC731001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "horizontalAlignment" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __horizontalAlignment;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.Orientation> __verticalAlignment;
        /**
         * Returns the descriptor for the <code>verticalAlignment</code> attribute.
         * @return  the descriptor for the <code>verticalAlignment</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.Orientation> VERTICAL_ALIGNMENT( ) {
            if ( __verticalAlignment == null ) {
                __verticalAlignment = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.Orientation>( "46973F2C80BDECB4311F11DCC5FB001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "verticalAlignment" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __verticalAlignment;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Integer> __angle;
        /**
         * Returns the descriptor for the <code>angle</code> attribute.
         * @return  the descriptor for the <code>angle</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Integer> ANGLE( ) {
            if ( __angle == null ) {
                __angle = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Integer>( "46973F2C80BDECB5311F11DC9664001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "angle" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __angle;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Boolean> __stretchH;
        /**
         * Returns the descriptor for the <code>stretchH</code> attribute.
         * @return  the descriptor for the <code>stretchH</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Boolean> STRETCH_H( ) {
            if ( __stretchH == null ) {
                __stretchH = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Boolean>( "46973F2C80BDECB6311F11DCB6C1001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "stretchH" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __stretchH;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Boolean> __stretchV;
        /**
         * Returns the descriptor for the <code>stretchV</code> attribute.
         * @return  the descriptor for the <code>stretchV</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Boolean> STRETCH_V( ) {
            if ( __stretchV == null ) {
                __stretchV = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Boolean>( "46973F2C80BDECB7311F11DC9749001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "stretchV" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __stretchV;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Boolean> __proportional;
        /**
         * Returns the descriptor for the <code>proportional</code> attribute.
         * @return  the descriptor for the <code>proportional</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Boolean> PROPORTIONAL( ) {
            if ( __proportional == null ) {
                __proportional = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.mi.gfw.mm.pictograms.Style,java.lang.Boolean>( "46973F2C80BDECB8311F11DCCAA6001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "proportional" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __proportional;
        }
        /**
         * Returns the descriptor for the <code>styles</code> reference.
         * @return  the descriptor for the <code>styles</code> reference
         */
        public com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.mi.gfw.mm.pictograms.StyleContainer,java.util.Collection<com.sap.mi.gfw.mm.pictograms.Style>> STYLES( ) {
            return com.sap.mi.gfw.mm.pictograms.StyleContainer.DESCRIPTORS.STYLES( );
        }
        /**
         * Returns the descriptor for the <code>background</code> reference.
         * @return  the descriptor for the <code>background</code> reference
         */
        public com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.mi.gfw.mm.pictograms.AbstractStyle,com.sap.mi.gfw.mm.datatypes.Color> BACKGROUND( ) {
            return com.sap.mi.gfw.mm.pictograms.AbstractStyle.DESCRIPTORS.BACKGROUND( );
        }
        /**
         * Returns the descriptor for the <code>foreground</code> reference.
         * @return  the descriptor for the <code>foreground</code> reference
         */
        public com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.mi.gfw.mm.pictograms.AbstractStyle,com.sap.mi.gfw.mm.datatypes.Color> FOREGROUND( ) {
            return com.sap.mi.gfw.mm.pictograms.AbstractStyle.DESCRIPTORS.FOREGROUND( );
        }
        private com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.StyleContainer> __styleContainer;
        /**
         * Returns the descriptor for the <code>styleContainer</code> reference.
         * @return  the descriptor for the <code>styleContainer</code> reference
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.StyleContainer> STYLE_CONTAINER( ) {
            if ( __styleContainer == null ) {
                __styleContainer = new com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.mi.gfw.mm.pictograms.Style,com.sap.mi.gfw.mm.pictograms.StyleContainer>( "46973F2C80BDECBA311F11DCBE17001125D59A18", "sap.com/com/sap/mi/gfw/mm", new java.lang.String[] { "pictograms", "Style", "styleContainer" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __styleContainer;
        }
    }
}    