<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vortrag"
    nsURI="http://vortrag/1.0" nsPrefix="vortrag">
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eOperations name="bekommtKind" eType="#//Person"/>
    <eOperations name="hatGeburtstag"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autos" upperBound="-1"
        eType="#//Auto" eOpposite="#//Auto/besitzer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kinder" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/eltern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eltern" lowerBound="2"
        upperBound="2" eType="#//Person" eOpposite="#//Person/kinder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//Container"
        eOpposite="#//Container/person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Auto">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kennzeichen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marke" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="erstzulassung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baujahr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="besitzer" lowerBound="1"
        eType="#//Person" eOpposite="#//Person/autos"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//Container"
        eOpposite="#//Container/auto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" upperBound="-1"
        eType="#//Person" containment="true" eOpposite="#//Person/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auto" upperBound="-1" eType="#//Auto"
        containment="true" eOpposite="#//Auto/container"/>
  </eClassifiers>
</ecore:EPackage>
