<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ForeachPredicatePropertyInit"
    nsURI="http://www.furcas.org/TCS/featuretests/property/ForeachPredicatePropertyInit"
    nsPrefix="ForeachPredicatePropertyInit">
  <eClassifiers xsi:type="ecore:EClass" name="BibTextFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" ordered="false"
        upperBound="-1" eType="#//BibTextEntry" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="bibtexFile"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibTextEntry" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" unique="false"
        lowerBound="1" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="5"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Article" eSuperTypes="#//BibTextEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" ordered="false"
        lowerBound="1" eType="#//Author" eOpposite="#//Author/articles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" lowerBound="1" eType="#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author" eSuperTypes="#//BibTextEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="articles" ordered="false"
        upperBound="-1" eType="#//Article" eOpposite="#//Article/author"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revenues" upperBound="-1"
        eType="#//RevenueLedger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RevenueLedger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" lowerBound="1"
        eType="#//Article"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revenueInEUR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
</ecore:EPackage>
