<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="NestedScopes"
    nsURI="http://www.furcas.org/TCS/referenceresolving/tests/nestedScopes">
  <eClassifiers xsi:type="ecore:EClass" name="Definition" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usage" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundDefinition" lowerBound="1"
        eType="#//Definition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true">
    <eOperations name="getDeclarationsInScope" upperBound="-1" eType="#//Definition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="body" value="Definition.allInstances()->asOrderedSet()"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementsInBlock" upperBound="-1"
        eType="#//Statement"/>
  </eClassifiers>
</ecore:EPackage>
