<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="loopOperator2"
    nsURI="http://de.hpi.sam.bp2009.benchframework.loopOperator2" nsPrefix="benchframework.loopOperator2">
  <eClassifiers xsi:type="ecore:EClass" name="StartLoop" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//StartOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndLoop" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//EndOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoopOption" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//OptionObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repetitions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
</ecore:EPackage>
