<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="de"
    nsURI="http:///de.ecore" nsPrefix="de">
  <eSubpackages name="ikv" nsURI="http:///de/ikv.ecore" nsPrefix="de.ikv">
    <eSubpackages name="medini" nsURI="http:///de/ikv/medini.ecore" nsPrefix="de.ikv.medini">
      <eSubpackages name="kernel" nsURI="http:///de/ikv/medini/kernel.ecore" nsPrefix="de.ikv.medini.kernel">
        <eClassifiers xsi:type="ecore:EClass" name="MediniObject" abstract="true">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediniIdentifier"
              ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
              iD="true"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
