<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestMetaModel"
    nsURI="http:///TestMetaModel.ecore" nsPrefix="TestMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelDummyClass"/>
  <eSubpackages name="ClassifierTest" nsURI="http:///TestMetaModel/ClassifierTest.ecore"
      nsPrefix="TestMetaModel.ClassifierTest">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractSuperClass" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subClass" ordered="false"
          upperBound="-1" eType="#//ClassifierTest/SubClass" eOpposite="#//ClassifierTest/SubClass/abstractSuperClass"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="AbstractSuperName" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubClass" eSuperTypes="#//ClassifierTest/SuperClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SubName" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="abstractSuperClass" ordered="false"
          upperBound="-1" eType="#//ClassifierTest/AbstractSuperClass" eOpposite="#//ClassifierTest/AbstractSuperClass/subClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperClass" eSuperTypes="#//ClassifierTest/AbstractSuperClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SuperName" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="DataTypeTests" nsURI="http:///TestMetaModel/DataTypeTests.ecore"
      nsPrefix="TestMetaModel.DataTypeTests">
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="#//DataTypeTests/EnumerationTestType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="#//DataTypeTests/EnumerationTestType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="#//DataTypeTests/EnumerationTestType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="#//DataTypeTests/EnumerationTestType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="#//DataTypeTests/EnumerationTestType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="#//DataTypeTests/EnumerationTestType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EnumerationTestType">
      <eLiterals name="Label3"/>
      <eLiterals name="Label4" value="1"/>
      <eLiterals name="Label1" value="2"/>
      <eLiterals name="Label2" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructureTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="#//DataTypeTests/StructureTestType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SetAttribute" ordered="false"
          upperBound="-1" eType="#//DataTypeTests/StructureTestType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="OrderedSetAttribute"
          lowerBound="1" upperBound="-1" eType="#//DataTypeTests/StructureTestType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="#//DataTypeTests/StructureTestType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="#//DataTypeTests/StructureTestType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="#//DataTypeTests/StructureTestType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructureTestType" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="IntegerStructField" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="EnumStructField" ordered="false"
          unique="false" lowerBound="1" eType="#//DataTypeTests/EnumerationTestType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="StringStructField" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BooleanStructField" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="FloatStructureField"
          ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DoubleStructureField"
          ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="LongStructField" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ClassStructField" ordered="false"
          unique="false" lowerBound="1" eType="#//PrimitiveTypesTests/StringTest"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="PrimitiveTypesTests" nsURI="http:///TestMetaModel/PrimitiveTypesTests.ecore"
      nsPrefix="TestMetaModel.PrimitiveTypesTests">
    <eClassifiers xsi:type="ecore:EClass" name="BooleanTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoubleTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FloatTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LongTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="PrimitiveTypesStaticTests" nsURI="http:///TestMetaModel/PrimitiveTypesStaticTests.ecore"
      nsPrefix="TestMetaModel.PrimitiveTypesStaticTests">
    <eClassifiers xsi:type="ecore:EClass" name="StaticBooleanTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dummy" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaticDoubleTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dummy" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaticFloatTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dummy" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaticIntegerTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dummy" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaticLongTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dummy" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleAttribute" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionalSimpleAttribute"
          ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SequenceAttribute" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SetAttribute" ordered="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OrderedSetAttribute"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dummy" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BagAttribute" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="RelationshipTests" nsURI="http:///TestMetaModel/RelationshipTests.ecore"
      nsPrefix="TestMetaModel.RelationshipTests">
    <eClassifiers xsi:type="ecore:EClass" name="ClassTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiClassReference"
          ordered="false" upperBound="-1" eType="#//PrimitiveTypesStaticTests/StaticBooleanTest"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="singleClassReference"
          ordered="false" lowerBound="1" eType="#//PrimitiveTypesStaticTests/StringTest"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SingleClassAttribute"
          ordered="false" lowerBound="1" eType="#//PrimitiveTypesTests/StringTest"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="MultiUniqueClassAttribute"
          ordered="false" upperBound="-1" eType="#//PrimitiveTypesTests/IntegerTest"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="MultiNonUniqueClassAttribute"
          ordered="false" unique="false" upperBound="-1" eType="#//PrimitiveTypesTests/StringTest"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NavigableAssociationTest" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentEnd" ordered="false"
          lowerBound="1" eType="#//PrimitiveTypesStaticTests/StaticIntegerTest"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="aggregate" ordered="false"
          upperBound="-1" eType="#//PrimitiveTypesStaticTests/StaticLongTest"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
