/**
 * Generated by the MOIN Generator Version 3.0
 **/

package testmetamodel.__impl;

public final class TopLevelDummyClassImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefObjectImpl {

    
    static {
    }
    
    // default constructor
    public TopLevelDummyClassImpl() {
        super();
    }
    
    // specific constructor
    public TopLevelDummyClassImpl(java.lang.Object workspace, String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject, com.sap.tc.moin.repository.mmi.reflect.RefClass refClass) {
        super(workspace, mofId, immediatePackage, metaObject, refClass);
    }
    
    // methods for internal attribute setter

    // reflective methods
        
    


    // get the JMI interface
    public java.lang.Class<testmetamodel.TopLevelDummyClass> get___JmiInterface() {
        return testmetamodel.TopLevelDummyClass.class;
    }

    // create the wrapper
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<testmetamodel.__impl.TopLevelDummyClassImpl> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new testmetamodel.__impl.TopLevelDummyClassWrapper(conn, this, synchronize);
    }
    
}