/**
 * Generated by the MOIN Generator Version 3.0
 **/

package textblocks;
/**
 * This interface is not intended to be implemented by clients.
 */
public interface DocumentNodeHasDocumentNodeVersions extends com.sap.tc.moin.repository.mmi.reflect.RefAssociation
{
    // association extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<textblocks.DocumentNodeHasDocumentNodeVersions> ASSOCIATION_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<textblocks.DocumentNodeHasDocumentNodeVersions>("480716BCBE2DC5500C5F11DDB14600016CE99C52", "demo.sap.com/tcsmeta", "textblocks", "DocumentNode_Has_DocumentNodeVersions"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ 


    // association interface
    public boolean exists(textblocks.DocumentNode _OtherVersions, textblocks.DocumentNode _DocumentNode) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.List<textblocks.DocumentNode> getOtherVersions(textblocks.DocumentNode _DocumentNode) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.Collection<textblocks.DocumentNode> getDocumentNode(textblocks.DocumentNode _OtherVersions) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean add(textblocks.DocumentNode _OtherVersions, textblocks.DocumentNode _DocumentNode) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean remove(textblocks.DocumentNode _OtherVersions, textblocks.DocumentNode _DocumentNode) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
}