<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CorbaIdlTypes"
    nsURI="http://sap.com/moin/CorbaIdlTypes" nsPrefix="corbaidltypes">
  <eAnnotations source="http://sap.com/MOIN">
    <details key="CorbaIdlTypes.CorbaOctet" value="//CorbaOctet"/>
    <details key="CorbaIdlTypes.CorbaShort" value="//CorbaShort"/>
    <details key="CorbaIdlTypes.CorbaUnsignedShort" value="//CorbaUnsignedShort"/>
    <details key="CorbaIdlTypes.CorbaUnsignedLong" value="//CorbaUnsignedLong"/>
    <details key="CorbaIdlTypes.CorbaUnsignedLongLong" value="//CorbaUnsignedLongLong"/>
    <details key="CorbaIdlTypes.CorbaLongDouble" value="//CorbaLongDouble"/>
    <details key="CorbaIdlTypes.CorbaString" value="//CorbaString"/>
    <details key="CorbaIdlTypes.CorbaChar" value="//CorbaChar"/>
    <details key="CorbaIdlTypes.CorbaWChar" value="//CorbaWChar"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaOctet">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="CorbaIdlTypes.CorbaOctet"/>
      <details key="metaObjectMofId" value="4625EA0207E9C53B88824EC92D44CF71684E3BF8"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaShort">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="CorbaIdlTypes.CorbaShort"/>
      <details key="metaObjectMofId" value="4625EA025A8B87151E42492E220987C485BFF582"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaUnsignedShort">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="CorbaIdlTypes.CorbaUnsignedShort"/>
      <details key="metaObjectMofId" value="4625EA0285B26943A09D4CF22E9D8E6F789125C4"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaUnsignedLong">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="CorbaIdlTypes.CorbaUnsignedLong"/>
      <details key="metaObjectMofId" value="4625EA02E33898C22AF840E01878CD4B83ECDB03"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaUnsignedLongLong">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="CorbaIdlTypes.CorbaUnsignedLongLong"/>
      <details key="metaObjectMofId" value="4625EA02143D63ED323E4FF006D5943DF62FF4B4"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaLongDouble">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="CorbaIdlTypes.CorbaLongDouble"/>
      <details key="metaObjectMofId" value="4625EA02D42A2B4136A34D351D2DD894F502E061"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaString">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="CorbaIdlTypes.CorbaString"/>
      <details key="metaObjectMofId" value="4625EA02621591FEEB8F4D030C4BD82B1489EE74"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaChar">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="CorbaIdlTypes.CorbaChar"/>
      <details key="metaObjectMofId" value="4625EA02D4F5DEB55DE94CDE145D85D89B0F22DD"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorbaWChar">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="CorbaIdlTypes.CorbaWChar"/>
      <details key="metaObjectMofId" value="4625EA0254D19C09D87B478B26A8CD268FD80681"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
