/**
 * Generated by the MOIN Generator Version 3.0
 **/

package uml.__impl;

public final class ActualImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public ActualImpl() {
        super();
    }

    // specific constructor
    public ActualImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Templateparametersubstitution, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Actual) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _Templateparametersubstitution, _Actual);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Templateparametersubstitution, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Actual) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMultN( connection, _Templateparametersubstitution, _Actual, "498694159E327912F0F311DD919B000E35A783E4"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getTemplateparametersubstitution(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Actual) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getTemplateparametersubstitution(get___CurrentConnection(), _Actual);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getTemplateparametersubstitution(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Actual) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        com.sap.tc.moin.repository.core.EndAndMetaObject endAndMetaObject = get___EndAndMetaObject( 1 );
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___queryElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _Actual, endAndMetaObject );
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getActual(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Templateparametersubstitution) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getActual(get___CurrentConnection(), _Templateparametersubstitution);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getActual(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Templateparametersubstitution) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___getElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _Templateparametersubstitution, get___EndAndMetaObject( 0 ) );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Templateparametersubstitution, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Actual) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Templateparametersubstitution, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Actual);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Templateparametersubstitution, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Actual) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Templateparametersubstitution, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Actual);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Templateparametersubstitution, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Actual) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Templateparametersubstitution, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Actual);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Templateparametersubstitution, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Actual) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Templateparametersubstitution, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Actual);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    public java.lang.Class<uml.Actual> get___JmiInterface() {
        return uml.Actual.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<uml.Actual> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new uml.__impl.ActualWrapper(conn, this, synchronize);
    }
}