/**
* <copyright>
*
* Copyright (c) 2005, 2007 IBM Corporation and others.
* All rights reserved.   This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
*   IBM - Initial API and implementation
*
* </copyright>
*
* $Id: OCLLPGParsersym.java,v 1.4 2007/04/05 20:36:07 cdamus Exp $
*/

package org.eclipse.ocl.internal.parser;

@SuppressWarnings({"unchecked", "nls"})
public interface OCLLPGParsersym {
    public final static int
      TK_NUMERIC_OPERATION = 58,
      TK_STRING_LITERAL = 59,
      TK_INTEGER_LITERAL = 60,
      TK_REAL_LITERAL = 61,
      TK_PLUS = 28,
      TK_MINUS = 29,
      TK_MULTIPLY = 16,
      TK_DIVIDE = 17,
      TK_GREATER = 18,
      TK_LESS = 19,
      TK_EQUAL = 4,
      TK_GREATER_EQUAL = 20,
      TK_LESS_EQUAL = 21,
      TK_NOT_EQUAL = 14,
      TK_LPAREN = 1,
      TK_RPAREN = 2,
      TK_LBRACE = 78,
      TK_RBRACE = 79,
      TK_LBRACKET = 80,
      TK_RBRACKET = 81,
      TK_ARROW = 85,
      TK_BAR = 70,
      TK_COMMA = 35,
      TK_COLON = 22,
      TK_COLONCOLON = 67,
      TK_SEMICOLON = 86,
      TK_DOT = 87,
      TK_DOTDOT = 88,
      TK_ATPRE = 69,
      TK_CARET = 89,
      TK_CARETCARET = 90,
      TK_QUESTIONMARK = 82,
      TK_self = 23,
      TK_inv = 72,
      TK_pre = 73,
      TK_post = 74,
      TK_body = 75,
      TK_context = 15,
      TK_package = 24,
      TK_endpackage = 91,
      TK_def = 76,
      TK_derive = 83,
      TK_init = 84,
      TK_if = 68,
      TK_then = 92,
      TK_else = 93,
      TK_endif = 94,
      TK_and = 25,
      TK_or = 26,
      TK_xor = 27,
      TK_not = 36,
      TK_implies = 95,
      TK_let = 62,
      TK_in = 96,
      TK_true = 63,
      TK_false = 64,
      TK_Set = 30,
      TK_Bag = 31,
      TK_Sequence = 32,
      TK_Collection = 33,
      TK_OrderedSet = 34,
      TK_iterate = 37,
      TK_forAll = 38,
      TK_exists = 39,
      TK_isUnique = 40,
      TK_any = 41,
      TK_one = 42,
      TK_collect = 43,
      TK_select = 44,
      TK_reject = 45,
      TK_collectNested = 46,
      TK_sortedBy = 47,
      TK_closure = 48,
      TK_oclIsKindOf = 49,
      TK_oclIsTypeOf = 50,
      TK_oclAsType = 51,
      TK_oclIsNew = 52,
      TK_oclIsUndefined = 53,
      TK_oclIsInvalid = 54,
      TK_oclIsInState = 55,
      TK_allInstances = 56,
      TK_String = 5,
      TK_Integer = 6,
      TK_UnlimitedNatural = 7,
      TK_Real = 8,
      TK_Boolean = 9,
      TK_Tuple = 57,
      TK_OclAny = 10,
      TK_OclVoid = 11,
      TK_Invalid = 12,
      TK_OclMessage = 13,
      TK_null = 65,
      TK_OclInvalid = 66,
      TK_EOF_TOKEN = 71,
      TK_IDENTIFIER = 3,
      TK_INTEGER_RANGE_START = 77,
      TK_ERROR_TOKEN = 97;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "LPAREN",
                 "RPAREN",
                 "IDENTIFIER",
                 "EQUAL",
                 "String",
                 "Integer",
                 "UnlimitedNatural",
                 "Real",
                 "Boolean",
                 "OclAny",
                 "OclVoid",
                 "Invalid",
                 "OclMessage",
                 "NOT_EQUAL",
                 "context",
                 "MULTIPLY",
                 "DIVIDE",
                 "GREATER",
                 "LESS",
                 "GREATER_EQUAL",
                 "LESS_EQUAL",
                 "COLON",
                 "self",
                 "package",
                 "and",
                 "or",
                 "xor",
                 "PLUS",
                 "MINUS",
                 "Set",
                 "Bag",
                 "Sequence",
                 "Collection",
                 "OrderedSet",
                 "COMMA",
                 "not",
                 "iterate",
                 "forAll",
                 "exists",
                 "isUnique",
                 "any",
                 "one",
                 "collect",
                 "select",
                 "reject",
                 "collectNested",
                 "sortedBy",
                 "closure",
                 "oclIsKindOf",
                 "oclIsTypeOf",
                 "oclAsType",
                 "oclIsNew",
                 "oclIsUndefined",
                 "oclIsInvalid",
                 "oclIsInState",
                 "allInstances",
                 "Tuple",
                 "NUMERIC_OPERATION",
                 "STRING_LITERAL",
                 "INTEGER_LITERAL",
                 "REAL_LITERAL",
                 "let",
                 "true",
                 "false",
                 "null",
                 "OclInvalid",
                 "COLONCOLON",
                 "if",
                 "ATPRE",
                 "BAR",
                 "EOF_TOKEN",
                 "inv",
                 "pre",
                 "post",
                 "body",
                 "def",
                 "INTEGER_RANGE_START",
                 "LBRACE",
                 "RBRACE",
                 "LBRACKET",
                 "RBRACKET",
                 "QUESTIONMARK",
                 "derive",
                 "init",
                 "ARROW",
                 "SEMICOLON",
                 "DOT",
                 "DOTDOT",
                 "CARET",
                 "CARETCARET",
                 "endpackage",
                 "then",
                 "else",
                 "endif",
                 "implies",
                 "in",
                 "ERROR_TOKEN"
             };

    public final static boolean isValidForParser = true;
}
