/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.component.controller.__impl;

public final class AControllerUsageComponentUsageImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public AControllerUsageComponentUsageImpl() {
        super();
    }

    // specific constructor
    public AControllerUsageComponentUsageImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ControllerUsage, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _ControllerUsage, _ComponentUsage);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ControllerUsage, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMult1( connection, _ControllerUsage, _ComponentUsage, "460CC65C30BDA3AE8CAD495133BAE737B26E28F4"); //$NON-NLS-1$
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getControllerUsage(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getControllerUsage(get___CurrentConnection(), _ComponentUsage);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getControllerUsage(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___queryElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _ComponentUsage, get___EndAndMetaObject( 1 ) );
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getComponentUsage(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ControllerUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getComponentUsage(get___CurrentConnection(), _ControllerUsage);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getComponentUsage(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ControllerUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _ControllerUsage, "460CC65C30BDA3AE8CAD495133BAE737B26E28F4"); //$NON-NLS-1$
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ControllerUsage, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_ControllerUsage, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ComponentUsage);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ControllerUsage, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ControllerUsage, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ComponentUsage);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ControllerUsage, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_ControllerUsage, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ComponentUsage);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ControllerUsage, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsage) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ControllerUsage, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ComponentUsage);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.webdynpro.component.controller.AControllerUsageComponentUsage> get___JmiInterface() {
        return com.sap.ide.metamodel.webdynpro.component.controller.AControllerUsageComponentUsage.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<com.sap.ide.metamodel.webdynpro.component.controller.AControllerUsageComponentUsage> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new com.sap.ide.metamodel.webdynpro.component.controller.__impl.AControllerUsageComponentUsageWrapper(conn, this, synchronize);
    }
}