<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="solution"
    nsURI="http://de.hpi.sam.bp2009.solution" nsPrefix="solution">
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionSupplier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IA" eType="ecore:EClass ../../de.hpi.sam.bp2009.solution.impactAnalyzer/model/impactAnalyzer.ecore#//ImpactAnalyzer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Persistence">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventManager" eType="ecore:EClass ../../de.hpi.sam.bp2009.solution.eventManager/model/eventManager.ecore#//EventManager"/>
  </eClassifiers>
</ecore:EPackage>
