#!/bin/sh
PACKAGES="com/sap/junit com/sap/tc/moin/facility/primary/ide com/sap/tc/moin/facility/primary/diservice com/sap/tc/moin/facility/primary/inconsistency com/sap/tc/moin/facility/primary/versioning com/sap/tc/moin/primary/facility com/sap/tc/moin/repository/cps/test com/sap/tc/moin/repository/errorhandler com/sap/tc/moin/repository/runtimehost com/sap/tc/moin/repository/test/jmitck/tests com/sap/tc/moin/repository/test/performance com/sap/tc/moin/repository/test/rom com/sap/tc/moin/repository/test/s2x com/sap/tc/moin/test com/sap/tc/moin/xm/test/customexit/mc com/sap/tc/moin/xm/text/pfl testmm/mmr/mets"
for i in $PACKAGES; do
  for d in `find . -type d -wholename */$i*`; do
    j=$(echo $i | sed -e 's/\//\\\//g')
    echo j: $j
    echo $d | sed -e 's/.*\/'$j'\(.*\)$/'$j'\1/'
    dir=`echo $d | sed -e 's/.*\/'$j'\(.*\)$/'$j'\1/'`
    echo Shortened: $dir
    target=~/workspace/com.sap.tc.moin.repository.test.MoinTestEclipsePlugin/src/$dir
    echo target is "$target"
    cp -v $d/* "$target"
  done
done
