<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="queryEvaluator"
    nsURI="http://de.hpi.sam.bp2009.benchframework.queryEvaluator" nsPrefix="benchframework.queryEvaluator">
  <eClassifiers xsi:type="ecore:EClass" name="EmbedQEOperator" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="QueryEvaluator">
    <eOperations name="evaluateQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="query" eType="#//Query"/>
      <eParameters name="contextInstances">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Query" instanceClassName="org.eclipse.ocl.ecore.OCL.Query"/>
  <eClassifiers xsi:type="ecore:EEnum" name="QueryEvaluatorNotifyLiterals">
    <eLiterals name="START_QUERY_EVALUATION"/>
    <eLiterals name="END_QUERY_EVALUATION" value="1"/>
  </eClassifiers>
</ecore:EPackage>
