/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.mi.gfw.mm.datatypes.__impl;

public final class PointImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefStructImpl implements com.sap.mi.gfw.mm.datatypes.Point
{
    private static final long serialVersionUID = 1L;

    private static final java.util.List<String> QUALIFIED_NAME = java.util.Collections.unmodifiableList(java.util.Arrays.asList(new String[] { "datatypes", "Point" })); //$NON-NLS-1$ //$NON-NLS-2$
    
    private static final java.util.List<String> STRUCTURE_FIELD_NAMES = java.util.Collections.unmodifiableList(java.util.Arrays.asList(new String[] { "x", "y", "before", "after" })); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$

        
    public static final java.util.Map<java.lang.String, java.lang.Integer> FEATURE_IDS;
    
    static {
        
        FEATURE_IDS = new java.util.HashMap<java.lang.String, java.lang.Integer>();
        FEATURE_IDS.put("x", Integer.valueOf(0)); //$NON-NLS-1$
        FEATURE_IDS.put("y", Integer.valueOf(1)); //$NON-NLS-1$
        FEATURE_IDS.put("before", Integer.valueOf(2)); //$NON-NLS-1$
        FEATURE_IDS.put("after", Integer.valueOf(3)); //$NON-NLS-1$
    }

    // default constructor
    public PointImpl() {
        super();
    }
    // JMI constructor
    public PointImpl(java.lang.Object workspace, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, metaObject);
    }

    protected java.util.List<String> ___getTypeName() {
        return QUALIFIED_NAME;
    }

    protected java.util.List<String> ___getFieldNames() {
        return STRUCTURE_FIELD_NAMES;
    }

    // variable declarations
    private int __x;
    private int __y;
    private int __before;
    private int __after;
    // fields
    public int getX() throws com.sap.tc.moin.repository.mmi.reflect.JmiException 
    {
        return __x;
    }
    public int getY() throws com.sap.tc.moin.repository.mmi.reflect.JmiException 
    {
        return __y;
    }
    public int getBefore() throws com.sap.tc.moin.repository.mmi.reflect.JmiException 
    {
        return __before;
    }
    public int getAfter() throws com.sap.tc.moin.repository.mmi.reflect.JmiException 
    {
        return __after;
    }

    // get a value
    public Object refGetValue(String featureName) {
        Object result = null;
        java.lang.Integer featureId = FEATURE_IDS.get(featureName);
        if (featureId == null) {
            throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureName, get___MetaObject(), "refGetValue(String)"); //$NON-NLS-1$
        }
        switch (featureId) {
            case 0: 
                result = getX();
                break;
            case 1: 
                result = getY();
                break;
            case 2: 
                result = getBefore();
                break;
            case 3: 
                result = getAfter();
                break;
            default:
                throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureName, null, "refGetValue(String)"); //$NON-NLS-1$
        }
        return result;}
    


    public void set__X(int newValue) {
        __x = newValue;
    }
    public void set__Y(int newValue) {
        __y = newValue;
    }
    public void set__Before(int newValue) {
        __before = newValue;
    }
    public void set__After(int newValue) {
        __after = newValue;
    }
    // set the value internally
    public void set___Value(String featureName, Object value) {
        switch (FEATURE_IDS.get(featureName)) {
            case 0:
                set__X((java.lang.Integer) value);     
                break;
            case 1:
                set__Y((java.lang.Integer) value);     
                break;
            case 2:
                set__Before((java.lang.Integer) value);     
                break;
            case 3:
                set__After((java.lang.Integer) value);     
                break;
            default:
                throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureName, null, "set___Value(String)"); //$NON-NLS-1$
        }}
}