<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="emfindex"
    nsURI="http://www.eclipse.org/emfindex/1.0" nsPrefix="emfindex">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractBaseDescriptor" instanceClassName="org.eclipse.emf.emfindex.BaseDescriptor"
      abstract="true">
    <eOperations name="getUserData" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (userData != null) ? userData.get(key) : null;"/>
      </eAnnotations>
      <eParameters name="key" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="setUserData">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="getUserData().put(key, value);"/>
      </eAnnotations>
      <eParameters name="key" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userData" upperBound="-1"
        eType="#//UserDataEntry" unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerDescriptor" instanceClassName="org.eclipse.emf.emfindex.ContainerDescriptor"
      eSuperTypes="#//AbstractBaseDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceDescriptors" upperBound="-1"
        eType="#//ResourceDescriptor" containment="true" eOpposite="#//ResourceDescriptor/container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceDescriptor" instanceClassName="org.eclipse.emf.emfindex.ResourceDescriptor"
      eSuperTypes="#//AbstractBaseDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" lowerBound="1" eType="#//EURI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexedVersion" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//ContainerDescriptor"
        eOpposite="#//ContainerDescriptor/resourceDescriptors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObjectDescriptors" upperBound="-1"
        eType="#//EObjectDescriptor" containment="true" eOpposite="#//EObjectDescriptor/resourceDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReferenceDescriptors"
        upperBound="-1" eType="#//EReferenceDescriptor" containment="true" eOpposite="#//EReferenceDescriptor/sourceResourceDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectDescriptor" instanceClassName="org.eclipse.emf.emfindex.EObjectDescriptor"
      eSuperTypes="#//AbstractBaseDescriptor">
    <eOperations name="getFragmentURI" eType="#//EURI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getResourceDescriptor().getURI().appendFragment(fragment);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="createProxy" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="org.eclipse.emf.ecore.InternalEObject proxy = (org.eclipse.emf.ecore.InternalEObject) getEClass().getEPackage().getEFactoryInstance().create(getEClass());&#xA;proxy.eSetProxyURI(getFragmentURI());&#xA;return proxy;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fragment" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceDescriptor" eType="#//ResourceDescriptor"
        eOpposite="#//ResourceDescriptor/eObjectDescriptors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceDescriptor" instanceClassName="org.eclipse.emf.emfindex.EReferenceDescriptor"
      eSuperTypes="#//AbstractBaseDescriptor">
    <eOperations name="getTargetFragmentURI" eType="#//EURI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getTargetResourceURI().appendFragment(targetFragment);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getSourceFragmentURI" eType="#//EURI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getSourceResourceDescriptor().getURI().appendFragment(sourceFragment);"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceFragment" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReference" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetFragment" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetResourceURI" eType="#//EURI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEObjectDescriptor"
        eType="#//EObjectDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceResourceDescriptor"
        eType="#//ResourceDescriptor" eOpposite="#//ResourceDescriptor/eReferenceDescriptors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDataEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EURI" instanceClassName="org.eclipse.emf.common.util.URI"/>
</ecore:EPackage>
