/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.component.navigation;

/**
 * Outbound plugs are potential starting points for navigational links to other views.
 * This interface is not intended to be implemented by clients.
 */
public interface OutboundPlug extends com.sap.ide.metamodel.webdynpro.event.OutgoingEvent {

    /**
     * Descriptors for all features of this MofClass and its supertypes.
     */
    public static final Descriptors DESCRIPTORS = new Descriptors( );

    // class extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, com.sap.ide.metamodel.webdynpro.component.navigation.OutboundPlug> CLASS_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, com.sap.ide.metamodel.webdynpro.component.navigation.OutboundPlug>("45DDACEEAE1FE305BF944ACC24A2C4C17EF5CD00", "sap.com/tc/moin/webdynpro", "WebDynpro", "component", "navigation", "OutboundPlug"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ 

    
    // attributes
    public com.sap.ide.metamodel.webdynpro.enums.OutboundPlugTypeEnum getType() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setType(com.sap.ide.metamodel.webdynpro.enums.OutboundPlugTypeEnum newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;

    // references
    public com.sap.ide.metamodel.webdynpro.component.view.AbstractView getView() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setView(com.sap.ide.metamodel.webdynpro.component.view.AbstractView newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;


    public static final class Descriptors {
        Descriptors( ) { 
        }
        /**
         * Returns the descriptor for the <code>name</code> attribute.
         * @return  the descriptor for the <code>name</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.ide.metamodel.common.CommonDevelopmentObject,java.lang.String> NAME( ) {
            return com.sap.ide.metamodel.common.CommonDevelopmentObject.DESCRIPTORS.NAME( );
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.ide.metamodel.webdynpro.component.navigation.OutboundPlug,com.sap.ide.metamodel.webdynpro.enums.OutboundPlugTypeEnum> __type;
        /**
         * Returns the descriptor for the <code>type</code> attribute.
         * @return  the descriptor for the <code>type</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.ide.metamodel.webdynpro.component.navigation.OutboundPlug,com.sap.ide.metamodel.webdynpro.enums.OutboundPlugTypeEnum> TYPE( ) {
            if ( __type == null ) {
                __type = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,com.sap.ide.metamodel.webdynpro.component.navigation.OutboundPlug,com.sap.ide.metamodel.webdynpro.enums.OutboundPlugTypeEnum>( "45DDACEE74561906A2D94C733EB6C7320D8F3446", "sap.com/tc/moin/webdynpro", new java.lang.String[] { "WebDynpro", "component", "navigation", "OutboundPlug", "type" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ 
            }
            return __type;
        }
        /**
         * Returns the descriptor for the <code>templateInstances</code> reference.
         * @return  the descriptor for the <code>templateInstances</code> reference
         */
        public com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.ide.metamodel.common.CommonDevelopmentObject,java.util.List<com.sap.ide.metamodel.common.template.EmbeddedTemplateInstance>> TEMPLATE_INSTANCES( ) {
            return com.sap.ide.metamodel.common.CommonDevelopmentObject.DESCRIPTORS.TEMPLATE_INSTANCES( );
        }
        /**
         * Returns the descriptor for the <code>diagrams</code> reference.
         * @return  the descriptor for the <code>diagrams</code> reference
         */
        public com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.ide.metamodel.common.CommonDevelopmentObject,java.util.List<com.sap.ide.metamodel.common.diagram.EmbeddedDiagram>> DIAGRAMS( ) {
            return com.sap.ide.metamodel.common.CommonDevelopmentObject.DESCRIPTORS.DIAGRAMS( );
        }
        /**
         * Returns the descriptor for the <code>documentationObject</code> reference.
         * @return  the descriptor for the <code>documentationObject</code> reference
         */
        public com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.ide.metamodel.common.CommonDevelopmentObject,com.sap.ide.metamodel.common.DocumentationObject> DOCUMENTATION_OBJECT( ) {
            return com.sap.ide.metamodel.common.CommonDevelopmentObject.DESCRIPTORS.DOCUMENTATION_OBJECT( );
        }
        /**
         * Returns the descriptor for the <code>parameters</code> reference.
         * @return  the descriptor for the <code>parameters</code> reference
         */
        public com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.ide.metamodel.webdynpro.base.ParameterizedFeature,java.util.List<com.sap.ide.metamodel.webdynpro.base.Parameter>> PARAMETERS( ) {
            return com.sap.ide.metamodel.webdynpro.base.ParameterizedFeature.DESCRIPTORS.PARAMETERS( );
        }
        private com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.ide.metamodel.webdynpro.component.navigation.OutboundPlug,com.sap.ide.metamodel.webdynpro.component.view.AbstractView> __view;
        /**
         * Returns the descriptor for the <code>view</code> reference.
         * @return  the descriptor for the <code>view</code> reference
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.ide.metamodel.webdynpro.component.navigation.OutboundPlug,com.sap.ide.metamodel.webdynpro.component.view.AbstractView> VIEW( ) {
            if ( __view == null ) {
                __view = new com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.ide.metamodel.webdynpro.component.navigation.OutboundPlug,com.sap.ide.metamodel.webdynpro.component.view.AbstractView>( "45DDACEE9F60813FD59440F2114CF101F843EC5B", "sap.com/tc/moin/webdynpro", new java.lang.String[] { "WebDynpro", "component", "navigation", "OutboundPlug", "View" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ 
            }
            return __view;
        }
    }
}    