/**
 * Generated by the MOIN Generator Version 3.0
 **/

package behavioral.events;
/**
 * This interface is not intended to be implemented by clients.
 */
public interface ATestFilter extends com.sap.tc.moin.repository.mmi.reflect.RefAssociation
{
    // association extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<behavioral.events.ATestFilter> ASSOCIATION_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<behavioral.events.ATestFilter>("E0BC871351CA38293E4B11DEB76A0018DE1146FF", "sap.com/moin/mm/ap/core", "behavioral", "events", "A_test_filter"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 


    // association interface
    public boolean exists(behavioral.actions.Block _Test, behavioral.events.EventFilter _Filter) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public behavioral.actions.Block getTest(behavioral.events.EventFilter _Filter) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public behavioral.events.EventFilter getFilter(behavioral.actions.Block _Test) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean add(behavioral.actions.Block _Test, behavioral.events.EventFilter _Filter) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean remove(behavioral.actions.Block _Test, behavioral.events.EventFilter _Filter) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
}