<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="randomModelModifier"
    nsURI="http://de.hpi.sam.bp2009.benchframework.randomModelModifier" nsPrefix="benchframework.randomModelModifier">
  <eClassifiers xsi:type="ecore:EClass" name="RandomModelModifier" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//Operator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RandomNumberGenerator"
        eType="#//Random"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomModelModifierOptionObject" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//OptionObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="times" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="task" eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Task" instanceClassName="java.lang.string">
    <eLiterals name="classDelete" literal="classDelete"/>
    <eLiterals name="classCreate" value="1"/>
    <eLiterals name="referenceDelete" value="2"/>
    <eLiterals name="referenceCreate" value="3"/>
    <eLiterals name="modifyAttribute" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Random" instanceClassName="java.util.Random"/>
</ecore:EPackage>
