/**
* <copyright>
*
* Copyright (c) 2005, 2009 IBM Corporation, Zeligsoft Inc., Borland Software Corp., and others.
* All rights reserved.   This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
*   IBM - Initial API and implementation
*   E.D.Willink - Elimination of some shift-reduce conflicts
*   E.D.Willink - Remove unnecessary warning suppression
*   E.D.Willink - Bugs 225493, 243976, 259818
*   Zeligsoft - Bug 243976
*   Borland - Bug 242880
*   E.D.Willink - Bug 282882 resolve invalid confusion
*
* </copyright>
*
* $Id: OCLBacktrackingParsersym.java,v 1.4 2009/09/04 08:27:07 ewillink Exp $
*/

package org.eclipse.ocl.parser.backtracking;

/**
 * The backtracking variant of the OCL parser symbol table.
 * 
 * @noimplement This interface is not intended to be implemented by clients.
 * @noextend This interface is not intended to be extended by clients.
 * 
 * @since 1.3
 */
@SuppressWarnings("nls")
public interface OCLBacktrackingParsersym {
    public final static int
      TK_NUMERIC_OPERATION = 61,
      TK_STRING_LITERAL = 62,
      TK_INTEGER_LITERAL = 63,
      TK_REAL_LITERAL = 64,
      TK_PLUS = 28,
      TK_MINUS = 29,
      TK_MULTIPLY = 17,
      TK_DIVIDE = 18,
      TK_GREATER = 19,
      TK_LESS = 20,
      TK_EQUAL = 5,
      TK_GREATER_EQUAL = 21,
      TK_LESS_EQUAL = 22,
      TK_NOT_EQUAL = 7,
      TK_LPAREN = 2,
      TK_RPAREN = 3,
      TK_LBRACE = 94,
      TK_RBRACE = 75,
      TK_LBRACKET = 95,
      TK_RBRACKET = 80,
      TK_ARROW = 86,
      TK_BAR = 70,
      TK_COMMA = 31,
      TK_COLON = 32,
      TK_COLONCOLON = 81,
      TK_SEMICOLON = 82,
      TK_DOT = 87,
      TK_DOTDOT = 88,
      TK_ATPRE = 76,
      TK_CARET = 89,
      TK_CARETCARET = 90,
      TK_QUESTIONMARK = 96,
      TK_self = 30,
      TK_inv = 77,
      TK_pre = 71,
      TK_post = 72,
      TK_context = 78,
      TK_package = 97,
      TK_endpackage = 83,
      TK_def = 74,
      TK_if = 69,
      TK_then = 91,
      TK_else = 92,
      TK_endif = 85,
      TK_and = 25,
      TK_or = 26,
      TK_xor = 27,
      TK_not = 53,
      TK_implies = 93,
      TK_let = 68,
      TK_in = 84,
      TK_true = 65,
      TK_false = 66,
      TK_body = 6,
      TK_derive = 23,
      TK_init = 24,
      TK_null = 38,
      TK_invalid = 67,
      TK_attr = 99,
      TK_oper = 100,
      TK_static = 79,
      TK_Set = 33,
      TK_Bag = 34,
      TK_Sequence = 35,
      TK_Collection = 36,
      TK_OrderedSet = 37,
      TK_iterate = 39,
      TK_forAll = 40,
      TK_exists = 41,
      TK_isUnique = 42,
      TK_any = 43,
      TK_one = 44,
      TK_collect = 45,
      TK_select = 46,
      TK_reject = 47,
      TK_collectNested = 48,
      TK_sortedBy = 49,
      TK_closure = 50,
      TK_oclIsKindOf = 54,
      TK_oclIsTypeOf = 55,
      TK_oclAsType = 56,
      TK_oclIsNew = 57,
      TK_oclIsUndefined = 58,
      TK_oclIsInvalid = 59,
      TK_oclIsInState = 60,
      TK_allInstances = 51,
      TK_String = 8,
      TK_Integer = 9,
      TK_UnlimitedNatural = 10,
      TK_Real = 11,
      TK_Boolean = 12,
      TK_Tuple = 52,
      TK_OclAny = 13,
      TK_OclVoid = 14,
      TK_OclInvalid = 15,
      TK_OclMessage = 16,
      TK_EOF_TOKEN = 73,
      TK_IDENTIFIER = 4,
      TK_INTEGER_RANGE_START = 98,
      TK_SINGLE_LINE_COMMENT = 101,
      TK_MULTI_LINE_COMMENT = 102,
      TK_ERROR_TOKEN = 1;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "ERROR_TOKEN",
                 "LPAREN",
                 "RPAREN",
                 "IDENTIFIER",
                 "EQUAL",
                 "body",
                 "NOT_EQUAL",
                 "String",
                 "Integer",
                 "UnlimitedNatural",
                 "Real",
                 "Boolean",
                 "OclAny",
                 "OclVoid",
                 "OclInvalid",
                 "OclMessage",
                 "MULTIPLY",
                 "DIVIDE",
                 "GREATER",
                 "LESS",
                 "GREATER_EQUAL",
                 "LESS_EQUAL",
                 "derive",
                 "init",
                 "and",
                 "or",
                 "xor",
                 "PLUS",
                 "MINUS",
                 "self",
                 "COMMA",
                 "COLON",
                 "Set",
                 "Bag",
                 "Sequence",
                 "Collection",
                 "OrderedSet",
                 "null",
                 "iterate",
                 "forAll",
                 "exists",
                 "isUnique",
                 "any",
                 "one",
                 "collect",
                 "select",
                 "reject",
                 "collectNested",
                 "sortedBy",
                 "closure",
                 "allInstances",
                 "Tuple",
                 "not",
                 "oclIsKindOf",
                 "oclIsTypeOf",
                 "oclAsType",
                 "oclIsNew",
                 "oclIsUndefined",
                 "oclIsInvalid",
                 "oclIsInState",
                 "NUMERIC_OPERATION",
                 "STRING_LITERAL",
                 "INTEGER_LITERAL",
                 "REAL_LITERAL",
                 "true",
                 "false",
                 "invalid",
                 "let",
                 "if",
                 "BAR",
                 "pre",
                 "post",
                 "EOF_TOKEN",
                 "def",
                 "RBRACE",
                 "ATPRE",
                 "inv",
                 "context",
                 "static",
                 "RBRACKET",
                 "COLONCOLON",
                 "SEMICOLON",
                 "endpackage",
                 "in",
                 "endif",
                 "ARROW",
                 "DOT",
                 "DOTDOT",
                 "CARET",
                 "CARETCARET",
                 "then",
                 "else",
                 "implies",
                 "LBRACE",
                 "LBRACKET",
                 "QUESTIONMARK",
                 "package",
                 "INTEGER_RANGE_START",
                 "attr",
                 "oper",
                 "SINGLE_LINE_COMMENT",
                 "MULTI_LINE_COMMENT"
             };

    public final static boolean isValidForParser = true;
}
