/**
 * Generated by the MOIN Generator Version 3.0
 **/

package euml.generic.usecases.__impl;

public final class UmlactorUmlclassifierImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public UmlactorUmlclassifierImpl() {
        super();
    }

    // specific constructor
    public UmlactorUmlclassifierImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlactor, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ActorIsSystem) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _Umlactor, _ActorIsSystem);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlactor, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ActorIsSystem) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMult1( connection, _Umlactor, _ActorIsSystem, "498656FB32CD1321F0CF11DDC022000E35A783E4"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getUmlactor(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ActorIsSystem) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getUmlactor(get___CurrentConnection(), _ActorIsSystem);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getUmlactor(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ActorIsSystem) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        com.sap.tc.moin.repository.core.EndAndMetaObject endAndMetaObject = get___EndAndMetaObject( 1 );
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___queryElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _ActorIsSystem, endAndMetaObject );
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getActorIsSystem(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlactor) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getActorIsSystem(get___CurrentConnection(), _Umlactor);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getActorIsSystem(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlactor) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _Umlactor, "498656FB32CD1321F0CF11DDC022000E35A783E4"); //$NON-NLS-1$
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlactor, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ActorIsSystem) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Umlactor, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ActorIsSystem);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlactor, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ActorIsSystem) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Umlactor, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ActorIsSystem);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlactor, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ActorIsSystem) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Umlactor, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ActorIsSystem);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlactor, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ActorIsSystem) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Umlactor, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ActorIsSystem);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    @SuppressWarnings("unchecked")
    public java.lang.Class<euml.generic.usecases.UmlactorUmlclassifier> get___JmiInterface() {
        return euml.generic.usecases.UmlactorUmlclassifier.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<euml.generic.usecases.UmlactorUmlclassifier> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new euml.generic.usecases.__impl.UmlactorUmlclassifierWrapper(conn, this, synchronize);
    }
}