/**
 * Generated by the MOIN Generator Version 3.0
 **/

package euml.generic.usecases.__impl;

public final class UmluseCaseUmluseCaseImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public UmluseCaseUmluseCaseImpl() {
        super();
    }

    // specific constructor
    public UmluseCaseUmluseCaseImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlusecase, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheExtendedCase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _Umlusecase, _TheExtendedCase);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlusecase, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheExtendedCase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMultN( connection, _Umlusecase, _TheExtendedCase, "4986565BD3C9A642F0CE11DD9AA3000E35A783E4"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getUmlusecase(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheExtendedCase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getUmlusecase(get___CurrentConnection(), _TheExtendedCase);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getUmlusecase(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheExtendedCase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        com.sap.tc.moin.repository.core.EndAndMetaObject endAndMetaObject = get___EndAndMetaObject( 1 );
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___queryElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _TheExtendedCase, endAndMetaObject );
    }
    public java.util.List<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getTheExtendedCase(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlusecase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getTheExtendedCase(get___CurrentConnection(), _Umlusecase);
    }
    public java.util.List<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getTheExtendedCase(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlusecase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.List<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___getElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _Umlusecase, get___EndAndMetaObject( 0 ) );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlusecase, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheExtendedCase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Umlusecase, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheExtendedCase);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlusecase, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheExtendedCase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Umlusecase, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheExtendedCase);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlusecase, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheExtendedCase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_Umlusecase, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheExtendedCase);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Umlusecase, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _TheExtendedCase) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Umlusecase, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_TheExtendedCase);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    public java.lang.Class<euml.generic.usecases.UmluseCaseUmluseCase> get___JmiInterface() {
        return euml.generic.usecases.UmluseCaseUmluseCase.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<euml.generic.usecases.UmluseCaseUmluseCase> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new euml.generic.usecases.__impl.UmluseCaseUmluseCaseWrapper(conn, this, synchronize);
    }
}