/**
 * Generated by the MOIN Generator Version 3.0
 **/

package tcs;
/**
 * This interface is not intended to be implemented by clients.
 */
public interface BlockSequence extends com.sap.tc.moin.repository.mmi.reflect.RefAssociation
{
    // association extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<tcs.BlockSequence> ASSOCIATION_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<tcs.BlockSequence>("4843BB7633B07990308511DD81B1001742153E0C", "demo.sap.com/tcsmeta", "TCS", "Block_Sequence"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ 


    // association interface
    public boolean exists(tcs.Block _Block, tcs.Sequence _Sequence) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public tcs.Block getBlock(tcs.Sequence _Sequence) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public tcs.Sequence getSequence(tcs.Block _Block) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean add(tcs.Block _Block, tcs.Sequence _Sequence) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean remove(tcs.Block _Block, tcs.Sequence _Sequence) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
}