/**
 * Generated by the MOIN Generator Version 3.0
 **/

package tcs;

/**
 * This interface is not intended to be implemented by clients.
 */
public interface QualifiedNamedElement extends tcs.LocatedElement {

    /**
     * Descriptors for all features of this MofClass and its supertypes.
     */
    public static final Descriptors DESCRIPTORS = new Descriptors( );

    // class extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, tcs.QualifiedNamedElement> CLASS_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, tcs.QualifiedNamedElement>("483FE093F85A80F02E3811DDAAF7001742153E0C", "demo.sap.com/tcsmeta", "TCS", "QualifiedNamedElement"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ 

    
    // attributes
    public java.util.List<java.lang.String> getNames() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;

    // references
    public com.sap.tc.moin.repository.mmi.model.Classifier getMetaReference() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setMetaReference(com.sap.tc.moin.repository.mmi.model.Classifier newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;


    public static final class Descriptors {
        Descriptors( ) { 
        }
        /**
         * Returns the descriptor for the <code>location</code> attribute.
         * @return  the descriptor for the <code>location</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,tcs.LocatedElement,java.lang.String> LOCATION( ) {
            return tcs.LocatedElement.DESCRIPTORS.LOCATION( );
        }
        /**
         * Returns the descriptor for the <code>commentsBefore</code> attribute.
         * @return  the descriptor for the <code>commentsBefore</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,tcs.LocatedElement,java.util.List<java.lang.String>> COMMENTS_BEFORE( ) {
            return tcs.LocatedElement.DESCRIPTORS.COMMENTS_BEFORE( );
        }
        /**
         * Returns the descriptor for the <code>commentsAfter</code> attribute.
         * @return  the descriptor for the <code>commentsAfter</code> attribute
         */
        public com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,tcs.LocatedElement,java.util.List<java.lang.String>> COMMENTS_AFTER( ) {
            return tcs.LocatedElement.DESCRIPTORS.COMMENTS_AFTER( );
        }
        private com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,tcs.QualifiedNamedElement,java.util.List<java.lang.String>> __names;
        /**
         * Returns the descriptor for the <code>names</code> attribute.
         * @return  the descriptor for the <code>names</code> attribute
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,tcs.QualifiedNamedElement,java.util.List<java.lang.String>> NAMES( ) {
            if ( __names == null ) {
                __names = new com.sap.tc.moin.repository.mmi.descriptors.AttributeDescriptor<com.sap.tc.moin.repository.mmi.model.Attribute,tcs.QualifiedNamedElement,java.util.List<java.lang.String>>( "48400380C99927C02E4D11DD85BB001742153E0C", "demo.sap.com/tcsmeta", new java.lang.String[] { "TCS", "QualifiedNamedElement", "names" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __names;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,tcs.QualifiedNamedElement,com.sap.tc.moin.repository.mmi.model.Classifier> __metaReference;
        /**
         * Returns the descriptor for the <code>metaReference</code> reference.
         * @return  the descriptor for the <code>metaReference</code> reference
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,tcs.QualifiedNamedElement,com.sap.tc.moin.repository.mmi.model.Classifier> META_REFERENCE( ) {
            if ( __metaReference == null ) {
                __metaReference = new com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,tcs.QualifiedNamedElement,com.sap.tc.moin.repository.mmi.model.Classifier>( "48B5573C7AF68920743C11DDA054001742153E0C", "demo.sap.com/tcsmeta", new java.lang.String[] { "TCS", "QualifiedNamedElement", "metaReference" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 
            }
            return __metaReference;
        }
    }
}    