<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="essentialOCLCST"
    nsURI="http://www.eclipse.org/ocl/3.0.0/EssentialOCLCST" nsPrefix="essentialOCLCST">
  <eClassifiers xsi:type="ecore:EClass" name="ArrowCallArgumentsCS" eSuperTypes="#//CallArgumentsCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable1" eType="#//VariableCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable2" eType="#//VariableCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//OclExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpressionCS" eSuperTypes="#//OclExpressionCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//OclExpressionCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//OclExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallArgumentsCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathName" eType="#//PathNameCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//OclExpressionCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallExpCS" eSuperTypes="#//OclExpressionCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//OclExpressionCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callArguments" upperBound="-1"
        eType="#//CallArgumentsCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteralExpCS" eSuperTypes="#//LiteralExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteralPartCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressionCS" eType="#//OclExpressionCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastExpressionCS" eType="#//OclExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionTypeCS" eSuperTypes="#//TypeCS #//CollectionLiteralExpCS #//TypeLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SimpleNameCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeCS" eType="#//TypeCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionLiteralParts"
        upperBound="-1" eType="#//CollectionLiteralPartCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DotIndexArgumentsCS" eSuperTypes="#//CallArgumentsCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//OclExpressionCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfExpCS" eSuperTypes="#//OclExpressionCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//OclExpressionCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" eType="#//OclExpressionCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" eType="#//OclExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="LetExpCS" eSuperTypes="#//OclExpressionCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//VariableCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" eType="#//OclExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExpCS" eSuperTypes="#//OclExpressionCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="NullLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclExpressionCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="PathNameCS" eSuperTypes="#//TypeCS #//TypeLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="simpleNames" upperBound="-1"
        eType="#//SimpleNameCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveLiteralExpCS" eSuperTypes="#//LiteralExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleNameCS" eSuperTypes="#//TypeCS #//CollectionLiteralExpCS #//TypeLiteralExpCS #//VariableExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionLiteralParts"
        upperBound="-1" eType="#//CollectionLiteralPartCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringSymbol" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleLiteralExpCS" eSuperTypes="#//LiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1" eType="#//VariableCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleTypeCS" eSuperTypes="#//TypeCS #//TypeLiteralExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1" eType="#//VariableCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeLiteralExpCS" eSuperTypes="#//LiteralExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpressionCS" eSuperTypes="#//OclExpressionCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//OclExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnlimitedNaturalLiteralExpCS" eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//SimpleNameCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="#//OclExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableExpCS" eSuperTypes="#//OclExpressionCS"/>
</ecore:EPackage>
