/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.framework.uielib.__impl;

public final class AExtendedInterfacesMarkerInterfaceImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public AExtendedInterfacesMarkerInterfaceImpl() {
        super();
    }

    // specific constructor
    public AExtendedInterfacesMarkerInterfaceImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ExtendedInterfaces, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _MarkerInterface) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _ExtendedInterfaces, _MarkerInterface);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ExtendedInterfaces, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _MarkerInterface) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMultN( connection, _MarkerInterface, _ExtendedInterfaces, "45DDACEF1856A43D47004FFF2D018F9E0D0749BE"); //$NON-NLS-1$
    }
    public java.util.List<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getExtendedInterfaces(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _MarkerInterface) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getExtendedInterfaces(get___CurrentConnection(), _MarkerInterface);
    }
    public java.util.List<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getExtendedInterfaces(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _MarkerInterface) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.List<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___getElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _MarkerInterface, get___EndAndMetaObject( 1 ) );
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getMarkerInterface(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ExtendedInterfaces) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getMarkerInterface(get___CurrentConnection(), _ExtendedInterfaces);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getMarkerInterface(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ExtendedInterfaces) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___queryElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _ExtendedInterfaces, get___EndAndMetaObject( 0 ) );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ExtendedInterfaces, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _MarkerInterface) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_ExtendedInterfaces, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_MarkerInterface);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ExtendedInterfaces, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _MarkerInterface) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ExtendedInterfaces, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_MarkerInterface);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ExtendedInterfaces, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _MarkerInterface) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_ExtendedInterfaces, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_MarkerInterface);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ExtendedInterfaces, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _MarkerInterface) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ExtendedInterfaces, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_MarkerInterface);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.webdynpro.framework.uielib.AExtendedInterfacesMarkerInterface> get___JmiInterface() {
        return com.sap.ide.metamodel.webdynpro.framework.uielib.AExtendedInterfacesMarkerInterface.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<com.sap.ide.metamodel.webdynpro.framework.uielib.AExtendedInterfacesMarkerInterface> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new com.sap.ide.metamodel.webdynpro.framework.uielib.__impl.AExtendedInterfacesMarkerInterfaceWrapper(conn, this, synchronize);
    }
}