/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.tc.moin.testcases.case002.__impl;

public class A2Wrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefObjectWrapperImpl<com.sap.tc.moin.testcases.case002.__impl.A2Impl> implements com.sap.tc.moin.testcases.case002.A2,com.sap.tc.moin.repository.Partitionable {

    
    static {
    }

    public A2Wrapper(com.sap.tc.moin.repository.core.CoreConnection conn, com.sap.tc.moin.testcases.case002.__impl.A2Impl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }

    private com.sap.tc.moin.testcases.case002.__impl.A2Impl getCastWrappedObject() {
        return (com.sap.tc.moin.testcases.case002.__impl.A2Impl) getWrappedObject();
    }
    
    public com.sap.tc.moin.testcases.case002.__impl.A2Impl unwrap() {
        return (com.sap.tc.moin.testcases.case002.__impl.A2Impl) getWrappedObject();
    }
        
    // methods for attributes
     
    // methods for references
   
    // methods for modeled operations
    
    // methods for internal modeled operations

    // reflective methods
    

    // get the JMI interface
    public java.lang.Class<com.sap.tc.moin.testcases.case002.A2> get___JmiInterface() {
        return com.sap.tc.moin.testcases.case002.A2.class;
    }

    // to String
    protected String metaObjectToString() {
        return "com.sap.tc.moin.testcases.case002.A2 (Java Type)\ntestcases.case002.A2 (MOF Type)"; //$NON-NLS-1$
    }    
}