/**
 * Generated by the MOIN Generator Version 3.0
 **/

package uml;
/**
 * This interface is not intended to be implemented by clients.
 */
public interface ClassifierFeature extends com.sap.tc.moin.repository.mmi.reflect.RefAssociation
{
    // association extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<uml.ClassifierFeature> ASSOCIATION_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<uml.ClassifierFeature>("49868DF7F8F97190F0EF11DD81A1000E35A783E4", "sap.com/moin/mm/euml", "uml", "Classifier_Feature"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ 


    // association interface
    public boolean exists(uml.Classifier _FeaturingClassifier, uml.Feature _Feature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.Collection<uml.Classifier> getFeaturingClassifier(uml.Feature _Feature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.Collection<uml.Feature> getFeature(uml.Classifier _FeaturingClassifier) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean add(uml.Classifier _FeaturingClassifier, uml.Feature _Feature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean remove(uml.Classifier _FeaturingClassifier, uml.Feature _Feature) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
}