/**
 * Generated by the MOIN Generator Version 3.0
 **/

package uml;
/**
 * This interface is not intended to be implemented by clients.
 */
public interface GeneralizationGeneralizationSet extends com.sap.tc.moin.repository.mmi.reflect.RefAssociation
{
    // association extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<uml.GeneralizationGeneralizationSet> ASSOCIATION_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<uml.GeneralizationGeneralizationSet>("498695082F0499A0F0F411DD9931000E35A783E4", "sap.com/moin/mm/euml", "uml", "Generalization_GeneralizationSet"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ 


    // association interface
    public boolean exists(uml.Generalization _Generalization, uml.GeneralizationSet _Generalizationset) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.Collection<uml.Generalization> getGeneralization(uml.GeneralizationSet _Generalizationset) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.Collection<uml.GeneralizationSet> getGeneralizationset(uml.Generalization _Generalization) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean add(uml.Generalization _Generalization, uml.GeneralizationSet _Generalizationset) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean remove(uml.Generalization _Generalization, uml.GeneralizationSet _Generalizationset) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
}