/**
 * Generated by the MOIN Generator Version 3.0
 **/

package uml;
/**
 * This interface is not intended to be implemented by clients.
 */
public interface OpaqueExpressionParameter extends com.sap.tc.moin.repository.mmi.reflect.RefAssociation
{
    // association extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<uml.OpaqueExpressionParameter> ASSOCIATION_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<uml.OpaqueExpressionParameter>("498698C368AB9800F0F611DD84FD000E35A783E4", "sap.com/moin/mm/euml", "uml", "OpaqueExpression_Parameter"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ 


    // association interface
    public boolean exists(uml.OpaqueExpression _Opaqueexpression, uml.Parameter _Result) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public uml.OpaqueExpression getOpaqueexpression(uml.Parameter _Result) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public uml.Parameter getResult(uml.OpaqueExpression _Opaqueexpression) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
}