
Options in effect for C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/OCLLexer.gi:

    ACTION-BLOCK=("C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/OCLLexer.java","/.","./")

    AST-DIRECTORY=""  AST-TYPE="Ast"  NOATTRIBUTES  NOAUTOMATIC-AST  NOBACKTRACK
    BYTE  CONFLICTS  
    DAT-DIRECTORY="C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/"
    
    DAT-FILE="C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/OCLLexerdcl.data"
    
    DCL-FILE="C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/OCLLexerdcl.java"
    NODEBUG  
    DEF-FILE="C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/OCLLexerdef.java"
    NOEDIT  NOERROR-MAPS  ESCAPE='$'  
    EXPORT-TERMINALS=("C:\Development\HartLibrary\Workspace3.5.1\org.eclipse.ocl.examples.xtext.essentialocl\src\org\eclipse\ocl\examples\xtext\essentialocl\parser\OCLParsersym.java","TK_","")
    EXTENDS-PARSETABLE  FACTORY="new "  FILE-PREFIX="OCLLexer"  
    FILTER="OCLKWLexer.gi"  NOFIRST  NOFOLLOW  NOGLR  NOGOTO-DEFAULT  
    GRM-FILE="C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/OCLLexer.gi"
    
    IMP-FILE="C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/OCLLexerimp.java"
    INCLUDE-DIRECTORY=".;../lpg"  LALR=2  LEGACY  NOLIST  MARGIN=4  
    MAX-CASES=1024  NAMES=OPTIMIZED  NONT-CHECK  OR_MARKER='|'  
    OUT-DIRECTORY="C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/"
    PACKAGE="org.eclipse.ocl.examples.xtext.essentialocl.parser"  NOPARENT-SAVE
    PARSETABLE-INTERFACES="lpg.runtime.ParseTable"  PREFIX="Char_"  PRIORITY  
    PROGRAMMING_LANGUAGE=JAVA  
    PRS-FILE="C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/OCLLexerprs.java"
    NOQUIET  READ-REDUCE  REMAP-TERMINALS  NOSCOPES  NOSERIALIZE  
    NOSHIFT-DEFAULT  SINGLE-PRODUCTIONS  NOSOFT-KEYWORDS  NOSTATES  SUFFIX=""  
    SYM-FILE="C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/OCLLexersym.java"
    TAB-FILE="OCLLexer.t"  TABLE  TEMPLATE="../lpg/LexerTemplateF.gi"  
    TRACE=CONFLICTS  NOVARIABLES  NOVERBOSE  NOVISITOR  VISITOR-TYPE="Visitor"
    WARNINGS  NOXREF  

C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/EssentialOCLLexer.gi:108:4:108:6:3229:3231: Warning: The macro "$Id" is undefined. No substitution made
C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/EssentialOCLLexer.gi:108:73:108:73:3298:3298: Warning: The macro "$" is undefined. No substitution made
C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/../lpg/LexerTemplateF.gi:82:20:82:33:2776:2789: Warning: The macro "$case" is undefined. No substitution made


C:/Development/HartLibrary/Workspace3.5.1/org.eclipse.ocl.examples.xtext.essentialocl/src/org/eclipse/ocl/examples/xtext/essentialocl/parser/EssentialOCLLexer.gi:220:9:220:13:5115:5119: Informative: Grammar is  LALR(2).

Number of Terminals: 103
Number of Nonterminals: 34
Number of Productions: 269
Number of Single Productions: 202
Number of Items: 584
Number of States: 43
Number of look-ahead states: 1
Number of Shift actions: 617
Number of Goto actions: 73
Number of Shift/Reduce actions: 729
Number of Goto/Reduce actions: 60
Number of Reduce actions: 377
Number of Shift-Reduce conflicts: 0
Number of Reduce-Reduce conflicts: 0

Number of entries in base Action Table: 176
Additional space required for compaction of Action Table: 6.8%

Number of unique terminal states: 42
Number of Shift actions saved by merging: 190
Number of Conflict points saved by merging: 0
Number of Reduce actions saved by merging: 1
Number of Reduce saved by default: 369

Number of entries in Terminal Action Table: 1206
Additional space required for compaction of Terminal Table: 8.7%

Actions in Compressed Tables:
     Number of Shifts: 427
     Number of Shift/Reduces: 729
     Number of Look-Ahead Shifts: 1
     Number of Gotos: 73
     Number of Goto/Reduces: 60
     Number of Reduces: 7
     Number of Defaults: 27

Parsing Tables storage:
    Storage required for BASE_CHECK: 269 Bytes
    Storage required for BASE_ACTION: 916 Bytes
    Storage required for TERM_CHECK: 1316 Bytes
    Storage required for TERM_ACTION: 2624 Bytes
