<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Reflect"
    nsURI="http://sap.com/moin/Reflect" nsPrefix="reflect">
  <eAnnotations source="http://sap.com/MOIN">
    <details key="Reflect.Element" value="//Element"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/tc/moin/mof_1.4[1.0]"/>
      <details key="metaObject" value="Reflect.Element"/>
      <details key="metaObjectMofId" value="45ED2E29000DEAF733A545E62844AF3FC5E44767"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
