<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EUML"
    nsURI="http:///EUML.ecore" nsPrefix="EUML">
  <eSubpackages name="Presentation" nsURI="http:///EUML/Presentation.ecore" nsPrefix="EUML.Presentation">
    <eSubpackages name="Graphic" nsURI="http:///EUML/Presentation/Graphic.ecore" nsPrefix="EUML.Presentation.Graphic">
      <eClassifiers xsi:type="ecore:EClass" name="Canvas" abstract="true" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="theObjectOnDiagram"
            ordered="false" upperBound="-1" eType="#//Presentation/Graphic/Representative"
            containment="true" eOpposite="#//Presentation/Graphic/Representative/theDiagram"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Representative" abstract="true"
          eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="theRepresentedElement"
            ordered="false" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/theRepresentative"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypeIsVisible"
            ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="zOrder" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theDiagram" ordered="false"
            lowerBound="1" eType="#//Presentation/Graphic/Canvas" eOpposite="#//Presentation/Graphic/Canvas/theObjectOnDiagram"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//Generic/Kernel/UMLNamedElement #//Presentation/Graphic/Canvas">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="showPublic" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="showProtected" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="showPrivate" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="xDimension" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="yDimension" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlightImports" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="showPackageContents"
            ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendedStyle" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocked" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="notes" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DiagramConnector" eSuperTypes="#//Presentation/Graphic/Representative">
        <eStructuralFeatures xsi:type="ecore:EReference" name="theDiagramObjects"
            upperBound="-1" eType="#//Presentation/Graphic/DiagramElement" eOpposite="#//Presentation/Graphic/DiagramElement/theConnectors"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="geometry" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHidden" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeStyle" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DiagramElement" eSuperTypes="#//Presentation/Graphic/Representative">
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_regions" ordered="false"
            eType="#//Presentation/Graphic/InvisibleRegion" containment="true" eOpposite="#//Presentation/Graphic/InvisibleRegion/the_element"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="top" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottom" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theConnectors" ordered="false"
            upperBound="-1" eType="#//Presentation/Graphic/DiagramConnector" eOpposite="#//Presentation/Graphic/DiagramConnector/theDiagramObjects"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InvisibleRegion" eSuperTypes="#//Presentation/Graphic/Canvas">
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_element" ordered="false"
            lowerBound="1" eType="#//Presentation/Graphic/DiagramElement" eOpposite="#//Presentation/Graphic/DiagramElement/the_regions"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Generic" nsURI="http:///EUML/Generic.ecore" nsPrefix="EUML.Generic">
    <eSubpackages name="Relationships" nsURI="http:///EUML/Generic/Relationships.ecore" nsPrefix="EUML.Generic.Relationships">
      <eClassifiers xsi:type="ecore:EEnum" name="DirectedRelationshipKind">
        <eLiterals name="DEPENDENCY_KIND"/>
        <eLiterals name="REALIZE_KIND" value="1"/>
        <eLiterals name="USES_KIND" value="2"/>
        <eLiterals name="ABSTRACTION_KIND" value="3"/>
        <eLiterals name="PERMISSION_KIND" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLDirectedRelationship" eSuperTypes="#//Generic/Relationships/UMLRelationship">
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_target_element"
            ordered="false" lowerBound="1" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/the_relationship_of_target"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_source_element"
            ordered="false" lowerBound="1" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/the_relationship_of_source"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false"
            unique="false" lowerBound="1" eType="#//Generic/Relationships/DirectedRelationshipKind"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLRelationship" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_related_elements"
            upperBound="-1" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/relationships"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLGeneralization" eSuperTypes="#//Generic/Relationships/UMLDirectedRelationship">
        <eOperations name="getgeneral" ordered="false" unique="false" lowerBound="1"
            eType="#//Generic/Kernel/UMLClassifier"/>
        <eOperations name="getspecific" ordered="false" unique="false" lowerBound="1"
            eType="#//Generic/Kernel/UMLClassifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLTrace" eSuperTypes="#//Generic/Relationships/UMLRelationship">
        <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/targetTrace"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sourceElement" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/sourceTrace"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="CommonBehaviors" nsURI="http:///EUML/Generic/CommonBehaviors.ecore"
        nsPrefix="EUML.Generic.CommonBehaviors">
      <eClassifiers xsi:type="ecore:EClass" name="UMLBehavioralFeature" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLFeature">
        <eStructuralFeatures xsi:type="ecore:EReference" name="method" upperBound="-1"
            eType="#//Generic/CommonBehaviors/UMLBehavior" eOpposite="#//Generic/CommonBehaviors/UMLBehavior/specification"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLCallEvent" eSuperTypes="#//Generic/CommonBehaviors/UMLMessageEvent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLOperation"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLMessageEvent" abstract="true"
          eSuperTypes="#//Generic/CommonBehaviors/UMLEvent"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLEvent" abstract="true" eSuperTypes="#//Generic/Kernel/UMLNamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLReception" eSuperTypes="#//Generic/CommonBehaviors/UMLBehavioralFeature">
        <eStructuralFeatures xsi:type="ecore:EReference" name="signal" ordered="false"
            eType="#//Generic/CommonBehaviors/UMLSignal"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLSignal" eSuperTypes="#//Generic/Kernel/UMLClassifier">
        <eOperations name="getownedProperties" upperBound="-1" eType="#//Generic/Kernel/UMLProperty"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLSignalEvent" eSuperTypes="#//Generic/CommonBehaviors/UMLMessageEvent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="signal" ordered="false"
            lowerBound="1" eType="#//Generic/CommonBehaviors/UMLSignal"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLTimeEvent" eSuperTypes="#//Generic/CommonBehaviors/UMLEvent">
        <eOperations name="getwhen" ordered="false" unique="false" lowerBound="1"
            eType="#//Generic/Kernel/UMLValueSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRelative" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLTrigger" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="event" ordered="false"
            lowerBound="1" eType="#//Generic/CommonBehaviors/UMLEvent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLBehavior" abstract="true" eSuperTypes="#//Generic/Kernel/UMLClass">
        <eOperations name="getownedParameters" upperBound="-1" eType="#//Generic/Kernel/UMLParameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="specification" ordered="false"
            eType="#//Generic/CommonBehaviors/UMLBehavioralFeature" eOpposite="#//Generic/CommonBehaviors/UMLBehavioralFeature/method"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theBehavioredClassifier"
            ordered="false" eType="#//Generic/Kernel/UMLClassifier" eOpposite="#//Generic/Kernel/UMLClassifier/theClassifierBehavior"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="CompositeStructures" nsURI="http:///EUML/Generic/CompositeStructures.ecore"
        nsPrefix="EUML.Generic.CompositeStructures">
      <eClassifiers xsi:type="ecore:EClass" name="PortUsage" eSuperTypes="#//Generic/CompositeStructures/UMLConnectableElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="represents" ordered="false"
            lowerBound="1" eType="#//Generic/CompositeStructures/UMLPort" eOpposite="#//Generic/CompositeStructures/UMLPort/representedBy"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLPort" eSuperTypes="#//Generic/Kernel/UMLProperty #//Generic/CompositeStructures/UMLConnectableElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="required" ordered="false"
            upperBound="-1" eType="#//Generic/Kernel/UMLInterface"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="provided" ordered="false"
            upperBound="-1" eType="#//Generic/Kernel/UMLInterface"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isService" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBehavior" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="representedBy" upperBound="-1"
            eType="#//Generic/CompositeStructures/PortUsage" eOpposite="#//Generic/CompositeStructures/PortUsage/represents"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLCollaboration" eSuperTypes="#//Generic/CompositeStructures/UMLStructuredClassifier"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLStructuredClassifier" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLClassifier">
        <eOperations name="getownedPorts" upperBound="-1" eType="#//Generic/CompositeStructures/UMLPort"/>
        <eOperations name="getownedConnectors" upperBound="-1" eType="#//Generic/CompositeStructures/UMLConnector"/>
        <eOperations name="getownedProperties" upperBound="-1" eType="#//Generic/Kernel/UMLProperty"/>
        <eOperations name="getparts" upperBound="-1" eType="#//Generic/CompositeStructures/UMLPart"/>
        <eOperations name="getportUsages" upperBound="-1" eType="#//Generic/CompositeStructures/PortUsage"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLConnector" eSuperTypes="#//Generic/Kernel/UMLFeature">
        <eStructuralFeatures xsi:type="ecore:EReference" name="theConnectorEnd" lowerBound="2"
            upperBound="-1" eType="#//Generic/CompositeStructures/UMLConnectorEnd"
            containment="true" eOpposite="#//Generic/CompositeStructures/UMLConnectorEnd/theConnector"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLConnectorEnd" eSuperTypes="#//Generic/Kernel/UMLMultiplicityElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="role" ordered="false"
            lowerBound="1" eType="#//Generic/CompositeStructures/UMLConnectableElement"
            eOpposite="#//Generic/CompositeStructures/UMLConnectableElement/end"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theConnector" ordered="false"
            lowerBound="1" eType="#//Generic/CompositeStructures/UMLConnector" eOpposite="#//Generic/CompositeStructures/UMLConnector/theConnectorEnd"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLPart" eSuperTypes="#//Generic/Kernel/UMLProperty #//Generic/CompositeStructures/UMLConnectableElement">
        <eOperations name="getportUsages" upperBound="-1" eType="#//Generic/CompositeStructures/PortUsage"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLCollaborationUse" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_type" ordered="false"
            lowerBound="1" eType="#//Generic/CompositeStructures/UMLCollaboration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="roleBinding" upperBound="-1"
            eType="#//Generic/Relationships/UMLDirectedRelationship" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLConnectableElement" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLTypedElement #//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="end" upperBound="-1"
            eType="#//Generic/CompositeStructures/UMLConnectorEnd" eOpposite="#//Generic/CompositeStructures/UMLConnectorEnd/role"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Activities" nsURI="http:///EUML/Generic/Activities.ecore" nsPrefix="EUML.Generic.Activities">
      <eClassifiers xsi:type="ecore:EClass" name="ClassifierPin" eSuperTypes="#//Generic/Activities/UMLInputPin"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInputPin" eSuperTypes="#//Generic/Activities/UMLPin"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLPin" abstract="true" eSuperTypes="#//Generic/Activities/UMLObjectNode #//Generic/Kernel/UMLMultiplicityElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="ConnectableElementPin" eSuperTypes="#//Generic/Activities/UMLInputPin">
        <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" ordered="false"
            eType="#//Generic/CompositeStructures/UMLConnectableElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceUsage" eSuperTypes="#//Generic/Activities/UMLObjectNode"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLAction" eSuperTypes="#//Generic/Activities/UMLActivityNode">
        <eOperations name="getinput" upperBound="-1" eType="#//Generic/Activities/UMLInputPin"/>
        <eOperations name="getoutput" upperBound="-1" eType="#//Generic/Activities/UMLOutputPin"/>
        <eOperations name="getownedHandlers" ordered="false" unique="false" upperBound="-1"
            eType="#//Generic/Activities/UMLExceptionHandler"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLActivityNode" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="theIncomingEdge" upperBound="-1"
            eType="#//Generic/Activities/UMLActivityEdge" eOpposite="#//Generic/Activities/UMLActivityEdge/theNodeOfTheIncomingEdge"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theGroupOfTheNode"
            ordered="false" eType="#//Generic/Activities/UMLActivityGroup" eOpposite="#//Generic/Activities/UMLActivityGroup/theNodeOfTheGroup"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theOutgoingEdge" upperBound="-1"
            eType="#//Generic/Activities/UMLActivityEdge" eOpposite="#//Generic/Activities/UMLActivityEdge/theNodeOfTheOutgoingEdge"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLActivityEdge" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="theGroupOfTheEdge"
            ordered="false" eType="#//Generic/Activities/UMLActivityGroup" eOpposite="#//Generic/Activities/UMLActivityGroup/theEdgesOfTheGroup"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="interrupts" ordered="false"
            eType="#//Generic/Activities/UMLInterruptibleActivityRegion" eOpposite="#//Generic/Activities/UMLInterruptibleActivityRegion/interrupting_edges"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theNodeOfTheOutgoingEdge"
            ordered="false" eType="#//Generic/Activities/UMLActivityNode" eOpposite="#//Generic/Activities/UMLActivityNode/theOutgoingEdge"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="guardCondition" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theNodeOfTheIncomingEdge"
            ordered="false" eType="#//Generic/Activities/UMLActivityNode" eOpposite="#//Generic/Activities/UMLActivityNode/theIncomingEdge"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLActivityGroup" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLElement">
        <eOperations name="getownedGroups" upperBound="-1" eType="#//Generic/Activities/UMLActivityGroup"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theNodeOfTheGroup"
            upperBound="-1" eType="#//Generic/Activities/UMLActivityNode" eOpposite="#//Generic/Activities/UMLActivityNode/theGroupOfTheNode"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theEdgesOfTheGroup"
            upperBound="-1" eType="#//Generic/Activities/UMLActivityEdge" eOpposite="#//Generic/Activities/UMLActivityEdge/theGroupOfTheEdge"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInterruptibleActivityRegion"
          eSuperTypes="#//Generic/Activities/UMLActivityGroup">
        <eStructuralFeatures xsi:type="ecore:EReference" name="interrupting_edges"
            upperBound="-1" eType="#//Generic/Activities/UMLActivityEdge" eOpposite="#//Generic/Activities/UMLActivityEdge/interrupts"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLOutputPin" eSuperTypes="#//Generic/Activities/UMLPin"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLExceptionHandler" eSuperTypes="#//Generic/Kernel/UMLElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="handlerBody" ordered="false"
            lowerBound="1" eType="#//Generic/Activities/UMLAction"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionInput" ordered="false"
            lowerBound="1" eType="#//Generic/Activities/UMLObjectNode"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionType" ordered="false"
            lowerBound="1" upperBound="-1" eType="#//Generic/Kernel/UMLClassifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLActivity" eSuperTypes="#//Generic/CommonBehaviors/UMLBehavior">
        <eOperations name="getedges" upperBound="-1" eType="#//Generic/Activities/UMLActivityEdge"/>
        <eOperations name="getnodes" upperBound="-1" eType="#//Generic/Activities/UMLActivityNode"/>
        <eOperations name="getgroups" upperBound="-1" eType="#//Generic/Activities/UMLActivityGroup"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSingleExecution"
            ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLActivityParameterNode" eSuperTypes="#//Generic/Activities/UMLObjectNode">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLParameter"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLActivityPartition" eSuperTypes="#//Generic/Kernel/UMLNamedElement #//Generic/Activities/UMLActivityGroup">
        <eOperations name="getowned_partitions" upperBound="-1" eType="#//Generic/Activities/UMLActivityPartition"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="representsElement"
            ordered="false" unique="false" eType="#//Generic/Kernel/UMLNamedElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLControlFlow" eSuperTypes="#//Generic/Activities/UMLActivityEdge"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLControlNode" abstract="true"
          eSuperTypes="#//Generic/Activities/UMLActivityNode"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLDataStoreNode" eSuperTypes="#//Generic/Activities/UMLObjectNode"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLDecisionMergeNode" eSuperTypes="#//Generic/Activities/UMLControlNode">
        <eStructuralFeatures xsi:type="ecore:EReference" name="decisionInput" ordered="false"
            unique="false" eType="#//Generic/CommonBehaviors/UMLBehavior"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLFinalNode" eSuperTypes="#//Generic/Activities/UMLControlNode">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="finalNodeKind" ordered="false"
            unique="false" lowerBound="1" eType="#//Generic/Activities/UMLFinalNodeKind"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="UMLFinalNodeKind">
        <eLiterals name="FINAL_ACTIVITY_NODE"/>
        <eLiterals name="FINAL_FLOW_NODE" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLForkJoinNode" eSuperTypes="#//Generic/Activities/UMLControlNode"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInitialNode" eSuperTypes="#//Generic/Activities/UMLControlNode"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLObjectFlow" eSuperTypes="#//Generic/Activities/UMLActivityEdge"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLStructuredActivityNode" eSuperTypes="#//Generic/Activities/UMLAction #//Generic/Kernel/UMLNamespace #//Generic/Activities/UMLActivityGroup">
        <eOperations name="getownedActivityNodes" upperBound="-1" eType="#//Generic/Activities/UMLActivityNode"/>
        <eOperations name="getownedActivityEdges" upperBound="-1" eType="#//Generic/Activities/UMLActivityEdge"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mustIsolate" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLObjectNode" abstract="true" eSuperTypes="#//Generic/Activities/UMLActivityNode #//Generic/Kernel/UMLTypedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="allocationScheme" ordered="false"
            eType="#//Generic/Kernel/UMLValueSpecification" eOpposite="#//Generic/Kernel/UMLValueSpecification/allocatedBy"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="UseCases" nsURI="http:///EUML/Generic/UseCases.ecore" nsPrefix="EUML.Generic.UseCases">
      <eClassifiers xsi:type="ecore:EClass" name="UMLActor" eSuperTypes="#//Generic/Kernel/UMLClassifier">
        <eStructuralFeatures xsi:type="ecore:EReference" name="actorIsSystem" ordered="false"
            unique="false" eType="#//Generic/Kernel/UMLClassifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLUseCase" eSuperTypes="#//Generic/Kernel/UMLClassifier">
        <eStructuralFeatures xsi:type="ecore:EReference" name="theExtendedCase" upperBound="-1"
            eType="#//Generic/UseCases/UMLUseCase"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theIncludedUseCase"
            upperBound="-1" eType="#//Generic/UseCases/UMLUseCase"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theSubject" ordered="false"
            upperBound="-1" eType="#//Generic/Kernel/UMLClassifier" eOpposite="#//Generic/Kernel/UMLClassifier/theUseCases"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Actions" nsURI="http:///EUML/Generic/Actions.ecore" nsPrefix="EUML.Generic.Actions">
      <eClassifiers xsi:type="ecore:EClass" name="UMLAcceptCallAction" eSuperTypes="#//Generic/Actions/UMLAcceptEventAction">
        <eOperations name="getreturnInformation" ordered="false" unique="false" lowerBound="1"
            eType="#//Generic/Activities/UMLOutputPin"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLAcceptEventAction" eSuperTypes="#//Generic/Activities/UMLAction">
        <eOperations name="getresult" upperBound="-1" eType="#//Generic/Activities/UMLOutputPin"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" ordered="false"
            lowerBound="1" upperBound="-1" eType="#//Generic/CommonBehaviors/UMLTrigger"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLCallAction" abstract="true" eSuperTypes="#//Generic/Actions/UMLInvocationAction">
        <eOperations name="getresult" upperBound="-1" eType="#//Generic/Activities/UMLOutputPin"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSynchronous" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInvocationAction" abstract="true"
          eSuperTypes="#//Generic/Activities/UMLAction">
        <eOperations name="getargument" upperBound="-1" eType="#//Generic/Activities/UMLInputPin"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLCallOperationAction" eSuperTypes="#//Generic/Actions/UMLCallAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLOperation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
            lowerBound="1" eType="#//Generic/Activities/UMLInputPin"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLReplyAction" eSuperTypes="#//Generic/Activities/UMLAction">
        <eOperations name="getreturnInformation" ordered="false" unique="false" lowerBound="1"
            eType="#//Generic/Activities/UMLInputPin"/>
        <eOperations name="getreplyValue" upperBound="-1" eType="#//Generic/Activities/UMLInputPin"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="replyToCall" ordered="false"
            lowerBound="1" eType="#//Generic/CommonBehaviors/UMLCallEvent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLSendSignalAction" eSuperTypes="#//Generic/Actions/UMLInvocationAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
            lowerBound="1" eType="#//Generic/Activities/UMLInputPin"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="signal" ordered="false"
            lowerBound="1" eType="#//Generic/CommonBehaviors/UMLSignal"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Components" nsURI="http:///EUML/Generic/Components.ecore"
        nsPrefix="EUML.Generic.Components">
      <eClassifiers xsi:type="ecore:EClass" name="UMLComponent" eSuperTypes="#//Generic/Kernel/UMLClass">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isExternal" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Interactions" nsURI="http:///EUML/Generic/Interactions.ecore"
        nsPrefix="EUML.Generic.Interactions">
      <eClassifiers xsi:type="ecore:EClass" name="UMLActionExecutionSpecification"
          eSuperTypes="#//Generic/Interactions/UMLExecutionSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="executingAction" ordered="false"
            lowerBound="1" eType="#//Generic/Activities/UMLAction"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLExecutionSpecification" abstract="true"
          eSuperTypes="#//Generic/Interactions/UMLInteractionFragment">
        <eStructuralFeatures xsi:type="ecore:EReference" name="start" ordered="false"
            lowerBound="1" eType="#//Generic/Interactions/UMLOccurrenceSpecification"
            eOpposite="#//Generic/Interactions/UMLOccurrenceSpecification/startExecution"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="finish" ordered="false"
            lowerBound="1" eType="#//Generic/Interactions/UMLOccurrenceSpecification"
            eOpposite="#//Generic/Interactions/UMLOccurrenceSpecification/finishExecution"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInteractionFragment" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eOperations name="getgeneralOrdering" ordered="false" unique="false" upperBound="-1"
            eType="#//Generic/Interactions/UMLGeneralOrdering"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="covered" ordered="false"
            upperBound="-1" eType="#//Generic/Interactions/UMLLifeline" eOpposite="#//Generic/Interactions/UMLLifeline/coveredBy"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLLifeline" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="represents" ordered="false"
            eType="#//Generic/CompositeStructures/UMLConnectableElement"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="decomposedAs" ordered="false"
            eType="#//Generic/Interactions/UMLPartDecomposition"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="coveredBy" ordered="false"
            upperBound="-1" eType="#//Generic/Interactions/UMLInteractionFragment"
            eOpposite="#//Generic/Interactions/UMLInteractionFragment/covered"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLPartDecomposition" eSuperTypes="#//Generic/Interactions/UMLInteractionUse"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInteractionUse" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="refersTo" ordered="false"
            lowerBound="1" eType="#//Generic/Interactions/UMLInteraction"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInteraction" eSuperTypes="#//Generic/CommonBehaviors/UMLBehavior #//Generic/Interactions/UMLInteractionFragment">
        <eOperations name="getlifeline" upperBound="-1" eType="#//Generic/Interactions/UMLLifeline"/>
        <eOperations name="getfragment" upperBound="-1" eType="#//Generic/Interactions/UMLInteractionFragment"/>
        <eOperations name="getmessage" upperBound="-1" eType="#//Generic/Interactions/UMLMessage"/>
        <eOperations name="getformalGate" upperBound="-1" eType="#//Generic/Interactions/UMLGate"/>
        <eOperations name="getaction" upperBound="-1" eType="#//Generic/Activities/UMLAction"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLMessage" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eOperations name="getmessageKind" ordered="false" lowerBound="1" eType="#//Generic/Interactions/UMLMessageKind"/>
        <eOperations name="getargument" upperBound="-1" eType="#//Generic/Kernel/UMLValueSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_channel" ordered="false"
            eType="#//Generic/CompositeStructures/UMLConnector"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="receiveEvent" ordered="false"
            eType="#//Generic/Interactions/UMLMessageEnd"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sendEvent" ordered="false"
            eType="#//Generic/Interactions/UMLMessageEnd"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageSort" ordered="false"
            lowerBound="1" eType="#//Generic/Interactions/UMLMessageSort"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLMessageEnd" abstract="true" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="message" ordered="false"
            eType="#//Generic/Interactions/UMLMessage"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="UMLMessageSort">
        <eLiterals name="MS_ASYNCH_CALL"/>
        <eLiterals name="MS_SYNCH_CALL" value="1"/>
        <eLiterals name="MS_ASYNCH_SIGNAL" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="UMLMessageKind">
        <eLiterals name="MK_COMPLETE"/>
        <eLiterals name="MK_FOUND" value="1"/>
        <eLiterals name="MK_LOST" value="2"/>
        <eLiterals name="MK_UNKNOWN" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLGate" eSuperTypes="#//Generic/Interactions/UMLMessageEnd"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLGeneralOrdering" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="after" ordered="false"
            lowerBound="1" eType="#//Generic/Interactions/UMLOccurrenceSpecification"
            eOpposite="#//Generic/Interactions/UMLOccurrenceSpecification/toBefore"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="before" ordered="false"
            lowerBound="1" eType="#//Generic/Interactions/UMLOccurrenceSpecification"
            eOpposite="#//Generic/Interactions/UMLOccurrenceSpecification/toAfter"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLOccurrenceSpecification" eSuperTypes="#//Generic/Interactions/UMLInteractionFragment">
        <eAnnotations source="duplicates">
          <contents xsi:type="ecore:EReference" name="covered" ordered="false" upperBound="-1"
              eType="#//Generic/Interactions/UMLLifeline">
            <eAnnotations source="redefines" references="#//Generic/Interactions/UMLInteractionFragment/covered"/>
          </contents>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="startExecution" ordered="false"
            upperBound="-1" eType="#//Generic/Interactions/UMLExecutionSpecification"
            eOpposite="#//Generic/Interactions/UMLExecutionSpecification/start"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="finishExecution" ordered="false"
            upperBound="-1" eType="#//Generic/Interactions/UMLExecutionSpecification"
            eOpposite="#//Generic/Interactions/UMLExecutionSpecification/finish"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="toAfter" upperBound="-1"
            eType="#//Generic/Interactions/UMLGeneralOrdering" eOpposite="#//Generic/Interactions/UMLGeneralOrdering/before"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="toBefore" upperBound="-1"
            eType="#//Generic/Interactions/UMLGeneralOrdering" eOpposite="#//Generic/Interactions/UMLGeneralOrdering/after"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLCombinedFragment" eSuperTypes="#//Generic/Interactions/UMLInteractionFragment">
        <eOperations name="getoperand" ordered="false" unique="false" lowerBound="1"
            upperBound="-1" eType="#//Generic/Interactions/UMLInteractionOperand"/>
        <eOperations name="getcfragmentGate" ordered="false" unique="false" upperBound="-1"
            eType="#//Generic/Interactions/UMLGate"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="interactionOperator"
            ordered="false" unique="false" lowerBound="1" eType="#//Generic/Interactions/UMLInteractionOperatorKind"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="UMLInteractionOperatorKind">
        <eLiterals name="seq"/>
        <eLiterals name="alt" value="1"/>
        <eLiterals name="opt" value="2"/>
        <eLiterals name="break" value="3"/>
        <eLiterals name="par" value="4"/>
        <eLiterals name="strict" value="5"/>
        <eLiterals name="loop" value="6"/>
        <eLiterals name="critical" value="7"/>
        <eLiterals name="neg" value="8"/>
        <eLiterals name="assert" value="9"/>
        <eLiterals name="ignore" value="10"/>
        <eLiterals name="consider" value="11"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInteractionOperand" eSuperTypes="#//Generic/Interactions/UMLInteractionFragment #//Generic/Kernel/UMLNamespace">
        <eOperations name="getguard" ordered="false" unique="false" eType="#//Generic/Interactions/UMLInteractionConstraint"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInteractionConstraint" eSuperTypes="#//Generic/Kernel/UMLConstraint"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLContinuation" eSuperTypes="#//Generic/Interactions/UMLInteractionFragment">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="setting" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLExecutionOccurrenceSpecification"
          eSuperTypes="#//Generic/Interactions/UMLOccurrenceSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="execution" ordered="false"
            lowerBound="1" eType="#//Generic/Interactions/UMLExecutionSpecification"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLMessageOccurrenceSpecification"
          eSuperTypes="#//Generic/Interactions/UMLOccurrenceSpecification #//Generic/Interactions/UMLMessageEnd">
        <eStructuralFeatures xsi:type="ecore:EReference" name="occurringMessageEvent"
            ordered="false" lowerBound="1" eType="#//Generic/CommonBehaviors/UMLMessageEvent"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Kernel" nsURI="http:///EUML/Generic/Kernel.ecore" nsPrefix="EUML.Generic.Kernel">
      <eClassifiers xsi:type="ecore:EClass" name="UMLElement" abstract="true" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
        <eOperations name="deduce_type_code_and_stereotype" ordered="false" lowerBound="1"/>
        <eOperations name="delete_element" ordered="false" lowerBound="1"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theStereotype" ordered="false"
            eType="#//Generic/Kernel/AppliedStereotype" containment="true" eOpposite="#//Generic/Kernel/AppliedStereotype/theElement"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theAnnotation" upperBound="-1"
            eType="#//Generic/Kernel/UMLAnnotation" eOpposite="#//Generic/Kernel/UMLAnnotation/theElementOfTheAnnotation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theConstraint" upperBound="-1"
            eType="#//Generic/Kernel/UMLConstraint" eOpposite="#//Generic/Kernel/UMLConstraint/theElement"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTrace" ordered="false"
            upperBound="-1" eType="#//Generic/Relationships/UMLTrace" eOpposite="#//Generic/Relationships/UMLTrace/sourceElement"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" ordered="false"
            upperBound="-1" eType="#//Generic/Relationships/UMLRelationship" eOpposite="#//Generic/Relationships/UMLRelationship/the_related_elements"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_relationship_of_target"
            upperBound="-1" eType="#//Generic/Relationships/UMLDirectedRelationship"
            eOpposite="#//Generic/Relationships/UMLDirectedRelationship/the_target_element"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_relationship_of_source"
            upperBound="-1" eType="#//Generic/Relationships/UMLDirectedRelationship"
            eOpposite="#//Generic/Relationships/UMLDirectedRelationship/the_source_element"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="targetTrace" ordered="false"
            upperBound="-1" eType="#//Generic/Relationships/UMLTrace" eOpposite="#//Generic/Relationships/UMLTrace/targetElement"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_utilized_elements"
            upperBound="-1" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/the_utilising_element"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_utilising_element"
            ordered="false" upperBound="-1" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/the_utilized_elements"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_owner" ordered="false"
            eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/the_owned_elements"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_owned_elements"
            upperBound="-1" eType="#//Generic/Kernel/UMLElement" containment="true"
            eOpposite="#//Generic/Kernel/UMLElement/the_owner"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeCode" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotype" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theRepresentative"
            ordered="false" upperBound="-1" eType="#//Presentation/Graphic/Representative"
            eOpposite="#//Presentation/Graphic/Representative/theRepresentedElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AppliedStereotype" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="profileValues" upperBound="-1"
            eType="#//Generic/Kernel/TaggedValue" changeable="false" containment="true"
            eOpposite="#//Generic/Kernel/TaggedValue/theStereotype"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotype" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileName" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theElement" ordered="false"
            eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/theStereotype"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TaggedValue" abstract="true" eSuperTypes="de.ecore#//ikv/medini/kernel/MediniObject">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theStereotype" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/AppliedStereotype" changeable="false"
            eOpposite="#//Generic/Kernel/AppliedStereotype/profileValues"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLAnnotation" eSuperTypes="#//Generic/Kernel/UMLElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotationKind" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theElementOfTheAnnotation"
            ordered="false" upperBound="-1" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/theAnnotation"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLConstraint" eSuperTypes="#//Generic/Kernel/UMLElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintLanguage"
            ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theElement" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLElement" eOpposite="#//Generic/Kernel/UMLElement/theConstraint"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLClassifier" abstract="true" eSuperTypes="#//Generic/Kernel/UMLType #//Generic/Kernel/UMLNamespace">
        <eOperations name="getownedBehavior" upperBound="-1" eType="#//Generic/CommonBehaviors/UMLBehavior"/>
        <eOperations name="getownedTriggers" upperBound="-1" eType="#//Generic/CommonBehaviors/UMLTrigger"/>
        <eOperations name="getcollaborationUsages" upperBound="-1" eType="#//Generic/CompositeStructures/UMLCollaborationUse"/>
        <eOperations name="gettheBaseClassifiers" upperBound="-1" eType="#//Generic/Kernel/UMLClassifier"/>
        <eOperations name="getgeneralizations" upperBound="-1" eType="#//Generic/Relationships/UMLGeneralization"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theClassifierBehavior"
            ordered="false" eType="#//Generic/CommonBehaviors/UMLBehavior" eOpposite="#//Generic/CommonBehaviors/UMLBehavior/theBehavioredClassifier"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theRaisingOperations"
            upperBound="-1" eType="#//Generic/Kernel/UMLOperation" eOpposite="#//Generic/Kernel/UMLOperation/theExceptions"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="representation" ordered="false"
            eType="#//Generic/CompositeStructures/UMLCollaborationUse"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theUseCases" upperBound="-1"
            eType="#//Generic/UseCases/UMLUseCase" eOpposite="#//Generic/UseCases/UMLUseCase/theSubject"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLType" abstract="true" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="theTypedElement" upperBound="-1"
            eType="#//Generic/Kernel/UMLTypedElement" eOpposite="#//Generic/Kernel/UMLTypedElement/theType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLNamedElement" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLElement">
        <eOperations name="getqualifiedName" unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eOperations name="getqualifiedAlias" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eOperations name="gettheNamespace" ordered="false" unique="false" eType="#//Generic/Kernel/UMLNamespace"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false"
            unique="false" lowerBound="1" eType="#//Generic/Kernel/UMLVisibilityKind"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="UMLVisibilityKind">
        <eLiterals name="PUBLIC_VIS"/>
        <eLiterals name="PRIVATE_VIS" value="1"/>
        <eLiterals name="PROTECTED_VIS" value="2"/>
        <eLiterals name="PACKAGE_VIS" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLNamespace" abstract="true" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eOperations name="gettheContainedElements" upperBound="-1" eType="#//Generic/Kernel/UMLNamedElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLTypedElement" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eOperations name="getTypeForType" ordered="false" unique="false" lowerBound="1"
            eType="#//Generic/Kernel/UMLType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theType" ordered="false"
            eType="#//Generic/Kernel/UMLType" eOpposite="#//Generic/Kernel/UMLType/theTypedElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLFeature" abstract="true" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLOperation" eSuperTypes="#//Generic/CommonBehaviors/UMLBehavioralFeature #//Generic/Kernel/UMLTypedElement #//Generic/Kernel/UMLMultiplicityElement #//Generic/Kernel/UMLNamespace">
        <eOperations name="getparameters" upperBound="-1" eType="#//Generic/Kernel/UMLParameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theExceptions" upperBound="-1"
            eType="#//Generic/Kernel/UMLClassifier" eOpposite="#//Generic/Kernel/UMLClassifier/theRaisingOperations"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLMultiplicityElement" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLParameter" eSuperTypes="#//Generic/CompositeStructures/UMLConnectableElement #//Generic/Kernel/UMLMultiplicityElement #//Generic/Kernel/UMLNamedElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="directionKind" ordered="false"
            unique="false" lowerBound="1" eType="#//Generic/Kernel/UMLParamDirectionKind"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInterface" eSuperTypes="#//Generic/Kernel/UMLClassifier">
        <eOperations name="getownedProperties" upperBound="-1" eType="#//Generic/Kernel/UMLProperty"/>
        <eOperations name="getownedOperations" upperBound="-1" eType="#//Generic/Kernel/UMLOperation"/>
        <eOperations name="getownedReceptions" upperBound="-1" eType="#//Generic/CommonBehaviors/UMLReception"/>
        <eOperations name="getnestedInterface" upperBound="-1" eType="#//Generic/Kernel/UMLInterface"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="UMLParamDirectionKind">
        <eLiterals name="DIR_IN"/>
        <eLiterals name="DIR_OUT" value="1"/>
        <eLiterals name="DIR_INOUT" value="2"/>
        <eLiterals name="DIR_RETURN" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLValueSpecification" abstract="true"
          eSuperTypes="#//Generic/Kernel/UMLTypedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedBy" upperBound="-1"
            eType="#//Generic/Activities/UMLObjectNode" eOpposite="#//Generic/Activities/UMLObjectNode/allocationScheme"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLClass" eSuperTypes="#//Generic/CompositeStructures/UMLStructuredClassifier">
        <eOperations name="getownedOperations" upperBound="-1" eType="#//Generic/Kernel/UMLOperation"/>
        <eOperations name="getownedReceptions" upperBound="-1" eType="#//Generic/CommonBehaviors/UMLReception"/>
        <eOperations name="getnestedClassifiers" upperBound="-1" eType="#//Generic/Kernel/UMLClassifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LiteralValue" eSuperTypes="#//Generic/Kernel/UMLValueSpecification">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReferenceValue" eSuperTypes="#//Generic/Kernel/TaggedValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
            unique="false" lowerBound="1" eType="#//Generic/Kernel/UMLElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="#//Generic/Kernel/TaggedValue">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="UMLAggregationKind">
        <eLiterals name="AGG_NONE"/>
        <eLiterals name="AGG_SHARED" value="1"/>
        <eLiterals name="AGG_COMPOSITE" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLAssociation" eSuperTypes="#//Generic/Kernel/UMLClassifier #//Generic/Relationships/UMLRelationship">
        <eStructuralFeatures xsi:type="ecore:EReference" name="theEndTwo" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLProperty" eOpposite="#//Generic/Kernel/UMLProperty/theAssociationOfEndTwo"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theEndOne" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLProperty" eOpposite="#//Generic/Kernel/UMLProperty/theAssociationOfEndOne"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLEnumeration" eSuperTypes="#//Generic/Kernel/UMLType #//Generic/Kernel/UMLNamespace">
        <eOperations name="getenumerators" lowerBound="1" upperBound="-1" eType="#//Generic/Kernel/UMLEnumerationLiteral"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLEnumerationLiteral" eSuperTypes="#//Generic/Kernel/UMLNamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInstanceSpecification" eSuperTypes="#//Generic/Kernel/UMLNamedElement">
        <eOperations name="getslot" upperBound="-1" eType="#//Generic/Kernel/UMLSlot"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="the_classifiers" upperBound="-1"
            eType="#//Generic/Kernel/UMLClassifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLSlot" eSuperTypes="#//Generic/Kernel/UMLElement">
        <eOperations name="getvaluesOfTheSlot" upperBound="-1" eType="#//Generic/Kernel/UMLValueSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="definingFeature" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLProperty"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLInstanceValue" eSuperTypes="#//Generic/Kernel/UMLValueSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="instance" ordered="false"
            lowerBound="1" eType="#//Generic/Kernel/UMLInstanceSpecification"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLPackage" eSuperTypes="#//Generic/Kernel/UMLNamespace">
        <eOperations name="getownedPackages" upperBound="-1" eType="#//Generic/Kernel/UMLPackage"/>
        <eOperations name="getownedClassifier" upperBound="-1" eType="#//Generic/Kernel/UMLClassifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UMLPrimitiveType" eSuperTypes="#//Generic/Kernel/UMLType"/>
      <eClassifiers xsi:type="ecore:EClass" name="UMLProperty" eSuperTypes="#//Generic/Kernel/UMLTypedElement #//Generic/Kernel/UMLFeature #//Generic/Kernel/UMLMultiplicityElement">
        <eOperations name="getisAssociationProperty" ordered="false" unique="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theAssociationOfEndTwo"
            ordered="false" eType="#//Generic/Kernel/UMLAssociation" eOpposite="#//Generic/Kernel/UMLAssociation/theEndTwo"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="theAssociationOfEndOne"
            ordered="false" eType="#//Generic/Kernel/UMLAssociation" eOpposite="#//Generic/Kernel/UMLAssociation/theEndOne"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadOnly" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" ordered="false"
            unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregationKind" ordered="false"
            unique="false" lowerBound="1" eType="#//Generic/Kernel/UMLAggregationKind"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
