<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eventCounter"
    nsURI="http://de.hpi.sam.bp2009.benchframework.eventCounter" nsPrefix="benchframework.eventCounter">
  <eClassifiers xsi:type="ecore:EClass" name="EventCounterStart" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//Operator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This operator starts event counting. It holds a map from string to int to identify the different types of events e.g. incoming events, mapped internal events, events sent to a specific application or thelike."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endPoint" eType="#//EventCounterEnd"
        eOpposite="#//EventCounterEnd/startPoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adapter" eType="#//Adapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventCounterEnd" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//Operator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This operator ends execution time measurement."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startPoint" eType="#//EventCounterStart"
        eOpposite="#//EventCounterStart/endPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Adapter" instanceClassName="org.eclipse.emf.common.notify.Adapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventCounterOptionObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventCounterResultObject" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//ResultObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventCounts" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
