<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="_EhS4EEO6Ed-T8POTkiYiBg"
    name="multipleOPSample" nsURI="http://www.modelversioning.org/ecoremutator/sample1"
    nsPrefix="ms">
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_Ehba8EO6Ed-T8POTkiYiBg" name="Employer">
    <eOperations xmi:id="_Ehba8UO6Ed-T8POTkiYiBg" name="fire"/>
    <eOperations xmi:id="_EhdQIEO6Ed-T8POTkiYiBg" name="work"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Ehd3MEO6Ed-T8POTkiYiBg"
        name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Ehd3MkO6Ed-T8POTkiYiBg"
        name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_Ehg6gEO6Ed-T8POTkiYiBg"
        name="salary" eType="#_EhiIpUO6Ed-T8POTkiYiBg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumAttribute" eType="#//EnumerationTest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_Ehg6gUO6Ed-T8POTkiYiBg" name="Employee">
    <eOperations xmi:id="_Ehg6gkO6Ed-T8POTkiYiBg" name="fire"/>
    <eOperations xmi:id="_Ehg6g0O6Ed-T8POTkiYiBg" name="work"/>
    <eOperations xmi:id="_Ehg6hEO6Ed-T8POTkiYiBg" name="calculateAge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Ehg6hkO6Ed-T8POTkiYiBg"
        name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_Ehg6iEO6Ed-T8POTkiYiBg"
        name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_EhhhkEO6Ed-T8POTkiYiBg"
        name="employedBy" upperBound="-1" eType="#_Ehba8EO6Ed-T8POTkiYiBg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_EhhhkkO6Ed-T8POTkiYiBg" name="Company">
    <eOperations xmi:id="_Ehhhk0O6Ed-T8POTkiYiBg" name="isBroke"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_EhhhlEO6Ed-T8POTkiYiBg"
        name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_EhhhlkO6Ed-T8POTkiYiBg"
        name="address" eType="#_Ehhhl0O6Ed-T8POTkiYiBg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_Ehhhl0O6Ed-T8POTkiYiBg" name="Address">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_EhhhmEO6Ed-T8POTkiYiBg"
        name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_EhiIoUO6Ed-T8POTkiYiBg"
        name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_EhiIo0O6Ed-T8POTkiYiBg"
        name="zipCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_EhiIpUO6Ed-T8POTkiYiBg" name="ManagementSalary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_salaryAtt" name="salary"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumerationTest">
    <eLiterals name="Test"/>
    <eLiterals name="Test2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Enum2">
    <eLiterals name="Literal1"/>
  </eClassifiers>
</ecore:EPackage>
