/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.component.__impl;

public final class AComponentUsageGroupMembersImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationImpl
{
    // default constructor
    public AComponentUsageGroupMembersImpl() {
        super();
    }

    // specific constructor
    public AComponentUsageGroupMembersImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    
    public boolean exists(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsageGroup, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Members) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return exists(get___CurrentConnection(), _ComponentUsageGroup, _Members);
    }
    public boolean exists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsageGroup, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Members) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return ___existsMultN( connection, _ComponentUsageGroup, _Members, "45DDACEE1269BB096DAD4D642537D7AC717D0873"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getComponentUsageGroup(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Members) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getComponentUsageGroup(get___CurrentConnection(), _Members);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getComponentUsageGroup(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Members) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        com.sap.tc.moin.repository.core.EndAndMetaObject endAndMetaObject = get___EndAndMetaObject( 1 );
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___queryElementAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _Members, endAndMetaObject );
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getMembers(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsageGroup) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return getMembers(get___CurrentConnection(), _ComponentUsageGroup);
    }
    public java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject> getMembers(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsageGroup) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection<com.sap.tc.moin.repository.mmi.reflect.RefBaseObject>) ___getElementsAtOtherLinkEnd( connection, (com.sap.tc.moin.repository.core.CorePartitionable) _ComponentUsageGroup, get___EndAndMetaObject( 0 ) );
    }
    public boolean add(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsageGroup, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Members) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_ComponentUsageGroup, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Members);
    }
    public boolean add(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsageGroup, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Members) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          return refAddLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ComponentUsageGroup, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Members);
    }
    public boolean remove(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsageGroup, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Members) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink((com.sap.tc.moin.repository.mmi.reflect.RefObject)_ComponentUsageGroup, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Members);
    }
    public boolean remove(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _ComponentUsageGroup, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject _Members) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return refRemoveLink(connection, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_ComponentUsageGroup, (com.sap.tc.moin.repository.mmi.reflect.RefObject)_Members);
    }
    public boolean refLinkExists(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefObject firstEnd, com.sap.tc.moin.repository.mmi.reflect.RefObject secondEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        if ( firstEnd == null || secondEnd == null ) { return false; }
        checkTypesForRefLinkExists( connection, firstEnd, secondEnd );
        return exists( connection, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) firstEnd, (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) secondEnd );
    }

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.webdynpro.component.AComponentUsageGroupMembers> get___JmiInterface() {
        return com.sap.ide.metamodel.webdynpro.component.AComponentUsageGroupMembers.class;
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<com.sap.ide.metamodel.webdynpro.component.AComponentUsageGroupMembers> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new com.sap.ide.metamodel.webdynpro.component.__impl.AComponentUsageGroupMembersWrapper(conn, this, synchronize);
    }
}