<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="randomGenerator"
    nsURI="http://de.hpi.sam.bp2009.benchframework.randomGenerator" nsPrefix="benchframework.randomGenerator">
  <eClassifiers xsi:type="ecore:EClass" name="RandomGenerator" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//Operator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This random generator generates a random instance of a given meta model. The meta model to instantiate has to be given in the respective RandomGeneratorOptionObject alon with some parameters the model instance has to match."/>
    </eAnnotations>
    <eOperations name="generateRandomModel">
      <eParameters name="number" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"/>
      <eParameters name="resource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
      <eParameters name="pkg" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomGeneratorOptionObject" eSuperTypes="../../de.hpi.sam.bp2009.benchframework/model/benchframework.ecore#//RandomNumberOptionObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is the option object of a RandomGenerator. It holds the metaModel to instantiate along with a map of parameters the generated instance has to match."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaModel" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
