/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.base.__impl;

public class ATypePropertyWrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationWrapperImpl<com.sap.ide.metamodel.webdynpro.base.ATypeProperty> implements com.sap.ide.metamodel.webdynpro.base.ATypeProperty,com.sap.tc.moin.repository.Partitionable
{

    /**
     * The ATypeProperty wrapper
     */
    public ATypePropertyWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, com.sap.ide.metamodel.webdynpro.base.__impl.ATypePropertyImpl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }
    
    private com.sap.ide.metamodel.webdynpro.base.__impl.ATypePropertyImpl getCastWrappedObject() {
        return (com.sap.ide.metamodel.webdynpro.base.__impl.ATypePropertyImpl) getWrappedObject();
    }

    public com.sap.ide.metamodel.webdynpro.base.ATypeProperty unwrap() {
        return (com.sap.ide.metamodel.webdynpro.base.ATypeProperty) getWrappedObject();
    }
    
    public boolean exists(com.sap.ide.metamodel.common.Type _Type, com.sap.ide.metamodel.webdynpro.base.Property _Property) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Type), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Property));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Type), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Property)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public com.sap.ide.metamodel.common.Type getType(com.sap.ide.metamodel.webdynpro.base.Property _Property) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (com.sap.ide.metamodel.common.Type) wrapResult(getCastWrappedObject().getType(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Property)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (com.sap.ide.metamodel.common.Type) wrapResult(getCastWrappedObject().getType(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Property))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public java.util.Collection getProperty(com.sap.ide.metamodel.common.Type _Type) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (java.util.Collection) wrapResult(getCastWrappedObject().getProperty(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Type)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (java.util.Collection) wrapResult(getCastWrappedObject().getProperty(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Type))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean add(com.sap.ide.metamodel.common.Type _Type, com.sap.ide.metamodel.webdynpro.base.Property _Property) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Type), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Property));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Type), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Property)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean remove(com.sap.ide.metamodel.common.Type _Type, com.sap.ide.metamodel.webdynpro.base.Property _Property) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Type), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Property));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Type), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _Property)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }   

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.webdynpro.base.ATypeProperty> get___JmiInterface() {
        return com.sap.ide.metamodel.webdynpro.base.ATypeProperty.class;
    }

    protected String metaObjectToString() {
        return "com.sap.ide.metamodel.webdynpro.base.ATypeProperty (Java Type)\nWebDynpro.base.A_Type_property (MOF Type)"; //$NON-NLS-1$
    }    
}