<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="loggingandtracing"
    nsURI="http:///loggingandtracing.ecore" nsPrefix="loggingandtracing">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://de.hpi.sam.bp2009.OCL"/>
    <details key="validationDelegates" value="http://de.hpi.sam.bp2009.OCL"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Constructs to express logging/tracing requests. Ideally, logging and tracing are separate from the other models but link to them. This allows for easy separation of the logging/tracing concern. Specific constructs may be established that trace, e.g., entry/exit of blocks/operations, modifications/reads of properties/associations, etc."/>
  </eAnnotations>
</ecore:EPackage>
