<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="security"
    nsURI="http:///security.ecore" nsPrefix="security">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://de.hpi.sam.bp2009.OCL"/>
    <details key="validationDelegates" value="http://de.hpi.sam.bp2009.OCL"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="We need to talk about subjects, policies, permissions, levels of authentication, certificates. Permissions need to be assigned to functionality and structure. How does this affect computing aggregates? We need to talk about signing messages, requests and events. How are keys managed and how is their use modeled? What about encryption and how should that be represented in models?"/>
  </eAnnotations>
</ecore:EPackage>
