<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sproxy_content"
    nsURI="http:///sproxy_content.ecore" nsPrefix="sproxy_content">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://de.hpi.sam.bp2009.OCL"/>
    <details key="validationDelegates" value="http://de.hpi.sam.bp2009.OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BO" eSuperTypes="modelmanagement.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Partition ID consists of BO's name and namespace. The single BO is the single root of that partition. The partition contains the subordinate BONodes with their Operations (Action/Query), Associations, the StautsAndActionSchemas as well as all ESF properties pertinent to any of these nodes.&#xD;&#xA;&#xD;&#xA;Together with its root BONode, the BO element is mapped to a Class. The BO properties such as its name determine the key properties of the resulting class. The node's data structure and child nodes determine other structural properties of the resulting Class."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootNode" lowerBound="1"
        eType="#//BONode" containment="true" eOpposite="#//BONode/bo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statusDerivators" upperBound="-1"
        eType="#//StatusDerivator">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//BO"
        eOpposite="#//BO/projections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projections" upperBound="-1"
        eType="#//BO" eOpposite="#//BO/template"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BONode" eSuperTypes="modelmanagement.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="BONodes other than root nodes are mapped to a Class, together with its nodeDataType. The DataType as well as the Associations on the BONode determine the set of Associations attached to the resulting Class."/>
    </eAnnotations>
    <eAnnotations source="http://de.hpi.sam.bp2009.OCL">
      <details key="EitherRootOrChild" value="self.bo->isEmpty() implies self.association->exists(a:Association | a.composite)"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="EitherRootOrChild"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeDataType" lowerBound="1"
        eType="#//DataType">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bo" eType="#//BO" transient="true"
        eOpposite="#//BO/rootNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statusAndActionSchemas"
        upperBound="-1" eType="#//StatusAndActionSchema" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="#//Association" eOpposite="#//Association/targetNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outboundAssociations" upperBound="-1"
        eType="#//Association" eOpposite="#//Association/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queries" upperBound="-1"
        eType="#//Query" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        eType="#//NodeProperties">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldProperties" upperBound="-1"
        eType="#//FieldProperties" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="modelmanagement.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A DataType that is not a nodeDataType maps to a Class (node data types are combined with their respective BONodes into a single Class). The elements and attributes are mapped to respective Associations."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abapType" lowerBound="1"
        eType="ecore:EClass abapmapping.ecore#//abapdictionary/AbapType">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" eType="#//Cardinality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInterface" eSuperTypes="modelmanagement.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//ServiceInterfaceOperation" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInterfaceOperation" eSuperTypes="modelmanagement.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestMessageType" lowerBound="1"
        eType="#//DataType">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseMessageType" lowerBound="1"
        eType="#//DataType">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faultMessageType" eType="#//DataType">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessAgent" eSuperTypes="modelmanagement.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutboundProcessAgent" eSuperTypes="#//ProcessAgent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outboundServiceInterface"
        lowerBound="1" eType="#//ServiceInterface">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InboundProcessAgent" eSuperTypes="#//ProcessAgent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inboundServiceInterfaces"
        lowerBound="1" upperBound="-1" eType="#//ServiceInterface">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatusAndActionSchema" eSuperTypes="modelmanagement.ecore#//NamedElement">
    <eAnnotations source="http://de.hpi.sam.bp2009.OCL">
      <details key="CanOnlyUseStatusAttributes" value="self.statusVariables->forAll(a:Attribute | a.statusAttribute)"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="CanOnlyUseStatusAttributes"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statusVariables" upperBound="-1"
        eType="#//Attribute">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" eSuperTypes="modelmanagement.ecore#//NamedElement #//Field">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Maps to an Association between the Classes to which the adjacent DataTypes have been mapped."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="modelmanagement.ecore#//NamedElement #//Field">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Maps to an Association between the Classes to which the owning DataType and the UnstructuredAbapType have been mapped, respectively."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statusAttribute" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abapType" lowerBound="1"
        eType="ecore:EClass abapmapping.ecore#//abapdictionary/UnstructuredAbapType">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Cardinality">
    <eLiterals name="zero"/>
    <eLiterals name="one" value="1"/>
    <eLiterals name="two" value="2"/>
    <eLiterals name="many" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DO" eSuperTypes="#//BO modelmanagement.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Dependent Objects constitute their own partition with a single DO as its root element. All contained elements are handled like for any other BO element, meaning they are contained in the DO's partition.&#xD;&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composite" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNode" lowerBound="1"
        eType="#//BONode" eOpposite="#//BONode/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//BONode"
        eOpposite="#//BONode/outboundAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        eType="#//AssociationProperties">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="modelmanagement.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterType" eType="#//DataType">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        eType="#//OperationProperties">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatusDerivator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Attribute">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Attribute">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Population" eSuperTypes="#//StatusDerivator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//StatusDerivator"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabled" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabledFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createEnabled" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createEnabledFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabled" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabledFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createEnabled" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createEnabledFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updateEnabled" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updateEnabledFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deleteEnabled" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deleteEnabledFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transientKey" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transientKeyFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabled" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabledFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabled" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabledFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readonly" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readonlyFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatory" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryFinal" eType="ecore:EClass runtime.ecore#//primitivetypes/Boolean"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="#//Field"
        eOpposite="#//Field/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//FieldProperties" eOpposite="#//FieldProperties/field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageDependentText"/>
</ecore:EPackage>
