/**
 * Generated by the MOIN Generator Version 3.0
 **/

package data.generics.__impl;

public final class ParameterizedClassInstantiationImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefObjectImpl {

        
    public static final java.util.Map<java.lang.String, java.lang.Integer> FEATURE_IDS;
        
    private static final java.util.Map<java.lang.String, java.lang.Integer> OPERATION_IDS;
    
    static {
        
        FEATURE_IDS = new java.util.HashMap<java.lang.String, java.lang.Integer>(20);
        FEATURE_IDS.put("subscriptions", Integer.valueOf(0)); //$NON-NLS-1$
        FEATURE_IDS.put("notificationSignatures", Integer.valueOf(1)); //$NON-NLS-1$
        FEATURE_IDS.put("name", Integer.valueOf(2)); //$NON-NLS-1$
        FEATURE_IDS.put("description", Integer.valueOf(3)); //$NON-NLS-1$
        FEATURE_IDS.put("ownedSignatures", Integer.valueOf(4)); //$NON-NLS-1$
        FEATURE_IDS.put("signaturesWithFault", Integer.valueOf(5)); //$NON-NLS-1$
        FEATURE_IDS.put("elementsOfType", Integer.valueOf(6)); //$NON-NLS-1$
        FEATURE_IDS.put("package_", Integer.valueOf(7)); //$NON-NLS-1$
        FEATURE_IDS.put("adaptedBy", Integer.valueOf(8)); //$NON-NLS-1$
        FEATURE_IDS.put("adapters", Integer.valueOf(9)); //$NON-NLS-1$
        FEATURE_IDS.put("formalObjectParameters", Integer.valueOf(10)); //$NON-NLS-1$
        FEATURE_IDS.put("converterBetweenParametrizations", Integer.valueOf(11)); //$NON-NLS-1$
        FEATURE_IDS.put("valueType", Integer.valueOf(12)); //$NON-NLS-1$
        FEATURE_IDS.put("actualTypeParametersForInstantiation", Integer.valueOf(13)); //$NON-NLS-1$
        FEATURE_IDS.put("parameterizedClass", Integer.valueOf(14)); //$NON-NLS-1$
        
        OPERATION_IDS = new java.util.HashMap<java.lang.String, java.lang.Integer>(30);
        OPERATION_IDS.put("isAbstract", Integer.valueOf(0)); //$NON-NLS-1$
        OPERATION_IDS.put("isParameterizedClassDefinition", Integer.valueOf(1)); //$NON-NLS-1$
        OPERATION_IDS.put("conformsTo", Integer.valueOf(2)); //$NON-NLS-1$
        OPERATION_IDS.put("allSignatures", Integer.valueOf(3)); //$NON-NLS-1$
        OPERATION_IDS.put("delegatesTo", Integer.valueOf(4)); //$NON-NLS-1$
        OPERATION_IDS.put("conformsToExcluding", Integer.valueOf(5)); //$NON-NLS-1$
        OPERATION_IDS.put("signaturesWithDelegation", Integer.valueOf(6)); //$NON-NLS-1$
        OPERATION_IDS.put("delegatedSignatures", Integer.valueOf(7)); //$NON-NLS-1$
        OPERATION_IDS.put("adaptedSignatures", Integer.valueOf(8)); //$NON-NLS-1$
        OPERATION_IDS.put("adaptedSignaturesExcluding", Integer.valueOf(9)); //$NON-NLS-1$
        OPERATION_IDS.put("allSignaturesExcluding", Integer.valueOf(10)); //$NON-NLS-1$
        OPERATION_IDS.put("signaturesWithDelegationExcluding", Integer.valueOf(11)); //$NON-NLS-1$
        OPERATION_IDS.put("delegatedSignaturesExcluding", Integer.valueOf(12)); //$NON-NLS-1$
        OPERATION_IDS.put("getConformingClasses", Integer.valueOf(13)); //$NON-NLS-1$
        OPERATION_IDS.put("getAssociationEnds", Integer.valueOf(14)); //$NON-NLS-1$
        OPERATION_IDS.put("getEqualityRelevantAssociationEnds", Integer.valueOf(15)); //$NON-NLS-1$
        OPERATION_IDS.put("getConformsToClasses", Integer.valueOf(16)); //$NON-NLS-1$
        OPERATION_IDS.put("getConformsToAssociationEnds", Integer.valueOf(17)); //$NON-NLS-1$
        OPERATION_IDS.put("getConformsToCompositeParentAssociationEnds", Integer.valueOf(18)); //$NON-NLS-1$
        OPERATION_IDS.put("getConformsToCompositeChildAssociationEnds", Integer.valueOf(19)); //$NON-NLS-1$
        OPERATION_IDS.put("resolveFormalTypeParameter", Integer.valueOf(20)); //$NON-NLS-1$
        OPERATION_IDS.put("getClassParameterization", Integer.valueOf(21)); //$NON-NLS-1$
    }
    
    
    // variable declarations
    private java.lang.String __name = null;
    private boolean __valueType = false;

    // links for multiplicity-1 association ends
    private com.sap.tc.moin.repository.core.EndStorageLink __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF;
    private com.sap.tc.moin.repository.core.EndStorageLink __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF;
    private com.sap.tc.moin.repository.core.EndStorageLink __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF;
    private com.sap.tc.moin.repository.core.EndStorageLink __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF;

    // links for multiplicity-n association ends
    private java.util.Collection<com.sap.tc.moin.repository.core.EndStorageLink> __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF;
    private java.util.Collection<com.sap.tc.moin.repository.core.EndStorageLink> __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF;
    private java.util.Collection<com.sap.tc.moin.repository.core.EndStorageLink> __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF;

    // links for multiplicity-1 object-valued attributes
    private com.sap.tc.moin.repository.core.EndStorageLink __description;

    // default constructor
    public ParameterizedClassInstantiationImpl() {
        super();
    }
    
    // specific constructor
    public ParameterizedClassInstantiationImpl(java.lang.Object workspace, String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject, com.sap.tc.moin.repository.mmi.reflect.RefClass refClass) {
        super(workspace, mofId, immediatePackage, metaObject, refClass);
    }
    
    // methods for attributes
    public java.lang.String getName() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return __name;
    }
    public void setName(java.lang.String newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeDataTypeAttribute(get___CurrentConnection(), 2, "E07264A551F762DD3E4B11DE95370018DE1146FF", __name, newValue); //$NON-NLS-1$
    }
    public void setName(com.sap.tc.moin.repository.core.CoreConnection connection, java.lang.String newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeDataTypeAttribute(connection, 2, "E07264A551F762DD3E4B11DE95370018DE1146FF", __name, newValue); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getDescription() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( get___CurrentConnection(), __description);
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getDescription(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( connection, __description);
    }
    public void setDescription(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeObjectAttribute(get___CurrentConnection(), "E07264A551F762DE3E4B11DE8B180018DE1146FF", newValue); //$NON-NLS-1$
    }
    public void setDescription(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeObjectAttribute(connection, "E07264A551F762DE3E4B11DE8B180018DE1146FF", newValue); //$NON-NLS-1$
    }
    public boolean isValueType() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return __valueType;
    }
    public void setValueType(boolean newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeDataTypeAttribute(get___CurrentConnection(), 12, "E0234C8C51E476DD3E4B11DE83EC0018DE1146FF", __valueType, newValue); //$NON-NLS-1$
    }
    public void setValueType(com.sap.tc.moin.repository.core.CoreConnection connection, boolean newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeDataTypeAttribute(connection, 12, "E0234C8C51E476DD3E4B11DE83EC0018DE1146FF", __valueType, newValue); //$NON-NLS-1$
    }

    // methods for references
    public java.util.Collection getSubscriptions() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( get___CurrentConnection(), this, get___EndAndMetaObject( "E0BC871351CA38203E4B11DEB5F50018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }
    public java.util.Collection getSubscriptions(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( connection, this, get___EndAndMetaObject( "E0BC871351CA38203E4B11DEB5F50018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }


    public java.util.Collection getNotificationSignatures() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( get___CurrentConnection(), this, get___EndAndMetaObject( "E0BC871351CC82003E4B11DEC6000018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }
    public java.util.Collection getNotificationSignatures(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( connection, this, get___EndAndMetaObject( "E0BC871351CC82003E4B11DEC6000018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }


    public java.util.Collection getOwnedSignatures() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___getElementsAtOtherLinkEnd( get___CurrentConnection(), this, get___EndAndMetaObject( "E0234C8C51EB7BF13E4B11DE9A020018DE1146FF" /* attribute or association */, 1 ) ) ; //$NON-NLS-1$
       
    }
    public java.util.Collection getOwnedSignatures(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___getElementsAtOtherLinkEnd( connection, this, get___EndAndMetaObject( "E0234C8C51EB7BF13E4B11DE9A020018DE1146FF" /* attribute or association */, 1 ) ) ; //$NON-NLS-1$
       
    }


    public java.util.Collection getSignaturesWithFault() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( get___CurrentConnection(), this, get___EndAndMetaObject( "E0234C8C51E9320D3E4B11DEA3540018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }
    public java.util.Collection getSignaturesWithFault(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( connection, this, get___EndAndMetaObject( "E0234C8C51E9320D3E4B11DEA3540018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }


    public java.util.Collection getElementsOfType() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( get___CurrentConnection(), this, get___EndAndMetaObject( "E0234C8C51EB7BC43E4B11DECAD00018DE1146FF" /* attribute or association */, 0 ) ); //$NON-NLS-1$
       
    }
    public java.util.Collection getElementsOfType(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( connection, this, get___EndAndMetaObject( "E0234C8C51EB7BC43E4B11DECAD00018DE1146FF" /* attribute or association */, 0 ) ); //$NON-NLS-1$
       
    }


    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getPackage() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( get___CurrentConnection(), __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF);
       
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getPackage(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( connection, __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF);
       
    }
    public void setPackage(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeReference(get___CurrentConnection(), /* mofId of association */ "E0234C8C51EB7BCA3E4B11DE87500018DE1146FF", /* mofId of reference */ "E0234C8C51E476D83E4B11DEC6F00018DE1146FF" , newValue, 0); //$NON-NLS-1$ //$NON-NLS-2$
    
    }
    public void setPackage(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeReference(connection, /* mofId of association */ "E0234C8C51EB7BCA3E4B11DE87500018DE1146FF", /* mofId of reference */ "E0234C8C51E476D83E4B11DEC6F00018DE1146FF" , newValue, 0); //$NON-NLS-1$ //$NON-NLS-2$
    
    }
    public java.util.Collection getAdaptedBy() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( get___CurrentConnection(), this, get___EndAndMetaObject( "E0234C8C51EB7BE23E4B11DEA9680018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }
    public java.util.Collection getAdaptedBy(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( connection, this, get___EndAndMetaObject( "E0234C8C51EB7BE23E4B11DEA9680018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }


    public java.util.Collection getAdapters() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( get___CurrentConnection(), this, get___EndAndMetaObject( "E0234C8C51EB7BE53E4B11DEA6D90018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }
    public java.util.Collection getAdapters(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.Collection) ___queryElementsAtOtherLinkEnd( connection, this, get___EndAndMetaObject( "E0234C8C51EB7BE53E4B11DEA6D90018DE1146FF" /* attribute or association */, 1 ) ); //$NON-NLS-1$
       
    }


    public java.util.List getFormalObjectParameters() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.List) ___getElementsAtOtherLinkEnd( get___CurrentConnection(), this, get___EndAndMetaObject( "E0234C8C51EB7BFA3E4B11DEA28E0018DE1146FF" /* attribute or association */, 0 ) ) ; //$NON-NLS-1$
       
    }
    public java.util.List getFormalObjectParameters(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.List) ___getElementsAtOtherLinkEnd( connection, this, get___EndAndMetaObject( "E0234C8C51EB7BFA3E4B11DEA28E0018DE1146FF" /* attribute or association */, 0 ) ) ; //$NON-NLS-1$
       
    }


    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getConverterBetweenParametrizations() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        com.sap.tc.moin.repository.core.EndAndMetaObject endAndMetaObject = get___EndAndMetaObject( "E0234C8C51EDECBB3E4B11DEC0E20018DE1146FF" /* attribute or association */, 0 ); //$NON-NLS-1$
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___queryElementAtOtherLinkEnd( get___CurrentConnection(), this, endAndMetaObject );
       
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getConverterBetweenParametrizations(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        com.sap.tc.moin.repository.core.EndAndMetaObject endAndMetaObject = get___EndAndMetaObject( "E0234C8C51EDECBB3E4B11DEC0E20018DE1146FF" /* attribute or association */, 0 ); //$NON-NLS-1$
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___queryElementAtOtherLinkEnd( connection, this, endAndMetaObject );
       
    }
    public void setConverterBetweenParametrizations(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeReference(get___CurrentConnection(), /* mofId of association */ "E0234C8C51EDECBB3E4B11DEC0E20018DE1146FF", /* mofId of reference */ "E0234C8C51E476DC3E4B11DE857B0018DE1146FF" , newValue, 0); //$NON-NLS-1$ //$NON-NLS-2$
    
    }
    public void setConverterBetweenParametrizations(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeReference(connection, /* mofId of association */ "E0234C8C51EDECBB3E4B11DEC0E20018DE1146FF", /* mofId of reference */ "E0234C8C51E476DC3E4B11DE857B0018DE1146FF" , newValue, 0); //$NON-NLS-1$ //$NON-NLS-2$
    
    }
    public java.util.List getActualTypeParametersForInstantiation() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.List) ___getElementsAtOtherLinkEnd( get___CurrentConnection(), this, get___EndAndMetaObject( "E0234C8C51F05DCF3E4B11DEC3C50018DE1146FF" /* attribute or association */, 0 ) ) ; //$NON-NLS-1$
       
    }
    public java.util.List getActualTypeParametersForInstantiation(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (java.util.List) ___getElementsAtOtherLinkEnd( connection, this, get___EndAndMetaObject( "E0234C8C51F05DCF3E4B11DEC3C50018DE1146FF" /* attribute or association */, 0 ) ) ; //$NON-NLS-1$
       
    }


    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getParameterizedClass() throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( get___CurrentConnection(), __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF);
       
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefBaseObject getParameterizedClass(com.sap.tc.moin.repository.core.CoreConnection connection) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        return (com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) ___getElementAtOtherLinkEnd( connection, __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF);
       
    }
    public void setParameterizedClass(com.sap.tc.moin.repository.mmi.reflect.RefBaseObject newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeReference(get___CurrentConnection(), /* mofId of association */ "E0234C8C51F05DDE3E4B11DEB1390018DE1146FF", /* mofId of reference */ "E0234C8C51F05DB43E4B11DE82330018DE1146FF" , newValue, 0); //$NON-NLS-1$ //$NON-NLS-2$
    
    }
    public void setParameterizedClass(com.sap.tc.moin.repository.core.CoreConnection connection, com.sap.tc.moin.repository.mmi.reflect.RefBaseObject newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
          ___changeReference(connection, /* mofId of association */ "E0234C8C51F05DDE3E4B11DEB1390018DE1146FF", /* mofId of reference */ "E0234C8C51F05DB43E4B11DE82330018DE1146FF" , newValue, 0); //$NON-NLS-1$ //$NON-NLS-2$
    
    }

    // methods for internal attribute setter
    private void set__Name(java.lang.String newValue) {
            __name = newValue;
    }

    private void set__Description(com.sap.tc.moin.repository.core.CoreSession session, java.lang.Object newValue) {
        ___loadLinks(session, "E07264A551F762DE3E4B11DE8B180018DE1146FF" /* "description" */, newValue, 1); //$NON-NLS-1$ //$NON-NLS-2$
    }

    private void set__ValueType(boolean newValue) {
            __valueType = newValue;
    }


    // reflective methods
    public java.lang.Object refGetValue(com.sap.tc.moin.repository.core.CoreConnection connection, java.lang.String featureName) {
        if (featureName == null) {
            throw new com.sap.tc.moin.repository.mmi.reflect.InvalidNameException(featureName);
        }
        java.lang.Object result = null;
        java.lang.Integer featureId = FEATURE_IDS.get(featureName);
        if (featureId == null) {
            throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureName, refMetaObject(), "refGetValue(String)"); //$NON-NLS-1$
        }
        switch (featureId) {
            case 0: 
                result = getSubscriptions(connection);
                break;
            case 1: 
                result = getNotificationSignatures(connection);
                break;
            case 2: 
                result = getName();
                break;
            case 3: 
                result = getDescription(connection);
                break;
            case 4: 
                result = getOwnedSignatures(connection);
                break;
            case 5: 
                result = getSignaturesWithFault(connection);
                break;
            case 6: 
                result = getElementsOfType(connection);
                break;
            case 7: 
                result = getPackage(connection);
                break;
            case 8: 
                result = getAdaptedBy(connection);
                break;
            case 9: 
                result = getAdapters(connection);
                break;
            case 10: 
                result = getFormalObjectParameters(connection);
                break;
            case 11: 
                result = getConverterBetweenParametrizations(connection);
                break;
            case 12: 
                result = isValueType();
                break;
            case 13: 
                result = getActualTypeParametersForInstantiation(connection);
                break;
            case 14: 
                result = getParameterizedClass(connection);
                break;
        default:
            throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureName, refMetaObject(), "refGetValue(String)"); //$NON-NLS-1$
        }
        return result;
    }
    
    public void refSetValue(com.sap.tc.moin.repository.core.CoreConnection connection, java.lang.String featureName, java.lang.Object value) {
        if (featureName == null) {
            throw new com.sap.tc.moin.repository.mmi.reflect.InvalidNameException(featureName);
        }
        java.lang.Integer featureId = FEATURE_IDS.get(featureName);
        if (featureId == null) {
            throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureName, refMetaObject(), "refSetValue(String)"); //$NON-NLS-1$
        }
        switch (featureId) {
            case 0:
                ___changeReference(connection, "E0BC871351CA38203E4B11DEB5F50018DE1146FF" /* mofId of association */, "E0BC871351CA38173E4B11DEB8B20018DE1146FF" /* mofId of reference */, value, 1); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 1:
                ___changeReference(connection, "E0BC871351CC82003E4B11DEC6000018DE1146FF" /* mofId of association */, "E0BC871351CA38183E4B11DE80C00018DE1146FF" /* mofId of reference */, value, 1); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 2:
                ___changeDataTypeAttribute(connection, 2, "E07264A551F762DD3E4B11DE95370018DE1146FF", __name, value); //$NON-NLS-1$
                break;
                    
            case 3:
                ___changeObjectAttribute(connection, "E07264A551F762DE3E4B11DE8B180018DE1146FF", value); //$NON-NLS-1$
                break;
                    
            case 4:
                ___changeReference(connection, "E0234C8C51EB7BF13E4B11DE9A020018DE1146FF" /* mofId of association */, "E0234C8C51E931FF3E4B11DECDD30018DE1146FF" /* mofId of reference */, value, 1); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 5:
                ___changeReference(connection, "E0234C8C51E9320D3E4B11DEA3540018DE1146FF" /* mofId of association */, "E0234C8C51E476D63E4B11DEC96D0018DE1146FF" /* mofId of reference */, value, 1); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 6:
                ___changeReference(connection, "E0234C8C51EB7BC43E4B11DECAD00018DE1146FF" /* mofId of association */, "E0234C8C51E476D73E4B11DE96D60018DE1146FF" /* mofId of reference */, value, 0); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 7:
                ___changeReference(connection, "E0234C8C51EB7BCA3E4B11DE87500018DE1146FF" /* mofId of association */, "E0234C8C51E476D83E4B11DEC6F00018DE1146FF" /* mofId of reference */, value, 0); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 8:
                ___changeReference(connection, "E0234C8C51EB7BE23E4B11DEA9680018DE1146FF" /* mofId of association */, "E0234C8C51E476D93E4B11DEA9DB0018DE1146FF" /* mofId of reference */, value, 1); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 9:
                ___changeReference(connection, "E0234C8C51EB7BE53E4B11DEA6D90018DE1146FF" /* mofId of association */, "E0234C8C51E476DA3E4B11DEC6950018DE1146FF" /* mofId of reference */, value, 1); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 10:
                ___changeReference(connection, "E0234C8C51EB7BFA3E4B11DEA28E0018DE1146FF" /* mofId of association */, "E0234C8C51E476DB3E4B11DE81280018DE1146FF" /* mofId of reference */, value, 0); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 11:
                ___changeReference(connection, "E0234C8C51EDECBB3E4B11DEC0E20018DE1146FF" /* mofId of association */, "E0234C8C51E476DC3E4B11DE857B0018DE1146FF" /* mofId of reference */, value, 0); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 12:
                ___changeDataTypeAttribute(connection, 12, "E0234C8C51E476DD3E4B11DE83EC0018DE1146FF", __valueType, value); //$NON-NLS-1$
                break;
                    
            case 13:
                ___changeReference(connection, "E0234C8C51F05DCF3E4B11DEC3C50018DE1146FF" /* mofId of association */, "E0234C8C51F05DB33E4B11DEA5240018DE1146FF" /* mofId of reference */, value, 0); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
            case 14:
                ___changeReference(connection, "E0234C8C51F05DDE3E4B11DEB1390018DE1146FF" /* mofId of association */, "E0234C8C51F05DB43E4B11DE82330018DE1146FF" /* mofId of reference */, value, 0); //$NON-NLS-1$ //$NON-NLS-2$     
                break;
                    
        default:
            throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureName, null, "refSetValue(String)"); //$NON-NLS-1$
        }
    }
    
    public void set___Value(com.sap.tc.moin.repository.core.CoreSession session, java.lang.String featureName, java.lang.Object value) {
        switch (FEATURE_IDS.get(featureName)) {
            case 2:
                set__Name((java.lang.String) value);     
                break;
            case 3:
                set__Description(session, value);     
                break;
            case 12:
                set__ValueType((java.lang.Boolean) value);     
                break;
            default:
                throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureName, refMetaObject(), "set___Value(String)"); //$NON-NLS-1$
        }
    }
    
    public void set___Value(com.sap.tc.moin.repository.core.CoreSession session, int featureId, java.lang.Object value) {
        switch (featureId) {
            case 2:
                set__Name((java.lang.String) value);     
                break;
            case 3:
                set__Description(session, value);     
                break;
            case 12:
                set__ValueType((java.lang.Boolean) value);     
                break;
            default:
                throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureId, refMetaObject(), "set___Value(int)"); //$NON-NLS-1$
        }
    }
    
    public void addOrSet___Value(com.sap.tc.moin.repository.core.CoreSession session, java.lang.String featureName, java.lang.Object value) {
        switch (FEATURE_IDS.get(featureName)) {
            case 2:
                set__Name((java.lang.String) value);     
                break;
            case 3:
                set__Description(session, value);         
                break;
            case 12:
                set__ValueType((java.lang.Boolean) value);     
                break;
            default:
                throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(featureName, refMetaObject(), "addOrSet___Value(String)"); //$NON-NLS-1$
        }
    }    
    


    public void set___AssociationLink( String associationEndMofId, com.sap.tc.moin.repository.core.EndStorageLink value ) {
        if ( associationEndMofId == "E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF" ) { __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF = value; return; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF" ) { __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF = value; return; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF" ) { __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF = value; return; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E05D452A520349883E4B11DEA7B40018DE1146FF" ) { __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF = value; return; } //$NON-NLS-1$ 
    }
    
    public com.sap.tc.moin.repository.core.EndStorageLink get___AssociationLink( String associationEndMofId ) {
        if ( associationEndMofId == "E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF" ) { return __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF" ) { return __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF" ) { return __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E05D452A520349883E4B11DEA7B40018DE1146FF" ) { return __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF; } //$NON-NLS-1$ 
        return null;
    }
    public void set___AttributeLink( String attributeMofId, com.sap.tc.moin.repository.core.EndStorageLink value ) {
        if ( attributeMofId == "E07264A551F762DE3E4B11DE8B180018DE1146FF" ) { __description = value; return; } //$NON-NLS-1$ 
    }

    public com.sap.tc.moin.repository.core.EndStorageLink get___AttributeLink( String attributeMofId ) {
        if ( attributeMofId == "E07264A551F762DE3E4B11DE8B180018DE1146FF" ) { return __description; } //$NON-NLS-1$ 
        return null;
    }
    public java.util.List<com.sap.tc.moin.repository.core.EndStorageLink> get___AllStoredLinks( ) {
        java.util.List<com.sap.tc.moin.repository.core.EndStorageLink> result = null;
        if ( __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF); } 
        if ( __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF); } 
        if ( __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF); } 
        if ( __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF); } 
        if ( __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.addAll( __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF); } 
        if ( __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.addAll( __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF); } 
        if ( __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.addAll( __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF); } 
        if ( __description != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __description); } 
        return result;

    }

    public java.util.List<com.sap.tc.moin.repository.core.EndStorageLink> get___AllStoredAssociationLinks( ) {
        java.util.List<com.sap.tc.moin.repository.core.EndStorageLink> result = null;
        if ( __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF); } 
        if ( __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF); } 
        if ( __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF); } 
        if ( __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF); } 
        if ( __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.addAll( __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF); } 
        if ( __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.addAll( __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF); } 
        if ( __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.addAll( __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF); } 
        return result;

    }
    public java.util.Collection<com.sap.tc.moin.repository.core.EndStorageLink> get___AssociationLinks( String associationEndMofId ) {
        if ( associationEndMofId == "E0234C8C51EB7BF03E4B11DEA1770018DE1146FF" ) { return __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF" ) { return __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF" ) { return __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF; } //$NON-NLS-1$ 
        return null;
    }

    public void set___AssociationLinks( java.util.Collection<com.sap.tc.moin.repository.core.EndStorageLink> links, String associationEndMofId ) {
        if ( associationEndMofId == "E0234C8C51EB7BF03E4B11DEA1770018DE1146FF" ) { __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF = links; return; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF" ) { __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF = links; return; } //$NON-NLS-1$ 
        if ( associationEndMofId == "E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF" ) { __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF = links; return; } //$NON-NLS-1$ 
    }    
    public java.util.List<com.sap.tc.moin.repository.core.EndStorageLink> clear___AllLinks( ) {
        reset___CompositeParentLink( );
        java.util.List<com.sap.tc.moin.repository.core.EndStorageLink> result = null;
        if ( __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF); __A_package__classes_package__E0234C8C51EB7BC83E4B11DE9BD50018DE1146FF = null; } 
        if ( __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF); __ParameterizedClassDeclaration_parameterization_E0234C8C51F05DD13E4B11DE8C7C0018DE1146FF = null; } 
        if ( __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF); __A_parameterizedClass_parameterizedClassInstantiation_parameterizedClass_E0234C8C51F05DDC3E4B11DE9E9F0018DE1146FF = null; } 
        if ( __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF); __A_abapAnnotation_sapClass_abapAnnotation_E05D452A520349883E4B11DEA7B40018DE1146FF = null; } 
        if ( __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.addAll( __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF); __OwnedSignatures_ownedSignatures_E0234C8C51EB7BF03E4B11DEA1770018DE1146FF = null; } 
        if ( __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.addAll( __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF); __A_formalObjectParameters_parameterOfClass_formalObjectParameters_E0234C8C51EB7BF83E4B11DECDEB0018DE1146FF = null; } 
        if ( __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.addAll( __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF); __A_actualTypeParametersForInstantiation_parameterizedClassInstantiation_actualTypeParametersForInstantiation_E0234C8C51F05DCD3E4B11DEBC5A0018DE1146FF = null; } 
        if ( __description != null ) { if ( result == null ) result = new java.util.ArrayList<com.sap.tc.moin.repository.core.EndStorageLink>( ); result.add( __description); __description = null; } 
        return result;

    }
    // get the JMI interface
    public java.lang.Class<data.generics.ParameterizedClassInstantiation> get___JmiInterface() {
        return data.generics.ParameterizedClassInstantiation.class;
    }

    // create the wrapper
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<data.generics.__impl.ParameterizedClassInstantiationImpl> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new data.generics.__impl.ParameterizedClassInstantiationWrapper(conn, this, synchronize);
    }
    
}