<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scopeProvider"
    nsURI="http://de.hpi.sam.bp2009.solution.scopeProvider" nsPrefix="solution.scopeProvider">
  <eClassifiers xsi:type="ecore:EClass" name="ProjectBasedScopeProvider" eSuperTypes="#//ScopeProvider">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Implementation of the ScopeProvider, identifies Forward and BackwardScope via EclipseProject references"/>
    </eAnnotations>
    <eOperations name="setupForEObjects">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set the initialprojects based on eObjects"/>
      </eAnnotations>
      <eParameters name="initialObjects" lowerBound="1" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="setupForResources">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set the initialprojects based on resources"/>
      </eAnnotations>
      <eParameters name="initialResources" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
    </eOperations>
    <eOperations name="setupForResourceSets">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set the initialprojects based on resourceset, iterating overall resources"/>
      </eAnnotations>
      <eParameters name="initialResourceSets" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"/>
    </eOperations>
    <eOperations name="getForwardScopeAsEObjects" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ScopeProvider tries to load all resources from the referenced projects with an XMIResourceImpl.&#xD;&#xA;Attention: No instance equality provided, when resources are not in the inMemory list."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getForwardScopeAsProjects" upperBound="-1" eType="#//IProject"/>
    <eOperations name="getForwardScopeAsResources" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
    <eOperations name="getForwardScopeAsURIs" upperBound="-1" eType="#//URI"/>
    <eOperations name="getBackwardScopeAsEObjects" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ScopeProvider tries to load all resources from the referenced projects with an XMIResourceImpl.&#xD;&#xA;Attention: No instance equality provided, when resources are not in the inMemory list."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getBackwardScopeAsProjects" upperBound="-1" eType="#//IProject"/>
    <eOperations name="getBackwardScopeAsResources" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
    <eOperations name="getBackwardScopeAsURIs" upperBound="-1" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialProjects" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//IProject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IProject" instanceClassName="org.eclipse.core.resources.IProject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeProvider" abstract="true" interface="true">
    <eOperations name="setupForEObjects">
      <eParameters name="initialObjects" lowerBound="1" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="setupForResources">
      <eParameters name="initialResources" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
    </eOperations>
    <eOperations name="setupForResourceSets">
      <eParameters name="initialResourceSets" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"/>
    </eOperations>
    <eOperations name="getForwardScopeAsEObjects" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eOperations name="getForwardScopeAsURIs" upperBound="-1" eType="#//URI"/>
    <eOperations name="getBackwardScopeAsEObjects" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eOperations name="getBackwardScopeAsURIs" upperBound="-1" eType="#//URI"/>
    <eOperations name="setInMemoryResources">
      <eParameters name="resources" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
    </eOperations>
    <eOperations name="getInMemoryResources" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"/>
  </eClassifiers>
</ecore:EPackage>
