/**
 * Generated by the MOIN Generator Version 3.0
 **/

package data.classes;
/**
 * This interface is not intended to be implemented by clients.
 */
public interface ATypeAssociationEnd extends com.sap.tc.moin.repository.mmi.reflect.RefAssociation
{
    // association extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<data.classes.ATypeAssociationEnd> ASSOCIATION_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.AssociationDescriptor<data.classes.ATypeAssociationEnd>("E0234C8C51EB7BD03E4B11DECD570018DE1146FF", "sap.com/moin/mm/ap/core", "data", "classes", "A_type_associationEnd"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 


    // association interface
    public boolean exists(data.classes.ClassTypeDefinition _Type, data.classes.AssociationEnd _AssociationEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public data.classes.ClassTypeDefinition getType(data.classes.AssociationEnd _AssociationEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public data.classes.AssociationEnd getAssociationEnd(data.classes.ClassTypeDefinition _Type) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean add(data.classes.ClassTypeDefinition _Type, data.classes.AssociationEnd _AssociationEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public boolean remove(data.classes.ClassTypeDefinition _Type, data.classes.AssociationEnd _AssociationEnd) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
}