<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petriNet"
    nsURI="http://petriNet/1.0" nsPrefix="petriNet">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="modelName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="modelName" value="self.elements->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="10"
        upperBound="-1" eType="#//Element" containment="true" eOpposite="#//Element/diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Petri Net 1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//PetriNet" eOpposite="#//PetriNet/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="numberOfTokens"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="numberOfTokens" value="self.noTokens > 3"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noTokens" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hiddenOpposite" eType="#//Transition">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml">
        <details key="Property.oppositeRoleName" value="transition2Place"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arc" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/outgoingArcs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/incomingArcs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingArcs" eType="#//Arc"
        eOpposite="#//Arc/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingArcs" eType="#//Arc"
        eOpposite="#//Arc/target"/>
  </eClassifiers>
</ecore:EPackage>
