<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="links"
    nsURI="http://sap.com/moin/links" nsPrefix="links">
  <eAnnotations source="http://sap.com/MOIN">
    <details key="links.PictogramLink" value="//PictogramLink"/>
    <details key="links.PictogramElementContainsPictogramLink" value="//PictogramLink/pictogramElement"/>
    <details key="links.DiagramLinkReferencesPictogramLinks" value="//DiagramLink/pictogramLinks"/>
    <details key="links.PictogramLinkReferencesBusinessObjects" value="//PictogramLink/businessObjects"/>
    <details key="links.DiagramLink" value="//DiagramLink"/>
    <details key="links.DiagramLinkReferencesDiagram" value="//DiagramLink/diagram"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PictogramLink" eSuperTypes="pictograms.ecore#//PropertyContainer">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="links.PictogramLink"/>
      <details key="metaObjectMofId" value="45E806E357AEC9BF0C7D4C3417DA8693C081773B"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" ordered="false"
        unique="false" eType="ecore:EClass pictograms.ecore#//PictogramElement" eOpposite="pictograms.ecore#//PictogramElement/link">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="links.PictogramElementContainsPictogramLink"/>
        <details key="metaObjectMofId" value="45E806E3A923DD06475A493C25D3E37647D0913C"/>
        <details key="storedEnd" value="0"/>
        <details key="compositeEnd" value="0"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramLink" ordered="false"
        unique="false" lowerBound="1" eType="#//DiagramLink" eOpposite="#//DiagramLink/pictogramLinks">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="links.DiagramLinkReferencesPictogramLinks"/>
        <details key="metaObjectMofId" value="45E806E369DC288747324E4122F8E53651800C8C"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessObjects" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="links.PictogramLinkReferencesBusinessObjects"/>
        <details key="metaObjectMofId" value="45E806E30284FE5FB2DF4EEE3C28FAD397F8DCD7"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="0"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramLink">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="links.DiagramLink"/>
      <details key="metaObjectMofId" value="45E806E3F50C9691A7AD41B1112AD1FB129489D9"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" ordered="false"
        unique="false" eType="ecore:EClass pictograms.ecore#//Diagram">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="links.DiagramLinkReferencesDiagram"/>
        <details key="metaObjectMofId" value="45E806E34864C34AAB914D1B0575B8FF0AE0200F"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramLinks" ordered="false"
        upperBound="-1" eType="#//PictogramLink" eOpposite="#//PictogramLink/diagramLink">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="links.DiagramLinkReferencesPictogramLinks"/>
        <details key="metaObjectMofId" value="45E806E369DC288747324E4122F8E53651800C8C"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
