<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pictograms"
    nsURI="http://sap.com/moin/pictograms" nsPrefix="pictograms">
  <eAnnotations source="http://sap.com/MOIN">
    <details key="pictograms.Shape" value="//Shape"/>
    <details key="pictograms.ContainershapeContainsShapes" value="//ContainerShape/children"/>
    <details key="pictograms.ContainerShape" value="//ContainerShape"/>
    <details key="pictograms.Diagram" value="//Diagram"/>
    <details key="pictograms.DiagramAggregatesConnections" value="//Connection/parent"/>
    <details key="pictograms.DiagramContainsColors" value="//Diagram/colors"/>
    <details key="pictograms.GraphicsAlgorithmContainsGraphicsAlgorithms" value="//GraphicsAlgorithm/parentGraphicsAlgorithm"/>
    <details key="pictograms.PictogramelementContainsGraphicsalgorithm" value="//PictogramElement/graphicsAlgorithm"/>
    <details key="pictograms.GraphicsAlgorithmReferencesStyle" value="//GraphicsAlgorithm/style"/>
    <details key="pictograms.Polyline" value="//Polyline"/>
    <details key="pictograms.Ellipse" value="//Ellipse"/>
    <details key="links.PictogramElementContainsPictogramLink" value="//PictogramElement/link"/>
    <details key="pictograms.Connection" value="//Connection"/>
    <details key="pictograms.ConnectionStartsAtAnchor" value="//Anchor/outgoingConnections"/>
    <details key="pictograms.ConnectionEndsAtAnchor" value="//Anchor/incomingConnections"/>
    <details key="pictograms.ConnectionContainsConnectionDecorators" value="//ConnectionDecorator/connection"/>
    <details key="pictograms.AnchorcontainerAggregatesAnchors" value="//AnchorContainer/anchors"/>
    <details key="pictograms.GraphicsAlgorithmForAnchor" value="//Anchor/referencedGraphicsAlgorithm"/>
    <details key="pictograms.HorizontalConnection" value="//HorizontalConnection"/>
    <details key="pictograms.VerticalConnection" value="//VerticalConnection"/>
    <details key="pictograms.FixPointAnchor" value="//FixPointAnchor"/>
    <details key="pictograms.BoxRelativeAnchor" value="//BoxRelativeAnchor"/>
    <details key="pictograms.ChopboxAnchor" value="//ChopboxAnchor"/>
    <details key="pictograms.LinkToDiagram" value="//LinkToDiagram"/>
    <details key="pictograms.DiagramlinkReferencesDiagram" value="//LinkToDiagram/diagram"/>
    <details key="pictograms.Property" value="//Property"/>
    <details key="pictograms.Text" value="//Text"/>
    <details key="pictograms.ConnectionDecorator" value="//ConnectionDecorator"/>
    <details key="pictograms.FreeFormConnection" value="//FreeFormConnection"/>
    <details key="pictograms.DirectConnection" value="//DirectConnection"/>
    <details key="pictograms.ManhattanConnection" value="//ManhattanConnection"/>
    <details key="pictograms.Polygon" value="//Polygon"/>
    <details key="pictograms.Rectangle" value="//Rectangle"/>
    <details key="pictograms.RoundedRectangle" value="//RoundedRectangle"/>
    <details key="pictograms.Font" value="//Font"/>
    <details key="pictograms.RenderingStyle" value="//RenderingStyle"/>
    <details key="pictograms.Image" value="//Image"/>
    <details key="pictograms.FanConnection" value="//FanConnection"/>
    <details key="pictograms.PlatformGraphicsAlgorithm" value="//PlatformGraphicsAlgorithm"/>
    <details key="pictograms.MultiText" value="//MultiText"/>
    <details key="pictograms.Button" value="//Button"/>
    <details key="pictograms.StyleContainerContainsStyles" value="//Style/styleContainer"/>
    <details key="pictograms.Style" value="//Style"/>
    <details key="pictograms.GraphicsAlgorithmHasBackgroundColor" value="//AbstractStyle/background"/>
    <details key="pictograms.GraphicsAlgorithmHasForegroundColor" value="//AbstractStyle/foreground"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Shape" eSuperTypes="#//AnchorContainer">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Shape"/>
      <details key="metaObjectMofId" value="45E806E31FD033AD65384259299DEBAA310F446D"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" ordered="false"
        unique="false" eType="#//ContainerShape" eOpposite="#//ContainerShape/children">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.ContainershapeContainsShapes"/>
        <details key="metaObjectMofId" value="45E806E34DAA68EC93FA462426FBB19CF45B7D2E"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="0"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerShape" eSuperTypes="#//Shape">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.ContainerShape"/>
      <details key="metaObjectMofId" value="45E806E37581995B8D82418E1867F74ADBD2C64E"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Shape" containment="true" eOpposite="#//Shape/container">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.ContainershapeContainsShapes"/>
        <details key="metaObjectMofId" value="45E806E34DAA68EC93FA462426FBB19CF45B7D2E"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="0"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//ContainerShape #//StyleContainer">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Diagram"/>
      <details key="metaObjectMofId" value="45E806E3B28EF07AFA0A4F2C342AC45B58528277"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gridUnit" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramTypeId" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" ordered="false"
        upperBound="-1" eType="#//Connection" containment="true" eOpposite="#//Connection/parent">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.DiagramAggregatesConnections"/>
        <details key="metaObjectMofId" value="45E806E391102595F404410628AEB33F0B572BA1"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="snapToGrid" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showGuides" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colors" ordered="false"
        upperBound="-1" eType="ecore:EClass datatypes.ecore#//Color" containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.DiagramContainsColors"/>
        <details key="metaObjectMofId" value="45E806E346B62DC200B947272E8FDE657EE11680"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphicsAlgorithm" abstract="true" eSuperTypes="#//GraphicsAlgorithmContainer #//AbstractStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphicsAlgorithmChildren"
        upperBound="-1" eType="#//GraphicsAlgorithm" containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.GraphicsAlgorithmContainsGraphicsAlgorithms"/>
        <details key="metaObjectMofId" value="45E806E369D37BBE0A1A4E2E3EEFCF9F8305FE0A"/>
        <details key="storedEnd" value="0"/>
        <details key="compositeEnd" value="0"/>
        <details key="orderedEnd" value="1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentGraphicsAlgorithm"
        ordered="false" unique="false" eType="#//GraphicsAlgorithm">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.GraphicsAlgorithmContainsGraphicsAlgorithms"/>
        <details key="metaObjectMofId" value="45E806E369D37BBE0A1A4E2E3EEFCF9F8305FE0A"/>
        <details key="storedEnd" value="0"/>
        <details key="compositeEnd" value="0"/>
        <details key="orderedEnd" value="1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" ordered="false"
        unique="false" eType="#//PictogramElement" eOpposite="#//PictogramElement/graphicsAlgorithm">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.PictogramelementContainsGraphicsalgorithm"/>
        <details key="metaObjectMofId" value="45E806E3FAA2BB1CBA6D4FD32BB3E5E85E90D191"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" ordered="false"
        unique="false" eType="#//Style">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.GraphicsAlgorithmReferencesStyle"/>
        <details key="metaObjectMofId" value="46973F2C80C28094311F11DCB45C001125D59A18"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polyline" eSuperTypes="#//GraphicsAlgorithm">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Polyline"/>
      <details key="metaObjectMofId" value="45E806E3D229789CCBAB417F1E1AD3B2356BC7B0"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" unique="false"
        upperBound="-1" eType="ecore:EClass datatypes.ecore#//Point" containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="ovaMofId" value="45E806E3EA39201CFDF3490C1CA8F41B3C01A5A3"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ellipse" eSuperTypes="#//GraphicsAlgorithm">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Ellipse"/>
      <details key="metaObjectMofId" value="45E806E382BF5E26C64846B90538E8C23BABA3D0"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PictogramElement" abstract="true" eSuperTypes="#//GraphicsAlgorithmContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphicsAlgorithm" ordered="false"
        unique="false" eType="#//GraphicsAlgorithm" containment="true" eOpposite="#//GraphicsAlgorithm/pictogramElement">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.PictogramelementContainsGraphicsalgorithm"/>
        <details key="metaObjectMofId" value="45E806E3FAA2BB1CBA6D4FD32BB3E5E85E90D191"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" ordered="false" unique="false"
        eType="ecore:EClass links.ecore#//PictogramLink" containment="true" eOpposite="links.ecore#//PictogramLink/pictogramElement">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="links.PictogramElementContainsPictogramLink"/>
        <details key="metaObjectMofId" value="45E806E3A923DD06475A493C25D3E37647D0913C"/>
        <details key="storedEnd" value="0"/>
        <details key="compositeEnd" value="0"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//AnchorContainer">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Connection"/>
      <details key="metaObjectMofId" value="45E806E34BDA2F4E9E294E9E3D77B2B1C73C6FF3"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" ordered="false"
        unique="false" lowerBound="1" eType="#//Anchor" eOpposite="#//Anchor/outgoingConnections">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.ConnectionStartsAtAnchor"/>
        <details key="metaObjectMofId" value="45E806E308B17408B49D40731BCBA3D70B50316A"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" ordered="false" unique="false"
        lowerBound="1" eType="#//Anchor" eOpposite="#//Anchor/incomingConnections">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.ConnectionEndsAtAnchor"/>
        <details key="metaObjectMofId" value="45E806E3EEA012BCF524491F27BACC87C8BA3CFC"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false"
        unique="false" lowerBound="1" eType="#//Diagram" eOpposite="#//Diagram/connections">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.DiagramAggregatesConnections"/>
        <details key="metaObjectMofId" value="45E806E391102595F404410628AEB33F0B572BA1"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionDecorators" ordered="false"
        upperBound="-1" eType="#//ConnectionDecorator" containment="true" eOpposite="#//ConnectionDecorator/connection">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.ConnectionContainsConnectionDecorators"/>
        <details key="metaObjectMofId" value="45E806E32B4E1991DC38488135D0E28ED9340535"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anchor" abstract="true" eSuperTypes="#//PictogramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false"
        unique="false" lowerBound="1" eType="#//AnchorContainer" eOpposite="#//AnchorContainer/anchors">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.AnchorcontainerAggregatesAnchors"/>
        <details key="metaObjectMofId" value="45E806E3C1BD2143396B4C431D6F8DCA605AD011"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections" ordered="false"
        upperBound="-1" eType="#//Connection" eOpposite="#//Connection/start">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.ConnectionStartsAtAnchor"/>
        <details key="metaObjectMofId" value="45E806E308B17408B49D40731BCBA3D70B50316A"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections" ordered="false"
        upperBound="-1" eType="#//Connection" eOpposite="#//Connection/end">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.ConnectionEndsAtAnchor"/>
        <details key="metaObjectMofId" value="45E806E3EEA012BCF524491F27BACC87C8BA3CFC"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedGraphicsAlgorithm"
        ordered="false" unique="false" eType="#//GraphicsAlgorithm">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.GraphicsAlgorithmForAnchor"/>
        <details key="metaObjectMofId" value="47DF8B0D8E951440F4CD11DC8C9A00199928CEAA"/>
        <details key="storedEnd" value="0"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HorizontalConnection" eSuperTypes="#//Connection">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.HorizontalConnection"/>
      <details key="metaObjectMofId" value="45E806E38B966C7ACD064C7E26CBFFB2AC414881"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerticalConnection" eSuperTypes="#//Connection">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.VerticalConnection"/>
      <details key="metaObjectMofId" value="45E806E377017573A2EB481B300CB48BF32B74E6"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnchorContainer" abstract="true" eSuperTypes="#//PictogramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anchors" ordered="false"
        upperBound="-1" eType="#//Anchor" containment="true" eOpposite="#//Anchor/parent">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.AnchorcontainerAggregatesAnchors"/>
        <details key="metaObjectMofId" value="45E806E3C1BD2143396B4C431D6F8DCA605AD011"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixPointAnchor" eSuperTypes="#//Anchor">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.FixPointAnchor"/>
      <details key="metaObjectMofId" value="45E806E35563C79C230D4CEE19FCE0CF5256B988"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass datatypes.ecore#//Point"
        containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="ovaMofId" value="45E806E325AD2A8F55174A461CE6F7012FF0A6E8"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoxRelativeAnchor" eSuperTypes="#//Anchor">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.BoxRelativeAnchor"/>
      <details key="metaObjectMofId" value="45E806E3770EC34F9202447F2114AAE130DEF429"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeWidth" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeHeight" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChopboxAnchor" eSuperTypes="#//Anchor">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.ChopboxAnchor"/>
      <details key="metaObjectMofId" value="45E806E3940A148E39184EB42774A56C14F847CD"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkToDiagram" eSuperTypes="#//Shape">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.LinkToDiagram"/>
      <details key="metaObjectMofId" value="45E806E324E75070FD2145593F95CDF2F3811E63"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="viewport"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="asIcon" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewport" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass datatypes.ecore#//ViewPort"
        containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="ovaMofId" value="45E806E31FD78E12512E47EA2D1DD8F3E74FE083"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" ordered="false"
        unique="false" lowerBound="1" eType="#//Diagram">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.DiagramlinkReferencesDiagram"/>
        <details key="metaObjectMofId" value="45E806E314D20B4B83F745B22FD0B27601F9FA3F"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Property"/>
      <details key="metaObjectMofId" value="473ABD0053C656A2929211DCA3AB8000600FE800"/>
      <details key="isStructureType" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//AbstractText">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Text"/>
      <details key="metaObjectMofId" value="45E806E3A3CF4A417DA2471C338590FC98B94E68"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle,font"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionDecorator" eSuperTypes="#//Shape">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.ConnectionDecorator"/>
      <details key="metaObjectMofId" value="45E806E3823C2857C9934BCF2144E2FB68FB4D69"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationRelative" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" ordered="false"
        unique="false" lowerBound="1" eType="#//Connection" eOpposite="#//Connection/connectionDecorators">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.ConnectionContainsConnectionDecorators"/>
        <details key="metaObjectMofId" value="45E806E32B4E1991DC38488135D0E28ED9340535"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FreeFormConnection" eSuperTypes="#//Connection">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.FreeFormConnection"/>
      <details key="metaObjectMofId" value="45E806E39F302197BFF04AA81DC1DEDE91076514"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendpoints" unique="false"
        upperBound="-1" eType="ecore:EClass datatypes.ecore#//Point" containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="ovaMofId" value="45E806E34A8CEEF1411042793FD8C6DDB18CCCAE"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectConnection" eSuperTypes="#//Connection">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.DirectConnection"/>
      <details key="metaObjectMofId" value="45E806E353DACCAE5C3B41D20414CA21B36C4F6D"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManhattanConnection" eSuperTypes="#//Connection">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.ManhattanConnection"/>
      <details key="metaObjectMofId" value="45E806E33F84C88EB1A645892BC1EE9F1052B938"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polygon" eSuperTypes="#//Polyline">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Polygon"/>
      <details key="metaObjectMofId" value="45E806E39CA8988B64AE496E1611E79464444C32"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineStyle">
    <eLiterals name="SOLID"/>
    <eLiterals name="DASH" value="1"/>
    <eLiterals name="DASHDOT" value="2"/>
    <eLiterals name="DASHDOTDOT" value="3"/>
    <eLiterals name="DOT" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Orientation">
    <eLiterals name="ALIGNMENT_CENTER"/>
    <eLiterals name="ALIGNMENT_LEFT" value="1"/>
    <eLiterals name="ALIGNMENT_TOP" value="2"/>
    <eLiterals name="ALIGNMENT_RIGHT" value="3"/>
    <eLiterals name="ALIGNMENT_BOTTOM" value="4"/>
    <eLiterals name="ALIGNMENT_MIDDLE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle" eSuperTypes="#//GraphicsAlgorithm">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Rectangle"/>
      <details key="metaObjectMofId" value="45E806E37120AD4D7CC74AC23483FCA2046A785F"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoundedRectangle" eSuperTypes="#//GraphicsAlgorithm">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.RoundedRectangle"/>
      <details key="metaObjectMofId" value="45E806E30B111639635B45AD24A896FDC10DD7D2"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerHeight" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerWidth" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Font">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Font"/>
      <details key="metaObjectMofId" value="45E806E35856AAF1B14B4F923905D5D6147B02C7"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenderingStyle">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.RenderingStyle"/>
      <details key="metaObjectMofId" value="45E806E35FC54737B8C242AB002CC014A8DEA9DF"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefinedStyleId" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//GraphicsAlgorithm">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Image"/>
      <details key="metaObjectMofId" value="45E806E353FEC7AFE8BF4ED114A7CEA6587A9600"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stretchH" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stretchV" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proportional" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanConnection" eSuperTypes="#//Connection">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.FanConnection"/>
      <details key="metaObjectMofId" value="45E806E3E04CBB1D866449380C09A19B3BE988A0"/>
      <details key="isStructureType" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatformGraphicsAlgorithm" eSuperTypes="#//GraphicsAlgorithm">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.PlatformGraphicsAlgorithm"/>
      <details key="metaObjectMofId" value="45E806E3DCA40CA8B8CC42F80403A99DE69FEBE3"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphicsAlgorithmContainer" abstract="true"
      eSuperTypes="#//PropertyContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractText" abstract="true" eSuperTypes="#//GraphicsAlgorithm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" ordered="false" unique="false"
        eType="#//Font" containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="ovaMofId" value="4649B449A3ED98C2F1F7486719AAA46038E0EF38"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalAlignment" ordered="false"
        unique="false" eType="#//Orientation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalAlignment" ordered="false"
        unique="false" eType="#//Orientation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiText" eSuperTypes="#//AbstractText">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.MultiText"/>
      <details key="metaObjectMofId" value="4649B449B306D1A783B7407702D58FB97D352380"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle,font"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" ordered="false"
        unique="false" upperBound="-1" eType="#//Property" containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="ovaMofId" value="473ABD0053CAEA80929211DCAE4D8000600FE800"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexGraphicsAlgorithm" abstract="true"
      eSuperTypes="#//GraphicsAlgorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//ComplexGraphicsAlgorithm">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Button"/>
      <details key="metaObjectMofId" value="4649B449FB1C7CC4A0404A0734699248CFBD3374"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a1" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a2" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a3" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StyleContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="styles" ordered="false"
        upperBound="-1" eType="#//Style" containment="true" eOpposite="#//Style/styleContainer">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.StyleContainerContainsStyles"/>
        <details key="metaObjectMofId" value="46973F2C80C28091311F11DCAD2F001125D59A18"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Style" eSuperTypes="#//StyleContainer #//AbstractStyle">
    <eAnnotations source="http://sap.com/MOIN">
      <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
      <details key="metaObject" value="pictograms.Style"/>
      <details key="metaObjectMofId" value="46973F2C80BDECBB311F11DCC8D8001125D59A18"/>
      <details key="isStructureType" value="false"/>
      <details key="ova" value="renderingStyle,font"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" ordered="false" unique="false"
        eType="#//Font" containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="ovaMofId" value="46973F2C80BDECB2311F11DC9519001125D59A18"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalAlignment" ordered="false"
        unique="false" eType="#//Orientation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalAlignment" ordered="false"
        unique="false" eType="#//Orientation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stretchH" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stretchV" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proportional" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="styleContainer" ordered="false"
        unique="false" lowerBound="1" eType="#//StyleContainer" eOpposite="#//StyleContainer/styles">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.StyleContainerContainsStyles"/>
        <details key="metaObjectMofId" value="46973F2C80C28091311F11DCAD2F001125D59A18"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStyle" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" ordered="false"
        unique="false" eType="ecore:EClass datatypes.ecore#//Color">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.GraphicsAlgorithmHasBackgroundColor"/>
        <details key="metaObjectMofId" value="45E806E39B5A5621D3A049D41BDCF825E4F1DFCD"/>
        <details key="storedEnd" value="0"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreground" ordered="false"
        unique="false" eType="ecore:EClass datatypes.ecore#//Color">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="metamodels" value="sap.com/com/sap/mi/gfw/mm[1.0]"/>
        <details key="metaObject" value="pictograms.GraphicsAlgorithmHasForegroundColor"/>
        <details key="metaObjectMofId" value="45E806E339C380ACB9D54742385FA5A67110FC14"/>
        <details key="storedEnd" value="1"/>
        <details key="compositeEnd" value="-1"/>
        <details key="orderedEnd" value="-1"/>
        <details key="exposedEndNumber" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineWidth" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineStyle" ordered="false"
        unique="false" eType="#//LineStyle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filled" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineVisible" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="renderingStyle" ordered="false"
        unique="false" eType="#//RenderingStyle" containment="true">
      <eAnnotations source="http://sap.com/MOIN">
        <details key="ovaMofId" value="46973F2C80BDECC2311F11DCC6FC001125D59A18"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transparency" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
</ecore:EPackage>
