/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.component.view.__impl;

public class AUielementPropertyUIelementContextBindingWrapper extends com.sap.tc.moin.repository.core.jmi.reflect.RefAssociationWrapperImpl<com.sap.ide.metamodel.webdynpro.component.view.AUielementPropertyUIelementContextBinding> implements com.sap.ide.metamodel.webdynpro.component.view.AUielementPropertyUIelementContextBinding,com.sap.tc.moin.repository.Partitionable
{

    /**
     * The AUielementPropertyUIelementContextBinding wrapper
     */
    public AUielementPropertyUIelementContextBindingWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, com.sap.ide.metamodel.webdynpro.component.view.__impl.AUielementPropertyUIelementContextBindingImpl baseObject, boolean synchronize) {
        super(conn, baseObject, synchronize);
    }
    
    private com.sap.ide.metamodel.webdynpro.component.view.__impl.AUielementPropertyUIelementContextBindingImpl getCastWrappedObject() {
        return (com.sap.ide.metamodel.webdynpro.component.view.__impl.AUielementPropertyUIelementContextBindingImpl) getWrappedObject();
    }

    public com.sap.ide.metamodel.webdynpro.component.view.AUielementPropertyUIelementContextBinding unwrap() {
        return (com.sap.ide.metamodel.webdynpro.component.view.AUielementPropertyUIelementContextBinding) getWrappedObject();
    }
    
    public boolean exists(com.sap.ide.metamodel.webdynpro.framework.uielib.AbstractViewElementPropertyDef _UielementProperty, com.sap.ide.metamodel.webdynpro.component.view.UielementContextBinding _UIelementContextBinding) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UielementProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UIelementContextBinding));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().exists(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UielementProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UIelementContextBinding)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public com.sap.ide.metamodel.webdynpro.framework.uielib.AbstractViewElementPropertyDef getUielementProperty(com.sap.ide.metamodel.webdynpro.component.view.UielementContextBinding _UIelementContextBinding) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (com.sap.ide.metamodel.webdynpro.framework.uielib.AbstractViewElementPropertyDef) wrapResult(getCastWrappedObject().getUielementProperty(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UIelementContextBinding)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (com.sap.ide.metamodel.webdynpro.framework.uielib.AbstractViewElementPropertyDef) wrapResult(getCastWrappedObject().getUielementProperty(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UIelementContextBinding))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public java.util.Collection getUIelementContextBinding(com.sap.ide.metamodel.webdynpro.framework.uielib.AbstractViewElementPropertyDef _UielementProperty) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronizationManager.acquireReadLock();
                try {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return (java.util.Collection) wrapResult(getCastWrappedObject().getUIelementContextBinding(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UielementProperty)));
                } finally {
                    synchronizationManager.releaseReadLock();
                }
       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return (java.util.Collection) wrapResult(getCastWrappedObject().getUIelementContextBinding(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UielementProperty))); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean add(com.sap.ide.metamodel.webdynpro.framework.uielib.AbstractViewElementPropertyDef _UielementProperty, com.sap.ide.metamodel.webdynpro.component.view.UielementContextBinding _UIelementContextBinding) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UielementProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UIelementContextBinding));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().add(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UielementProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UIelementContextBinding)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }
    public boolean remove(com.sap.ide.metamodel.webdynpro.framework.uielib.AbstractViewElementPropertyDef _UielementProperty, com.sap.ide.metamodel.webdynpro.component.view.UielementContextBinding _UIelementContextBinding) throws com.sap.tc.moin.repository.mmi.reflect.JmiException
    {
        try {
            if (synchronize) {
                synchronized (synchronizationManager.getProhibitWriteSyncObject()) {
                    assertConnectionAlive();
                    attachConnectionIfRequired();
                    return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UielementProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UIelementContextBinding));
                }       
            }
            assertConnectionAlive();
            attachConnectionIfRequired();
            return getCastWrappedObject().remove(connection, unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UielementProperty), unwrapArg((com.sap.tc.moin.repository.mmi.reflect.RefBaseObject) _UIelementContextBinding)); 
        } catch (com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            wrapJmiExceptionArgs(ex);
            throw ex;
        }
    }   

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.webdynpro.component.view.AUielementPropertyUIelementContextBinding> get___JmiInterface() {
        return com.sap.ide.metamodel.webdynpro.component.view.AUielementPropertyUIelementContextBinding.class;
    }

    protected String metaObjectToString() {
        return "com.sap.ide.metamodel.webdynpro.component.view.AUielementPropertyUIelementContextBinding (Java Type)\nWebDynpro.component.view.A_UIElementProperty_uIElementContextBinding (MOF Type)"; //$NON-NLS-1$
    }    
}