/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.ide.metamodel.webdynpro.component.view.__impl;

public final class ViewPackageImpl extends com.sap.tc.moin.repository.core.jmi.reflect.RefPackageImpl
{
        
    public static final java.util.Map<java.lang.String, java.lang.Integer> FEATURE_IDS;

    static {
        
        FEATURE_IDS = new java.util.HashMap<java.lang.String, java.lang.Integer>(31);
        FEATURE_IDS.put("uielement", Integer.valueOf(0)); //$NON-NLS-1$
        FEATURE_IDS.put("View", Integer.valueOf(1)); //$NON-NLS-1$
        FEATURE_IDS.put("ViewContainer", Integer.valueOf(2)); //$NON-NLS-1$
        FEATURE_IDS.put("UIElementContextBinding", Integer.valueOf(3)); //$NON-NLS-1$
        FEATURE_IDS.put("UIElementEventBinding", Integer.valueOf(4)); //$NON-NLS-1$
        FEATURE_IDS.put("AbstractView", Integer.valueOf(5)); //$NON-NLS-1$
        FEATURE_IDS.put("EmptyView", Integer.valueOf(6)); //$NON-NLS-1$
        FEATURE_IDS.put("InterfaceView", Integer.valueOf(7)); //$NON-NLS-1$
        FEATURE_IDS.put("UIElementDictionaryBinding", Integer.valueOf(8)); //$NON-NLS-1$
        FEATURE_IDS.put("A_ContextBindings_ViewElement", Integer.valueOf(9)); //$NON-NLS-1$
        FEATURE_IDS.put("A_BoundContextElement_uIElementContextBinding", Integer.valueOf(10)); //$NON-NLS-1$
        FEATURE_IDS.put("A_viewContainer_ViewContainerUIElement", Integer.valueOf(11)); //$NON-NLS-1$
        FEATURE_IDS.put("A_EventBindings_ViewElement", Integer.valueOf(12)); //$NON-NLS-1$
        FEATURE_IDS.put("A_RootUIElementContainer_view", Integer.valueOf(13)); //$NON-NLS-1$
        FEATURE_IDS.put("A_UIElementProperty_uIElementContextBinding", Integer.valueOf(14)); //$NON-NLS-1$
        FEATURE_IDS.put("A_DictionaryBindings_ViewElement", Integer.valueOf(15)); //$NON-NLS-1$
        FEATURE_IDS.put("A_UIElementProperty_uIElementDictionaryBinding", Integer.valueOf(16)); //$NON-NLS-1$
        FEATURE_IDS.put("A_TypeComponentPathElements_uIElementContextBinding", Integer.valueOf(17)); //$NON-NLS-1$
        FEATURE_IDS.put("A_View_ViewContainers", Integer.valueOf(18)); //$NON-NLS-1$
        FEATURE_IDS.put("A_InterfaceViewContainers_WindowViewContainers", Integer.valueOf(19)); //$NON-NLS-1$
        FEATURE_IDS.put("A_ViewController_View", Integer.valueOf(20)); //$NON-NLS-1$
        FEATURE_IDS.put("A_BoundAction_uIElementEventBinding", Integer.valueOf(21)); //$NON-NLS-1$
        FEATURE_IDS.put("A_UIElementEvent_uIElementEventBinding", Integer.valueOf(22)); //$NON-NLS-1$
    }

    // constructors    
    public ViewPackageImpl()
    {
        super();
    }
    public ViewPackageImpl(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject)
    {
        super(workspace, mofId, immediatePackage, metaObject);
    }
    // internal enumeration creators
    // internal structure type creators
    // nested packages
    public com.sap.tc.moin.repository.mmi.reflect.RefPackage getUielement(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refPackage(connection, "uielement"); //$NON-NLS-1$
    }
    // classes
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getView(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "View"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getViewContainer(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "ViewContainer"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getUielementContextBinding(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "UIElementContextBinding"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getUielementEventBinding(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "UIElementEventBinding"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getAbstractView(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "AbstractView"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getEmptyView(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "EmptyView"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getInterfaceView(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "InterfaceView"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefClass getUielementDictionaryBinding(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refClass(connection, "UIElementDictionaryBinding"); //$NON-NLS-1$
    }
    // associations
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAContextBindingsViewElement(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_ContextBindings_ViewElement"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getABoundContextElementUIelementContextBinding(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_BoundContextElement_uIElementContextBinding"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAViewContainerViewContainerUielement(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_viewContainer_ViewContainerUIElement"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAEventBindingsViewElement(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_EventBindings_ViewElement"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getARootUielementContainerView(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_RootUIElementContainer_view"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAUielementPropertyUIelementContextBinding(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_UIElementProperty_uIElementContextBinding"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getADictionaryBindingsViewElement(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_DictionaryBindings_ViewElement"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAUielementPropertyUIelementDictionaryBinding(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_UIElementProperty_uIElementDictionaryBinding"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getATypeComponentPathElementsUIelementContextBinding(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_TypeComponentPathElements_uIElementContextBinding"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAViewViewContainers(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_View_ViewContainers"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAInterfaceViewContainersWindowViewContainers(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_InterfaceViewContainers_WindowViewContainers"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAViewControllerView(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_ViewController_View"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getABoundActionUIelementEventBinding(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_BoundAction_uIElementEventBinding"); //$NON-NLS-1$
    }
    public com.sap.tc.moin.repository.mmi.reflect.RefAssociation getAUielementEventUIelementEventBinding(com.sap.tc.moin.repository.core.CoreConnection connection) {
        return  refAssociation(connection, "A_UIElementEvent_uIElementEventBinding"); //$NON-NLS-1$
    }
    // structure type creators

    protected java.lang.Object create___Extent(java.lang.Object workspace, java.lang.String mofId, com.sap.tc.moin.repository.mmi.reflect.RefPackage immediatePackage, com.sap.tc.moin.repository.mmi.reflect.RefObject metaObject) {
        java.lang.String name = ((com.sap.tc.moin.repository.mmi.model.ModelElement) metaObject).getName();
        com.sap.tc.moin.repository.mmi.reflect.RefBaseObject result = null;
        try {
            switch (FEATURE_IDS.get(name)) {
                case 0:
                    return new com.sap.ide.metamodel.webdynpro.component.view.uielement.__impl.UielementPackageImpl(workspace, mofId, immediatePackage, metaObject);
                case 1:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.ide.metamodel.webdynpro.component.view.__impl.ViewImpl")); //$NON-NLS-1$
                case 2:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.ide.metamodel.webdynpro.component.view.__impl.ViewContainerImpl")); //$NON-NLS-1$
                case 3:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.ide.metamodel.webdynpro.component.view.__impl.UielementContextBindingImpl")); //$NON-NLS-1$
                case 4:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.ide.metamodel.webdynpro.component.view.__impl.UielementEventBindingImpl")); //$NON-NLS-1$
                case 5:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject);
                case 6:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.ide.metamodel.webdynpro.component.view.__impl.EmptyViewImpl")); //$NON-NLS-1$
                case 7:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.ide.metamodel.webdynpro.component.view.__impl.InterfaceViewImpl")); //$NON-NLS-1$
                case 8:
                    return new com.sap.tc.moin.repository.core.jmi.reflect.RefClassImpl(workspace, mofId, immediatePackage, metaObject, Class.forName("com.sap.ide.metamodel.webdynpro.component.view.__impl.UielementDictionaryBindingImpl")); //$NON-NLS-1$
                case 9:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.AContextBindingsViewElementImpl(workspace, mofId, immediatePackage, metaObject);
                case 10:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.ABoundContextElementUIelementContextBindingImpl(workspace, mofId, immediatePackage, metaObject);
                case 11:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.AViewContainerViewContainerUielementImpl(workspace, mofId, immediatePackage, metaObject);
                case 12:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.AEventBindingsViewElementImpl(workspace, mofId, immediatePackage, metaObject);
                case 13:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.ARootUielementContainerViewImpl(workspace, mofId, immediatePackage, metaObject);
                case 14:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.AUielementPropertyUIelementContextBindingImpl(workspace, mofId, immediatePackage, metaObject);
                case 15:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.ADictionaryBindingsViewElementImpl(workspace, mofId, immediatePackage, metaObject);
                case 16:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.AUielementPropertyUIelementDictionaryBindingImpl(workspace, mofId, immediatePackage, metaObject);
                case 17:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.ATypeComponentPathElementsUIelementContextBindingImpl(workspace, mofId, immediatePackage, metaObject);
                case 18:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.AViewViewContainersImpl(workspace, mofId, immediatePackage, metaObject);
                case 19:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.AInterfaceViewContainersWindowViewContainersImpl(workspace, mofId, immediatePackage, metaObject);
                case 20:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.AViewControllerViewImpl(workspace, mofId, immediatePackage, metaObject);
                case 21:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.ABoundActionUIelementEventBindingImpl(workspace, mofId, immediatePackage, metaObject);
                case 22:
                    return new com.sap.ide.metamodel.webdynpro.component.view.__impl.AUielementEventUIelementEventBindingImpl(workspace, mofId, immediatePackage, metaObject);
                default:
                    throw new com.sap.tc.moin.repository.mmi.reflect.InvalidCallException(name, null, "create___Extent()"); //$NON-NLS-1$
        }
        }
        catch(com.sap.tc.moin.repository.mmi.reflect.JmiException ex) {
            throw ex;
        }
        catch(java.lang.Exception ex) {
            throw new com.sap.tc.moin.repository.mmi.reflect.JmiException(ex);
        }        
    }

    @SuppressWarnings("unchecked")
    public java.lang.Class<com.sap.ide.metamodel.webdynpro.component.view.ViewPackage> get___JmiInterface() {
        return com.sap.ide.metamodel.webdynpro.component.view.ViewPackage.class;
    }
    
    protected void initialize() {
        if (___refPackages == null) {
            ___refPackages = new java.util.ArrayList<RefPackageAndName>(1);
            ___refPackagesByName = new java.util.HashMap<String, RefPackageAndName>();
            @SuppressWarnings("unused")
            java.lang.String name = ""; //$NON-NLS-1$
            @SuppressWarnings("unused")
            RefPackageAndName rpan = null;
            name = "uielement"; //$NON-NLS-1$
            rpan = new RefPackageAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.uielement.UielementPackage", false); //$NON-NLS-1$
            ___refPackages.add(rpan);
            ___refPackagesByName.put(name, rpan);
        }
  
        if (___refClasses == null) {
            ___refClasses = new java.util.ArrayList<RefClassAndName>(8);
            ___refClassesByName = new java.util.HashMap<String, RefClassAndName>();
            java.lang.String name = ""; //$NON-NLS-1$
            RefClassAndName rcan = null;
            name = "View"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.View"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
            name = "ViewContainer"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.ViewContainer"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
            name = "UIElementContextBinding"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.UielementContextBinding"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
            name = "UIElementEventBinding"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.UielementEventBinding"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
            name = "AbstractView"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AbstractView"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
            name = "EmptyView"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.EmptyView"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
            name = "InterfaceView"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.InterfaceView"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
            name = "UIElementDictionaryBinding"; //$NON-NLS-1$
            rcan = new RefClassAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.UielementDictionaryBinding"); //$NON-NLS-1$
            ___refClasses.add(rcan);
            ___refClassesByName.put(name, rcan);
        }
  
        if (___refAssociations == null) {
            ___refAssociations = new java.util.ArrayList<RefAssociationAndName>(14);
            ___refAssociationsByName = new java.util.HashMap<String, RefAssociationAndName>();
            @SuppressWarnings("unused")
            java.lang.String name = ""; //$NON-NLS-1$
            @SuppressWarnings("unused")
            RefAssociationAndName raan = null;
            name = "A_ContextBindings_ViewElement"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AContextBindingsViewElement"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_BoundContextElement_uIElementContextBinding"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.ABoundContextElementUIelementContextBinding"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_viewContainer_ViewContainerUIElement"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AViewContainerViewContainerUielement"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_EventBindings_ViewElement"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AEventBindingsViewElement"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_RootUIElementContainer_view"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.ARootUielementContainerView"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_UIElementProperty_uIElementContextBinding"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AUielementPropertyUIelementContextBinding"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_DictionaryBindings_ViewElement"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.ADictionaryBindingsViewElement"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_UIElementProperty_uIElementDictionaryBinding"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AUielementPropertyUIelementDictionaryBinding"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_TypeComponentPathElements_uIElementContextBinding"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.ATypeComponentPathElementsUIelementContextBinding"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_View_ViewContainers"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AViewViewContainers"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_InterfaceViewContainers_WindowViewContainers"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AInterfaceViewContainersWindowViewContainers"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_ViewController_View"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AViewControllerView"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_BoundAction_uIElementEventBinding"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.ABoundActionUIelementEventBinding"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
            name = "A_UIElementEvent_uIElementEventBinding"; //$NON-NLS-1$
            raan = new RefAssociationAndName(name, "com.sap.ide.metamodel.webdynpro.component.view.AUielementEventUIelementEventBinding"); //$NON-NLS-1$
            ___refAssociations.add(raan);
            ___refAssociationsByName.put(name, raan);
        }
    }
    
    @Override
    public com.sap.tc.moin.repository.spi.core.Wrapper<com.sap.ide.metamodel.webdynpro.component.view.__impl.ViewPackageImpl> createWrapper(com.sap.tc.moin.repository.core.CoreConnection conn, boolean synchronize) {
        return new com.sap.ide.metamodel.webdynpro.component.view.__impl.ViewPackageWrapper(conn, this, synchronize);
    }

}