/**
 * Generated by the MOIN Generator Version 3.0
 **/

package com.sap.tc.moin.testcases.case010;

/**
 * This interface is not intended to be implemented by clients.
 */
public interface A10 extends com.sap.tc.moin.repository.mmi.reflect.RefObject {

    /**
     * Descriptors for all features of this MofClass and its supertypes.
     */
    public static final Descriptors DESCRIPTORS = new Descriptors( );

    // class extent descriptor
    /**
     * Extent descriptor
     */
    public final com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, com.sap.tc.moin.testcases.case010.A10> CLASS_DESCRIPTOR = new com.sap.tc.moin.repository.mmi.descriptors.ClassDescriptor<com.sap.tc.moin.repository.mmi.reflect.RefClass, com.sap.tc.moin.testcases.case010.A10>("45F120A5D3E548702DE84018177382797E661C28", "test.sap.com/tc/moin/metamodel/testcases", "testcases", "case010", "A10"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ 

    
    // references
    public java.util.Collection<com.sap.tc.moin.testcases.case010.B10> getManyBsNotChangeable() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.List<com.sap.tc.moin.testcases.case010.B10> getManyBsOrdered() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public java.util.Collection<com.sap.tc.moin.testcases.case010.B10> getManyBsChangeable() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public com.sap.tc.moin.testcases.case010.B10 getNavigable() throws com.sap.tc.moin.repository.mmi.reflect.JmiException;
    public void setNavigable(com.sap.tc.moin.testcases.case010.B10 newValue) throws com.sap.tc.moin.repository.mmi.reflect.JmiException;


    public static final class Descriptors {
        Descriptors( ) { 
        }
        private com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,java.util.Collection<com.sap.tc.moin.testcases.case010.B10>> __manyBsNotChangeable;
        /**
         * Returns the descriptor for the <code>manyBsNotChangeable</code> reference.
         * @return  the descriptor for the <code>manyBsNotChangeable</code> reference
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,java.util.Collection<com.sap.tc.moin.testcases.case010.B10>> MANY_BS_NOT_CHANGEABLE( ) {
            if ( __manyBsNotChangeable == null ) {
                __manyBsNotChangeable = new com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,java.util.Collection<com.sap.tc.moin.testcases.case010.B10>>( "45F120A516D22686CAC848C13AA699B3D9259E3B", "test.sap.com/tc/moin/metamodel/testcases", new java.lang.String[] { "testcases", "case010", "A10", "manyBsNotChangeable" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ 
            }
            return __manyBsNotChangeable;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,java.util.List<com.sap.tc.moin.testcases.case010.B10>> __manyBsOrdered;
        /**
         * Returns the descriptor for the <code>manyBsOrdered</code> reference.
         * @return  the descriptor for the <code>manyBsOrdered</code> reference
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,java.util.List<com.sap.tc.moin.testcases.case010.B10>> MANY_BS_ORDERED( ) {
            if ( __manyBsOrdered == null ) {
                __manyBsOrdered = new com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,java.util.List<com.sap.tc.moin.testcases.case010.B10>>( "45F120A5E652D0A38752435F38A4B00C0A5ED950", "test.sap.com/tc/moin/metamodel/testcases", new java.lang.String[] { "testcases", "case010", "A10", "manyBsOrdered" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ 
            }
            return __manyBsOrdered;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,java.util.Collection<com.sap.tc.moin.testcases.case010.B10>> __manyBsChangeable;
        /**
         * Returns the descriptor for the <code>manyBsChangeable</code> reference.
         * @return  the descriptor for the <code>manyBsChangeable</code> reference
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,java.util.Collection<com.sap.tc.moin.testcases.case010.B10>> MANY_BS_CHANGEABLE( ) {
            if ( __manyBsChangeable == null ) {
                __manyBsChangeable = new com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,java.util.Collection<com.sap.tc.moin.testcases.case010.B10>>( "45F120A5A436B6DB837849FC3E798E0AEFE7D573", "test.sap.com/tc/moin/metamodel/testcases", new java.lang.String[] { "testcases", "case010", "A10", "manyBsChangeable" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ 
            }
            return __manyBsChangeable;
        }
        private com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,com.sap.tc.moin.testcases.case010.B10> __navigable;
        /**
         * Returns the descriptor for the <code>navigable</code> reference.
         * @return  the descriptor for the <code>navigable</code> reference
         */
        public synchronized com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,com.sap.tc.moin.testcases.case010.B10> NAVIGABLE( ) {
            if ( __navigable == null ) {
                __navigable = new com.sap.tc.moin.repository.mmi.descriptors.ReferenceDescriptor<com.sap.tc.moin.repository.mmi.model.Reference,com.sap.tc.moin.testcases.case010.A10,com.sap.tc.moin.testcases.case010.B10>( "45F120A52431E40CF0994AE902F792E07B04C56E", "test.sap.com/tc/moin/metamodel/testcases", new java.lang.String[] { "testcases", "case010", "A10", "navigable" } ); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ 
            }
            return __navigable;
        }
    }
}    